#!/bin/sh -e
# Generated by patch2vi from unified diff
# Available separators: 0003-0010 0013-0014 0016-0037 0102 0104-0105 0107-0110 0112 0116 0120-0123 0125-0127 0131-0132 0136 0172 0176-0377

VI=${VI:-vi}
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi binary" >&2
    exit 1
fi

# Env switches:
# Phase 1 (search/mark) reports nothing by default
#   DBG1=1 reports failures and which fallback anchor
#   resolved a group, QF1=1 also quits on failure
# Phase 2 (edits) reports and quits by default
#   DBG2=1 silences it, QF2=1 keeps going after an error
# INTR=1 enters vi at the failing code line in this
#   script, for state inspection mid execution

# Body too large for EXINIT/argv: stage it in a file
( : > /tmp/p2vi.$$ ) 2>/dev/null && P2VIF=/tmp/p2vi.$$ || P2VIF=./p2vi.$$
trap 'rm -f "$P2VIF"' EXIT

# Patch: led.c
printf '%s%s%s\n' '|sc! |:vis 3ic 0217reg prFp FAIL %@219pr? %@212214reg ? %@217? %@211216reg ? %@220221reg vis 2q!1211reg ? %@221'\
"${DBG1:+213reg ? %@217? %@210215reg ? %@220}\
${DBG2:+ya!214ya!216}\
${QF1:+210reg vis 2q!1}\
${QF2:+ya!221}\
${INTR:+212reg |sc|vis 2:fr 0:e $0:83reg %@47:%f> 219reg %@219:&Q:b0:|sc! |:vis 3q1}"\
'fr 98b0%ya 98?0?
%f> 	return i-s;
}

static int search\(const char \*pattern, int l\)
\{1??0?
1??+3m 11q0?
%f> static int search\(const char \*pattern, int l\)
\{2??0?
2??m 1220reg p OK led.c:12:a22sc %? %@2152sc!1q0?
;0fr.,$f> ^static int search\(const char \*pattern, int l\)$3??0?
3??m 1220reg p OK led.c:12:a32sc %? %@2152sc!fr 981qfr 980?
%f> 	return i-s;
}

4??0?
4??+3m 1220reg p OK led.c:12:a42sc %? %@2152sc!1q0?
;0fr.,$f> ^\{$5??0?
5??-1m 1220reg p OK led.c:12:a52sc %? %@2152sc!fr 981qfr 980?
%f> ......n.....
}

....i...n......c....... .h...\*.....rn..... ..
\{6??0?
6??+3m 1220reg p OK led.c:12:a62sc %? %@2152sc!1q0?
grp 1%f> 	return i-s;.*?
}.*?
.*?
(static int search\(const char \*pattern, int l\))7??0?
grp 07??m 1220reg p OK led.c:12:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> \{
	register const char \*i;
	for \(i=s; \*i && \*i != delim; \+\+i\);.*(	sbuf_nul4\(suggestsb\))
	return suggestsb->s_n;
}8??0?
grp 08??-22m 1220reg p OK led.c:12:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> static sbuf \*suggestsb;
static sbuf \*acsb;
sbuf \*led_attsb;.*(static void file_index\(struct lbuf \*buf\))
\{
	char reg\[] = "\[\^\\t !-/:-@\[-\\\\]\^`\{-\\x7f]\+";9??0?
grp 09??-26m 1220reg p OK led.c:12:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg led.c:122sc %? %@2132sc!0?
?0?
%f+ \{
	if \(!\*pattern\)
		return 0;
	sbuf_cut\(suggestsb, 0\)
	sbuf_smake\(sylsb, 1024\)1??0?
1??+1m 21q0?
%f+ 	if \(!\*pattern\)
		return 0;
	sbuf_cut\(suggestsb, 0\)
	sbuf_smake\(sylsb, 1024\)2??0?
2??m 2220reg p OK led.c:14:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^	if \(!\*pattern\)$3??0?
3??m 2220reg p OK led.c:14:a32sc %? %@2152sc!fr 981qfr 980?
;0fr.,$f+ ^\{$4??0?
4??+1m 2220reg p OK led.c:14:a42sc %? %@2152sc!fr 981qfr 980?
%f+ 		return 0;
	sbuf_cut\(suggestsb, 0\)
	sbuf_smake\(sylsb, 1024\)5??0?
5??-1m 2220reg p OK led.c:14:a52sc %? %@2152sc!1q0?
%f+ \{
......\*pat.e...
..r..u.....
	s..f.......g.....b..0\)
.s..._sma...............6??0?
6??+1m 2220reg p OK led.c:14:a62sc %? %@2152sc!1q0?
grp 1%f+ \{.*?
(	if \(!\*pattern\))7??0?
grp 07??m 2220reg p OK led.c:14:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> \{
	register const char \*i;
	for \(i=s; \*i && \*i != delim; \+\+i\);.*(	sbuf_nul4\(suggestsb\))
	return suggestsb->s_n;
}8??0?
grp 08??-20m 2220reg p OK led.c:14:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> static sbuf \*suggestsb;
static sbuf \*acsb;
sbuf \*led_attsb;.*(static void file_index\(struct lbuf \*buf\))
\{
	char reg\[] = "\[\^\\t !-/:-@\[-\\\\]\^`\{-\\x7f]\+";9??0?
grp 09??-24m 2220reg p OK led.c:14:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg led.c:142sc %? %@2132sc!0?
?0?
%f+ 		return 0;
	sbuf_cut\(suggestsb, 0\)
	sbuf_smake\(sylsb, 1024\)
	char \*part = strstr\(acsb->s, pattern\);
	while \(part\) \{
		char \*part1 = part;
		while \(\*part != '\''\\n'\''\)1??0?
1??+3m 31q0?
%f+ 	char \*part = strstr\(acsb->s, pattern\);
	while \(part\) \{
		char \*part1 = part;
		while \(\*part != '\''\\n'\''\)2??0?
2??m 3220reg p OK led.c:18:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^	char \*part = strstr\(acsb->s, pattern\);$3??0?
3??m 3220reg p OK led.c:18:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 		return 0;
	sbuf_cut\(suggestsb, 0\)
	sbuf_smake\(sylsb, 1024\)4??0?
4??+3m 3220reg p OK led.c:18:a42sc %? %@2152sc!1q0?
%f+ 	while \(part\) \{
		char \*part1 = part;
		while \(\*part != '\''\\n'\''\)5??0?
5??-1m 3220reg p OK led.c:18:a52sc %? %@2152sc!1q0?
%f+ .........0;
.sb...........e...b,.0.
	.....s......yl... 1....
	c.....p.r..=.........c...>s. ...t.....
..h............
..c.......r.....p..t.
...h................n'\''.6??0?
6??+3m 3220reg p OK led.c:18:a62sc %? %@2152sc!1q0?
grp 1%f+ 		return 0;.*?
	sbuf_cut\(suggestsb, 0\).*?
	sbuf_smake\(sylsb, 1024\).*?
(	char \*part = strstr\(acsb->s, pattern\);)7??0?
grp 07??m 3220reg p OK led.c:18:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> \{
	register const char \*i;
	for \(i=s; \*i && \*i != delim; \+\+i\);.*(	sbuf_nul4\(suggestsb\))
	return suggestsb->s_n;
}8??0?
grp 08??-16m 3220reg p OK led.c:18:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> static sbuf \*suggestsb;
static sbuf \*acsb;
sbuf \*led_attsb;.*(static void file_index\(struct lbuf \*buf\))
\{
	char reg\[] = "\[\^\\t !-/:-@\[-\\\\]\^`\{-\\x7f]\+";9??0?
grp 09??-20m 3220reg p OK led.c:18:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg led.c:182sc %? %@2132sc!0?
?0?
%f+ 		while \(\*part != '\''\\n'\''\)
			part--;
		int len = dstrlen\(\+\+part, '\''\\n'\''\);
		if \(len\+\+ != l\) \{
			if \(part == part1\)
				sbuf_mem\(suggestsb, part, len\)1??0?
1??+3m 41q0?
%f+ 		if \(len\+\+ != l\) \{
			if \(part == part1\)
				sbuf_mem\(suggestsb, part, len\)2??0?
2??m 4220reg p OK led.c:24:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^		if \(len\+\+ != l\) \{$3??0?
3??m 4220reg p OK led.c:24:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 		while \(\*part != '\''\\n'\''\)
			part--;
		int len = dstrlen\(\+\+part, '\''\\n'\''\);4??0?
4??+3m 4220reg p OK led.c:24:a42sc %? %@2152sc!1q0?
%f+ 			if \(part == part1\)
				sbuf_mem\(suggestsb, part, len\)5??0?
5??-1m 4220reg p OK led.c:24:a52sc %? %@2152sc!1q0?
%f+ ....il.........!..'\''....
	.........
	.....l.n......rle.\(...a....'\''.n...
	..................
	..i. \(p..t....p.....
......u...e.\(su....ts......., ....6??0?
6??+3m 4220reg p OK led.c:24:a62sc %? %@2152sc!1q0?
grp 1%f+ 		while \(\*part != '\''\\n'\''\).*?
			part--;.*?
		int len = dstrlen\(\+\+part, '\''\\n'\''\);.*?
(		if \(len\+\+ != l\) \{)7??0?
grp 07??m 4220reg p OK led.c:24:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> \{
	register const char \*i;
	for \(i=s; \*i && \*i != delim; \+\+i\);.*(	sbuf_nul4\(suggestsb\))
	return suggestsb->s_n;
}8??0?
grp 08??-10m 4220reg p OK led.c:24:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> static sbuf \*suggestsb;
static sbuf \*acsb;
sbuf \*led_attsb;.*(static void file_index\(struct lbuf \*buf\))
\{
	char reg\[] = "\[\^\\t !-/:-@\[-\\\\]\^`\{-\\x7f]\+";9??0?
grp 09??-14m 4220reg p OK led.c:24:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg led.c:242sc %? %@2132sc!0?
?0?
%f+ 			if \(part == part1\)
				sbuf_mem\(suggestsb, part, len\)
			else
				sbuf_mem\(sylsb, part, len\)
		}1??0?
1??+2m 51q0?
%f+ 			else
				sbuf_mem\(sylsb, part, len\)
		}2??0?
2??m 5220reg p OK led.c:27:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^			else$3??0?
3??m 5220reg p OK led.c:27:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 			if \(part == part1\)
				sbuf_mem\(suggestsb, part, len\)4??0?
4??+2m 5220reg p OK led.c:27:a42sc %? %@2152sc!1q0?
%f+ 				sbuf_mem\(sylsb, part, len\)
		}5??0?
5??-1m 5220reg p OK led.c:27:a52sc %? %@2152sc!1q0?
%f+ .	....\(...t.== ..r...
	......._.em.s...........ar.. .en.
...e...
...	s..f..........,.p.... l..\)
..}6??0?
6??+2m 5220reg p OK led.c:27:a62sc %? %@2152sc!1q0?
grp 1%f+ 			if \(part == part1\).*?
				sbuf_mem\(suggestsb, part, len\).*?
(			else)7??0?
grp 07??m 5220reg p OK led.c:27:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> \{
	register const char \*i;
	for \(i=s; \*i && \*i != delim; \+\+i\);.*(	sbuf_nul4\(suggestsb\))
	return suggestsb->s_n;
}8??0?
grp 08??-7m 5220reg p OK led.c:27:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> static sbuf \*suggestsb;
static sbuf \*acsb;
sbuf \*led_attsb;.*(static void file_index\(struct lbuf \*buf\))
\{
	char reg\[] = "\[\^\\t !-/:-@\[-\\\\]\^`\{-\\x7f]\+";9??0?
grp 09??-11m 5220reg p OK led.c:27:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg led.c:272sc %? %@2132sc!0?
?0?
%f+ 				sbuf_mem\(sylsb, part, len\)
		}
		part = strstr\(part\+len, pattern\);
	}
	sbuf_mem\(suggestsb, sylsb->s, sylsb->s_n\)
	free\(sylsb->s\);1??0?
1??+2m 61q0?
%f+ 		part = strstr\(part\+len, pattern\);
	}
	sbuf_mem\(suggestsb, sylsb->s, sylsb->s_n\)
	free\(sylsb->s\);2??0?
2??m 6220reg p OK led.c:30:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^		part = strstr\(part\+len, pattern\);$3??0?
3??m 6220reg p OK led.c:30:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 				sbuf_mem\(sylsb, part, len\)
		}4??0?
4??+2m 6220reg p OK led.c:30:a42sc %? %@2152sc!1q0?
%f+ 	}
	sbuf_mem\(suggestsb, sylsb->s, sylsb->s_n\)
	free\(sylsb->s\);5??0?
5??-1m 6220reg p OK led.c:30:a52sc %? %@2152sc!1q0?
%f+ ..		s......m\(....., p.r....e..
.	}
..........t.st.....t.l..,..a.t....;
	.
....f.m.....g..s..b,.sy....>...s..s......\)
	...e.....b.>...6??0?
6??+2m 6220reg p OK led.c:30:a62sc %? %@2152sc!1q0?
grp 1%f+ 				sbuf_mem\(sylsb, part, len\).*?
		}.*?
(		part = strstr\(part\+len, pattern\);)7??0?
grp 07??m 6220reg p OK led.c:30:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> \{
	register const char \*i;
	for \(i=s; \*i && \*i != delim; \+\+i\);.*(	sbuf_nul4\(suggestsb\))
	return suggestsb->s_n;
}8??0?
grp 08??-4m 6220reg p OK led.c:30:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> static sbuf \*suggestsb;
static sbuf \*acsb;
sbuf \*led_attsb;.*(static void file_index\(struct lbuf \*buf\))
\{
	char reg\[] = "\[\^\\t !-/:-@\[-\\\\]\^`\{-\\x7f]\+";9??0?
grp 09??-8m 6220reg p OK led.c:30:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg led.c:302sc %? %@2132sc!0?
?0?
%f+ 	char \*cs;
	int len, c, i;
	sbuf \*reg;
	do \{
		led_printparts\(sb, pre, ps, \*post, postn, poff\);
		len = sb->s_n;1??0?
1??+2m 71q0?
%f+ 	char \*cs;
	int len, c, i;
	sbuf \*reg;4??0?
4??+2m 7220reg p OK led.c:430:a42sc %? %@2152sc!1q0?
grp 1%f+ 	char \*cs;.*?
	int len, c, i;.*?
(	sbuf \*reg;)7??0?
grp 07??m 7220reg p OK led.c:430:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> static int led_line\(sbuf \*sb, int ps, int pre, char \*\*post, int postn, char \*\*postref,
	int ai_max, int \*poff, int \*kmap, ins_state \*is, int orow, int crow, int ctop, int flg\)
\{.*(		c = term_read\(TK_CTL\('\''l'\''\)\);)
		noredraw:
		switch \(c\) \{8??0?
grp 08??-4m 7220reg p OK led.c:430:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	restore\(xvis\)
	restore\(xexec_dep\)
}.*(		case TK_CTL\('\''h'\''\):)
			c = 127;
		case 127:9??0?
grp 09??-7m 7220reg p OK led.c:430:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg led.c:4302sc %? %@2132sc!0?
?0?
%f+ 		case TK_CTL\('\''n'\''\):
			if \(!suggestsb\)
				continue;
			is->lsug = is->sug_pt >= 0 \? is->sug_pt : led_lastword\(sb->s \+ pre\) \+ pre;
			if \(is->_sug\) \{
				if \(suggestsb->s_n == is->sug - suggestsb->s\)
					continue;1??0?
1??+3m 81q0?
%f+ 			is->lsug = is->sug_pt >= 0 \? is->sug_pt : led_lastword\(sb->s \+ pre\) \+ pre;
			if \(is->_sug\) \{
				if \(suggestsb->s_n == is->sug - suggestsb->s\)
					continue;2??0?
2??m 8220reg p OK led.c:529:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^			is->lsug = is->sug_pt >= 0 \? is->sug_pt : led_lastword\(sb->s \+ pre\) \+ pre;$3??0?
3??m 8220reg p OK led.c:529:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 		case TK_CTL\('\''n'\''\):
			if \(!suggestsb\)
				continue;4??0?
4??+3m 8220reg p OK led.c:529:a42sc %? %@2152sc!1q0?
%f+ 			if \(is->_sug\) \{
				if \(suggestsb->s_n == is->sug - suggestsb->s\)
					continue;5??0?
5??-1m 8220reg p OK led.c:529:a52sc %? %@2152sc!1q0?
%f+ 	.c..e..K..T.\(...\).
...i....s....st...
	.......i....
	...s....u. =....>............. i...s.g... . ..._...t..r....-.. ...... ....e;
......\(.....s.g...
....i...s.......b..s.n ...i...su. -......s...-...
...	..o.ti....6??0?
6??+3m 8220reg p OK led.c:529:a62sc %? %@2152sc!1q0?
grp 1%f+ 		case TK_CTL\('\''n'\''\):.*?
			if \(!suggestsb\).*?
				continue;.*?
(			is->lsug = is->sug_pt >= 0 \? is->sug_pt : led_lastword\(sb->s \+ pre\) \+ pre;)7??0?
grp 07??m 8220reg p OK led.c:529:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 			char buf\[100];
			itoa\(is->sug_pt, buf\);
			led_info\(buf\).*(				redo_suggest:)
				if \(!\(is->_sug = strchr\(is->sug, '\''\\n'\''\)\)\) \{
					is->sug = suggestsb->s;8??0?
grp 08??-4m 8220reg p OK led.c:529:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 			continue;
		case TK_CTL\('\''x'\''\):
			is->sug_pt = is->sug_pt == len \? -1 : len;.*(					goto lookup;)
				}
				suggest:9??0?
grp 09??-7m 8220reg p OK led.c:529:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg led.c:5292sc %? %@2132sc!0?
?0?
%f+ 				}
				suggest:
				\*is->_sug = '\''\\0'\'';
				sbuf_cut\(sb, is->lsug\)
				sbuf_str\(sb, is->sug\)
				is->sug = is->_sug\+1;
				continue;
			}1??0?
1??+3m 91q0?
%f+ 				sbuf_cut\(sb, is->lsug\)
				sbuf_str\(sb, is->sug\)
				is->sug = is->_sug\+1;
				continue;
			}2??0?
2??m 9220reg p OK led.c:540:a22sc %? %@2152sc!1q0?
%f+ 				sbuf_cut\(sb, is->lsug\)
				sbuf_str\(sb, is->sug\)3??0?
3??m 9220reg p OK led.c:540:a32sc %? %@2152sc!1q0?
%f+ 				}
				suggest:
				\*is->_sug = '\''\\0'\'';4??0?
4??+3m 9220reg p OK led.c:540:a42sc %? %@2152sc!1q0?
%f+ 				is->sug = is->_sug\+1;
				continue;
			}5??0?
5??-2m 9220reg p OK led.c:540:a52sc %? %@2152sc!1q0?
%f+ .	..}
	..	...g....
			.....>..u..= ..0'\''.
.	....u._.....b...s..l..g.
..		s.u._.t..........su..
.....s->..... ......u....
.....o.......
..	.6??0?
6??+3m 9220reg p OK led.c:540:a62sc %? %@2152sc!1q0?
grp 1%f+ 				}.*?
				suggest:.*?
				\*is->_sug = '\''\\0'\'';.*?
(				sbuf_cut\(sb, is->lsug\))7??0?
grp 07??m 9220reg p OK led.c:540:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 				if \(!\(is->_sug = strchr\(is->sug, '\''\\n'\''\)\)\) \{
					is->sug = suggestsb->s;
					goto lookup;.*(				goto suggest;)
			}
			continue;8??0?
grp 08??-10m 9220reg p OK led.c:540:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 				if \(suggestsb->s_n == is->sug - suggestsb->s\)
					continue;
				redo_suggest:.*(		case TK_CTL\('\''b'\''\):)
			if \(ai_max >= 0\) \{
				pac:;9??0?
grp 09??-13m 9220reg p OK led.c:540:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg led.c:5402sc %? %@2132sc!0?
?0?
%f+ 				continue;
			}
			lookup:
			if \(search\(sb->s \+ is->lsug, len - is->lsug\)\) \{
				is->sug = suggestsb->s;
				if \(!\(is->_sug = strchr\(is->sug, '\''\\n'\''\)\)\)
					continue;1??0?
1??+3m 101q0?
%f+ 			if \(search\(sb->s \+ is->lsug, len - is->lsug\)\) \{
				is->sug = suggestsb->s;
				if \(!\(is->_sug = strchr\(is->sug, '\''\\n'\''\)\)\)
					continue;2??0?
2??m 10220reg p OK led.c:546:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^			if \(search\(sb->s \+ is->lsug, len - is->lsug\)\) \{$3??0?
3??m 10220reg p OK led.c:546:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 				continue;
			}
			lookup:4??0?
4??+3m 10220reg p OK led.c:546:a42sc %? %@2152sc!1q0?
%f+ 				is->sug = suggestsb->s;
				if \(!\(is->_sug = strchr\(is->sug, '\''\\n'\''\)\)\)
					continue;5??0?
5??-1m 10220reg p OK led.c:546:a52sc %? %@2152sc!1q0?
%f+ ..		....in...
	.	.
		..o...p:
	......s..........s...is-..s............-.l...\)...
.	....-..u.......ge........
	.		.......s-......=....c.......s.........\).
	.	.	c....nu..6??0?
6??+3m 10220reg p OK led.c:546:a62sc %? %@2152sc!1q0?
grp 1%f+ 				continue;.*?
			}.*?
			lookup:.*?
(			if \(search\(sb->s \+ is->lsug, len - is->lsug\)\) \{)7??0?
grp 07??m 10220reg p OK led.c:546:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 				if \(!\(is->_sug = strchr\(is->sug, '\''\\n'\''\)\)\) \{
					is->sug = suggestsb->s;
					goto lookup;.*(				goto suggest;)
			}
			continue;8??0?
grp 08??-4m 10220reg p OK led.c:546:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 				if \(suggestsb->s_n == is->sug - suggestsb->s\)
					continue;
				redo_suggest:.*(		case TK_CTL\('\''b'\''\):)
			if \(ai_max >= 0\) \{
				pac:;9??0?
grp 09??-7m 10220reg p OK led.c:546:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg led.c:5462sc %? %@2132sc!0?
?0?
%f+ 				int r = crow-ctop\+1;
				if \(is->sug\)
					goto pac_;
				i = is->sug_pt >= 0 \? is->sug_pt : led_lastword\(sb->s \+ pre\) \+ pre;
				if \(suggestsb && search\(sb->s \+ i, sb->s_n - i\)\) \{
					is->sug = suggestsb->s;
					pac_:;
					preserve\(int, xtd, xtd = 2;\)1??0?
1??+3m 111q0?
%f+ 				i = is->sug_pt >= 0 \? is->sug_pt : led_lastword\(sb->s \+ pre\) \+ pre;
				if \(suggestsb && search\(sb->s \+ i, sb->s_n - i\)\) \{
					is->sug = suggestsb->s;
					pac_:;
					preserve\(int, xtd, xtd = 2;\)2??0?
2??m 11220reg p OK led.c:560:a22sc %? %@2152sc!1q0?
%f+ 				i = is->sug_pt >= 0 \? is->sug_pt : led_lastword\(sb->s \+ pre\) \+ pre;
				if \(suggestsb && search\(sb->s \+ i, sb->s_n - i\)\) \{3??0?
3??m 11220reg p OK led.c:560:a32sc %? %@2152sc!1q0?
%f+ 				int r = crow-ctop\+1;
				if \(is->sug\)
					goto pac_;4??0?
4??+3m 11220reg p OK led.c:560:a42sc %? %@2152sc!1q0?
%f+ 					is->sug = suggestsb->s;
					pac_:;
					preserve\(int, xtd, xtd = 2;\)5??0?
5??-2m 11220reg p OK led.c:560:a52sc %? %@2152sc!1q0?
%f+ .	...n. ... c...........
		.	.f ....>....
	...	..t....c..
..	...=....>...... .=.. ..i..>...... ...e....s.......b.>....p....\+ pr..
...... .....est.b... ....c..sb... ........>..n ..... \{
.	.	..............ge...b.>..
.	.		.....;
.....pr........n.....d. .t..=.2;.6??0?
6??+3m 11220reg p OK led.c:560:a62sc %? %@2152sc!1q0?
grp 1%f+ 				int r = crow-ctop\+1;.*?
				if \(is->sug\).*?
					goto pac_;.*?
(				i = is->sug_pt >= 0 \? is->sug_pt : led_lastword\(sb->s \+ pre\) \+ pre;)7??0?
grp 07??m 11220reg p OK led.c:560:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 			if \(ai_max >= 0\) \{
				pac:;
				sbuf_nul\(sb\).*(					preserve\(int, ftidx,\))
					syn_setft\(ac_ft\);
					for \(int left = 0; r < xrows; r\+\+\) \{8??0?
grp 08??-5m 11220reg p OK led.c:560:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 			}
			continue;
		case TK_CTL\('\''b'\''\):.*(						RS\(2, led_crender\(is->sug, r, 0, left, left\+xcols\)\))
						left \+= xcols;
						if \(left >= rstates\[2]\.pos\[rstates\[2]\.n]\)9??0?
grp 09??-8m 11220reg p OK led.c:560:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg led.c:5602sc %? %@2132sc!0?
'\''1c static int search(sbuf *sb, int l, int pre)
??!219reg led.c:12:m12sc %? %@2142sc!0?
'\''2c 	if (!sb->s[l])
??!219reg led.c:14:m22sc %? %@2142sc!0?
'\''3c 	again:;
	char *part = strstr(acsb->s, sb->s+l);
??!219reg led.c:18:m32sc %? %@2142sc!0?
'\''4s/ l/ sb->s_n - l/??!219reg led.c:24:m42sc %? %@2142sc!0?
'\''5s/se/se if (l >= pre)/??!219reg led.c:27:m52sc %? %@2142sc!0?
'\''6c 		part = strstr(part+len, sb->s+l);
	}
	if (l < pre && sb->s[pre]) {
		l = pre;
		goto again;
??!219reg led.c:30:m62sc %? %@2142sc!0?
'\''7i 	if (ai_max >= 0 && xpac) {
		c = 0;
		goto pac;
	}
??!219reg led.c:430:m72sc %? %@2142sc!0?
'\''8s/ \+ pre\) \+ pre/)/??!219reg led.c:529:m82sc %? %@2142sc!0?
'\''9,#+1c 				for (i = 0; is->sug[i] && sb->s[i+is->lsug] == is->sug[i]; i++){}
				sbuf_cut(sb, MAX(is->lsug+i, pre))
				sbuf_str(sb, is->sug+i)
??!219reg led.c:540:m92sc %? %@2142sc!0?
?'\''10s/->s \+ is->lsug, len - is->lsug/, is->lsug, pre/1??1??1q'\''10s/->s \+(.*)len - is->lsug/,\1pre/2??2??'\''10220reg p OK led.c:546:s22sc %? %@2162sc!0?
1;2??!219reg led.c:546:m102sc %? %@2142sc!0?
'\''11,#+1c 				is->lsug = is->sug_pt >= 0 ? is->sug_pt : led_lastword(sb->s);
				if (suggestsb && search(sb, is->lsug, pre)) {
??!219reg led.c:560:m112sc %? %@2142sc!vis 2b0w2q' > "$P2VIF"
EXINIT='%ya 97:? %@97' $VI -e 'led.c' "$P2VIF"

if [ $# -gt 0 ]; then
    export P2VI_PATCH="$P2VI_PATCH ${0##*/}"
    next=$1
    shift
    case $next in /*|./*|../*) "$next" "$@" ;; *) "./$next" "$@" ;; esac
fi

exit 0
=== PATCH2VI PATCH ===
diff --git a/led.c b/led.c
index a38f7a06..7f227f0e 100644
--- a/led.c
+++ b/led.c
@@ -9,25 +9,30 @@ int dstrlen(const char *s, char delim)
 	return i-s;
 }
 
-static int search(const char *pattern, int l)
+static int search(sbuf *sb, int l, int pre)
 {
-	if (!*pattern)
+	if (!sb->s[l])
 		return 0;
 	sbuf_cut(suggestsb, 0)
 	sbuf_smake(sylsb, 1024)
-	char *part = strstr(acsb->s, pattern);
+	again:;
+	char *part = strstr(acsb->s, sb->s+l);
 	while (part) {
 		char *part1 = part;
 		while (*part != '\n')
 			part--;
 		int len = dstrlen(++part, '\n');
-		if (len++ != l) {
+		if (len++ != sb->s_n - l) {
 			if (part == part1)
 				sbuf_mem(suggestsb, part, len)
-			else
+			else if (l >= pre)
 				sbuf_mem(sylsb, part, len)
 		}
-		part = strstr(part+len, pattern);
+		part = strstr(part+len, sb->s+l);
+	}
+	if (l < pre && sb->s[pre]) {
+		l = pre;
+		goto again;
 	}
 	sbuf_mem(suggestsb, sylsb->s, sylsb->s_n)
 	free(sylsb->s);
@@ -428,6 +433,10 @@ static int led_line(sbuf *sb, int ps, int pre, char **post, int postn, char **po
 	char *cs;
 	int len, c, i;
 	sbuf *reg;
+	if (ai_max >= 0 && xpac) {
+		c = 0;
+		goto pac;
+	}
 	do {
 		led_printparts(sb, pre, ps, *post, postn, poff);
 		len = sb->s_n;
@@ -526,7 +535,7 @@ static int led_line(sbuf *sb, int ps, int pre, char **post, int postn, char **po
 		case TK_CTL('n'):
 			if (!suggestsb)
 				continue;
-			is->lsug = is->sug_pt >= 0 ? is->sug_pt : led_lastword(sb->s + pre) + pre;
+			is->lsug = is->sug_pt >= 0 ? is->sug_pt : led_lastword(sb->s);
 			if (is->_sug) {
 				if (suggestsb->s_n == is->sug - suggestsb->s)
 					continue;
@@ -537,13 +546,14 @@ static int led_line(sbuf *sb, int ps, int pre, char **post, int postn, char **po
 				}
 				suggest:
 				*is->_sug = '\0';
-				sbuf_cut(sb, is->lsug)
-				sbuf_str(sb, is->sug)
+				for (i = 0; is->sug[i] && sb->s[i+is->lsug] == is->sug[i]; i++){}
+				sbuf_cut(sb, MAX(is->lsug+i, pre))
+				sbuf_str(sb, is->sug+i)
 				is->sug = is->_sug+1;
 				continue;
 			}
 			lookup:
-			if (search(sb->s + is->lsug, len - is->lsug)) {
+			if (search(sb, is->lsug, pre)) {
 				is->sug = suggestsb->s;
 				if (!(is->_sug = strchr(is->sug, '\n')))
 					continue;
@@ -557,8 +567,8 @@ static int led_line(sbuf *sb, int ps, int pre, char **post, int postn, char **po
 				int r = crow-ctop+1;
 				if (is->sug)
 					goto pac_;
-				i = is->sug_pt >= 0 ? is->sug_pt : led_lastword(sb->s + pre) + pre;
-				if (suggestsb && search(sb->s + i, sb->s_n - i)) {
+				is->lsug = is->sug_pt >= 0 ? is->sug_pt : led_lastword(sb->s);
+				if (suggestsb && search(sb, is->lsug, pre)) {
 					is->sug = suggestsb->s;
 					pac_:;
 					preserve(int, xtd, xtd = 2;)
