#!/bin/sh -e
# Generated by patch2vi from unified diff
# Available separators: 0003-0010 0013-0014 0016-0037 0112 0120-0121 0126 0132 0176-0377

VI=${VI:-vi}
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi binary" >&2
    exit 1
fi

# Env switches:
# Phase 1 (search/mark) reports nothing by default
#   DBG1=1 reports failures and which fallback anchor
#   resolved a group, QF1=1 also quits on failure
# Phase 2 (edits) reports and quits by default
#   DBG2=1 silences it, QF2=1 keeps going after an error
# INTR=1 enters vi at the failing code line in this
#   script, for state inspection mid execution

# Body too large for EXINIT/argv: stage it in a file
( : > /tmp/p2vi.$$.d ) 2>/dev/null && P2VIF=/tmp/p2vi.$$ || P2VIF=./p2vi.$$
trap 'rm -f "$P2VIF".*' EXIT

printf '%s%s%s\n' '|sc! |:vis 3ic 0217reg prFp FAIL %@219pr? %@212214reg ? %@217? %@211216reg ? %@220221reg vis 2q!1211reg ? %@221'\
"229reg  $P2VI_PATCH \
${DBG1:+213reg ? %@217? %@210215reg ? %@220}\
${DBG2:+ya!214ya!216}\
${QF1:+210reg vis 2q!1}\
${QF2:+ya!221}\
${INTR:+212reg |sc|vis 2:fr 0:e $0:83reg %@47:%f> 219reg %@219:&Q:b0:|sc! |:vis 3q1}"\
'230reg 0fr 2290?
f> [ /]splits[.]sh 20??b620?? %ya 231230reg 1231??0?
f> [ /]incsearch[.]sh 20??b720?? %ya 232230reg 1232??0?
fr 98211reg fr 230f> 1??!? %@221fr 98b01b11b21b31b410?
b5%ya 972sc %? %@972sc!b41211reg ? %@2210?
2sc %? %@2312sc!b21211reg ? %@2210?
2sc %? %@2322sc!vis 2b0wb1wb2wb3wb4w2q' > "$P2VIF".d
printf '%s\n' '2sc!fr 98b0%ya 98?0?
%f> \(\?:'\''\[0-9]\+\)\|\(\[\.%\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\[0-9]\+\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\)\[ \\t]\*\\
\(\?:\(\[,;]#\?\)\[ \\t]\*\(\(\?:\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\(\?:\(\?:<\(\?:\[\^<\\\\\\\\]\|\\\\\\\\\.\?\)\*<\?\|>\(\?:\[\^>\\\\\\\\]\|\\\\\\\\\.\?\)\*>\?\)\|\\
\(\?:'\''\[0-9]\+\)\|\(\[\.\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\(\[0-9]\+\)\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\)\*\[ \\t]\*\)\*\)\\
\(\(pac\|pr\|ai\|ish\|err\|fr\|ic\|grp\|mpt\|rr\|shape\|seq\|ts\|td\|order\|hl\[lwpr]\?\|left\|lim\|led\|vis\)\\
\|\[@&!dmj]\|=\\\\\?\{0,1}\|\\\\\?\{1,2}\[\?!]\?\|b\[psx]\?\|p\[uh]\?\|ac\|e\[f!]\?!\?\|f\[-\+><tdp]\?\|inc\|i\|sc!\?\|\\
\(\?:g!\?\|s\)\[ \\t]\?\(\.\)\?\|q!\?\|reg\?\\\\\+\?\|rd\?\|w\(\?:q!\|\[q!]\)\?\|u\[czbd]\|x!\?\|ya\[!\+]\?\|cm!\?\|cd\?\)\?",
		A\(BL1 \| SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1\)},1??0?
1??+3m 11q0?
%f> \(\(pac\|pr\|ai\|ish\|err\|fr\|ic\|grp\|mpt\|rr\|shape\|seq\|ts\|td\|order\|hl\[lwpr]\?\|left\|lim\|led\|vis\)\\
\|\[@&!dmj]\|=\\\\\?\{0,1}\|\\\\\?\{1,2}\[\?!]\?\|b\[psx]\?\|p\[uh]\?\|ac\|e\[f!]\?!\?\|f\[-\+><tdp]\?\|inc\|i\|sc!\?\|\\
\(\?:g!\?\|s\)\[ \\t]\?\(\.\)\?\|q!\?\|reg\?\\\\\+\?\|rd\?\|w\(\?:q!\|\[q!]\)\?\|u\[czbd]\|x!\?\|ya\[!\+]\?\|cm!\?\|cd\?\)\?",
		A\(BL1 \| SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1\)},2??0?
2??m 1220reg p OK conf.c:300:a22sc %? %@2152sc!1q0?
;0fr.,$f> ^\(\(pac\|pr\|ai\|ish\|err\|fr\|ic\|grp\|mpt\|rr\|shape\|seq\|ts\|td\|order\|hl\[lwpr]\?\|left\|lim\|led\|vis\)\\$3??0?
3??m 1220reg p OK conf.c:300:a32sc %? %@2152sc!fr 981qfr 980?
%f> \(\?:'\''\[0-9]\+\)\|\(\[\.%\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\[0-9]\+\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\)\[ \\t]\*\\
\(\?:\(\[,;]#\?\)\[ \\t]\*\(\(\?:\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\(\?:\(\?:<\(\?:\[\^<\\\\\\\\]\|\\\\\\\\\.\?\)\*<\?\|>\(\?:\[\^>\\\\\\\\]\|\\\\\\\\\.\?\)\*>\?\)\|\\
\(\?:'\''\[0-9]\+\)\|\(\[\.\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\(\[0-9]\+\)\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\)\*\[ \\t]\*\)\*\)\\4??0?
4??+3m 1220reg p OK conf.c:300:a42sc %? %@2152sc!1q0?
%f> \|\[@&!dmj]\|=\\\\\?\{0,1}\|\\\\\?\{1,2}\[\?!]\?\|b\[psx]\?\|p\[uh]\?\|ac\|e\[f!]\?!\?\|f\[-\+><tdp]\?\|inc\|i\|sc!\?\|\\
\(\?:g!\?\|s\)\[ \\t]\?\(\.\)\?\|q!\?\|reg\?\\\\\+\?\|rd\?\|w\(\?:q!\|\[q!]\)\?\|u\[czbd]\|x!\?\|ya\[!\+]\?\|cm!\?\|cd\?\)\?",
		A\(BL1 \| SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1\)},5??0?
5??-1m 1220reg p OK conf.c:300:a52sc %? %@2152sc!1q0?
%f> .....0.9].....\....\|.0-9..t.\*...\).\?........%... \\.]\*\[0....\[......\*...\[ ...\*..\|......\\..\\].....\..\)\*...\?..\\.]......\\t..\\
....\[,;...\)....].\(......\(\?....\\.....\\.\\\\..\).....\[.\\..\*.......:.\(..\[\^.\\........\\\.......>.\?.....\\........\.\?.\*...\|.
.....0...\+\).\(.\..........t].....\(.......\+...........\[...].\)..\\....\*..:....]...\|...\[...\\.\\.\|.....\?\)..\\..... ........
\(.....p..a........r\|.....\|......t...\|s.....se...s...\|..de..h...w..]..l.f.\|..m......i...
..@..d.j...\\....,1..\\......}.\?.].........\|p.uh.\?....e\[....!\?\|.\[-\+..tdp....n..i..c..\|.
.\?:..\?.... \\.]...\)\?..!.....\?...\?.r..............\)..............y..!..\?.c...........
......1....Y...., ....RE..R...R....H.....1....,......H., RE, .R1, .Y......\)..6??0?
6??+3m 1220reg p OK conf.c:300:a62sc %? %@2152sc!1q0?
grp 1%f> \(\?:'\''\[0-9]\+\)\|\(\[\.%\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\[0-9]\+\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\)\[ \\t]\*\\.*?
\(\?:\(\[,;]#\?\)\[ \\t]\*\(\(\?:\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\(\?:\(\?:<\(\?:\[\^<\\\\\\\\]\|\\\\\\\\\.\?\)\*<\?\|>\(\?:\[\^>\\\\\\\\]\|\\\\\\\\\.\?\)\*>\?\)\|\\.*?
\(\?:'\''\[0-9]\+\)\|\(\[\.\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\(\[0-9]\+\)\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\)\*\[ \\t]\*\)\*\)\\.*?
(\(\(pac\|pr\|ai\|ish\|err\|fr\|ic\|grp\|mpt\|rr\|shape\|seq\|ts\|td\|order\|hl\[lwpr]\?\|left\|lim\|led\|vis\)\\)7??0?
grp 07??m 1220reg p OK conf.c:300:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	\{ac_ft, "\[\^ \\t-/:-@\[-\^\{-~]\+\(\?:\(\\n\$\)\|\\n\)\|\\n\|\(\[\^\\n]\+\(\\n\)\)",
		A\(NA, SYN_BGMK\(RE1\), SYN_BGMK\(AY1\), SYN_BGMK\(AY\)\)},
	\{ac_ft, "\[\^ \\t-/:-@\[-\^\{-~]\+\$\|\(\.\+\$\)", A\(NA, SYN_BGMK\(AY1\)\)},.*(	\{vs_ft, "\.\+", A\(AY1 \| SYN_BD\), 1},)
	\{vs_ft, "\(\^\[\?/]\)\|\(\\\\\\\\\[<>]\|\\\\\(\\\\\?\[:=!<>#]\|\\\\\[\\\\\^\?\(\(\?:\\\\\\\\\.\?\|\[\^\\\\]]\)\*\)]\|\\\\\[\|\[\.\^\$\\\\\(\)\*\+\|\?]\|\\\\\{\(\[0-9]\*\(,\)\?\[0-9]\*\)\?}\?\)\|\\\\\\\\\(\.\)",
		A\(SYN_BD, BL1, WH1, GR1, RE1, WH1, YE\)},8??0?
grp 08??-7m 1220reg p OK conf.c:300:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	\{n_ft, "1\(\[ \\t]\*\[1-9]\[ \\t]\*\)9", A\(RE1, MA1 \| SYN_BD\)},
	\{n_ft, "9\[ \\t]\*\(\[1-9]\[ \\t]\*\)1", A\(RE1, MA1 \| SYN_BD\)},
	\{n_ft, "\[1-9]", A\(RE1\)},.*(	\{vs_ft, "\(\\\\\\\\\)\(\.\)\(\?:\(-\)\(\?:\(\\\\\\\\\(\.\)\)\|\[\^\\\\\\\\\\\\]]\)\)\?\|\[\^\\\\\\\\\[\^]\(-\)\(\?:\(\\\\\\\\\(\.\)\)\|\.\)\|\\)
\[\^\\\\\\\\\[\^]\\\\\^\(-\)\(\?:\(\\\\\\\\\(\.\)\)\|\[\^\\\\\\\\]\)\|\\\\\^\(-\)\[\^\\\\\\\\]",
		A\(GR1 \| SYN_BD \| SYN_ATT, 1, GR1, AY1, YE, WH1, AY1, YE, WH1, AY1, YE, WH1, AY1, YE, WH1\), 2},9??0?
grp 09??-10m 1220reg p OK conf.c:300:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg conf.c:3002sc %? %@2132sc!0?
'\''1s/\|p/|sw|et|idt|p/??!219reg conf.c:300:m12sc %? %@2142sc!b1%ya 98?0?
%f> int xshape = 1;			/\* perform letter shaping \*/
int xorder = 1;			/\* change the order of characters \*/
int xts = 8;			/\* number of spaces for tab \*/
int xish;			/\* interactive shell \*/
int xgrp;			/\* regex search group \*/
int xpac;			/\* print autocomplete options \*/1??0?
1??+2m 11q0?
%f> int xshape = 1;			/\* perform letter shaping \*/
int xorder = 1;			/\* change the order of characters \*/
int xts = 8;			/\* number of spaces for tab \*/4??0?
4??+2m 1220reg p OK ex.c:14:a42sc %? %@2152sc!1q0?
grp 1%f> int xshape = 1;			/\* perform letter shaping \*/.*?
int xorder = 1;			/\* change the order of characters \*/.*?
(int xts = 8;			/\* number of spaces for tab \*/)7??0?
grp 07??m 1220reg p OK ex.c:14:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> int xhlr;			/\* highlight text in reverse direction \*/
int xled = 1;			/\* use the line editor \*/
int xtd = \+1;			/\* current text direction \*/.*(int xmpt;			/\* whether to prompt after printing > 1 lines in vi \*/)
int xpr;			/\* ex_cprint register \*/
int xlim = -1;			/\* rendering cutoff for non cursor lines \*/8??0?
grp 08??-4m 1220reg p OK ex.c:14:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> int xhll;			/\* highlight current line \*/
int xhlw;			/\* highlight current word \*/
int xhlp;			/\* highlight \{}\[]\(\) pair \*/.*(int xseq = 1;			/\* undo/redo sequence \*/)
int xerr = 1;			/\* error handling -
				bit 1: print errors, bit 2: early return, bit 3: ignore errors \*/9??0?
grp 09??-7m 1220reg p OK ex.c:14:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg ex.c:142sc %? %@2132sc!0?
?0?
%f+ 	bufs\[i]\.off = 0;
	bufs\[i]\.top = 0;
	bufs\[i]\.td = \+1;
	bufs\[i]\.mtime = -1;
	return i;
}1??0?
1??+2m 21q0?
%f+ 	bufs\[i]\.off = 0;
	bufs\[i]\.top = 0;
	bufs\[i]\.td = \+1;4??0?
4??+2m 2220reg p OK ex.c:168:a42sc %? %@2152sc!1q0?
grp 1%f+ 	bufs\[i]\.off = 0;.*?
	bufs\[i]\.top = 0;.*?
(	bufs\[i]\.td = \+1;)7??0?
grp 07??m 2220reg p OK ex.c:168:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	bufs\[i]\.lb = lbuf_make\(\);
	bufs\[i]\.plen = len;
	bufs\[i]\.row = 0;.*(void temp_open\(int i, char \*name, char \*ft\))
\{
	tempbufs\[i]\.path = uc_dup\(name\);8??0?
grp 08??-5m 2220reg p OK ex.c:168:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	else
		bufs_free\(--i\);
	bufs\[i]\.path = uc_dup\(path\);.*(	tempbufs\[i]\.lb = lbuf_make\(\);)
	tempbufs\[i]\.row = 0;
	tempbufs\[i]\.off = 0;9??0?
grp 09??-8m 2220reg p OK ex.c:168:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg ex.c:1682sc %? %@2132sc!0?
?0?
%f+ 	tempbufs\[i]\.off = 0;
	tempbufs\[i]\.top = 0;
	tempbufs\[i]\.td = \+1;
	tempbufs\[i]\.mtime = -1;
	tempbufs\[i]\.ft = ft;
}1??0?
1??+2m 31q0?
%f+ 	tempbufs\[i]\.off = 0;
	tempbufs\[i]\.top = 0;
	tempbufs\[i]\.td = \+1;4??0?
4??+2m 3220reg p OK ex.c:180:a42sc %? %@2152sc!1q0?
grp 1%f+ 	tempbufs\[i]\.off = 0;.*?
	tempbufs\[i]\.top = 0;.*?
(	tempbufs\[i]\.td = \+1;)7??0?
grp 07??m 3220reg p OK ex.c:180:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	tempbufs\[i]\.path = uc_dup\(name\);
	tempbufs\[i]\.lb = lbuf_make\(\);
	tempbufs\[i]\.row = 0;.*(void temp_pos\(int i, int row, int off, int top\))
\{
	if \(row < 0\)8??0?
grp 08??-5m 3220reg p OK ex.c:180:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	bufs\[i]\.mtime = -1;
	return i;
}.*(		row = lbuf_len\(tempbufs\[i]\.lb\)-1;)
	tempbufs\[i]\.row = row < 0 \? 0 : row;
	tempbufs\[i]\.off = off;9??0?
grp 09??-8m 3220reg p OK ex.c:180:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg ex.c:1802sc %? %@2132sc!0?
?0?
%f+ 	return 0;
}

static void \*ec_edit\(char \*loc, char \*cmd, char \*arg\)
\{
	char msg\[512];1??0?
1??+2m 41q0?
%f+ 	return 0;
}

4??0?
4??+2m 4220reg p OK ex.c:412:a42sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	}
	bufs_switch\(bufs_open\(path, len\)\);
	readfile\(\).*(	int fd, len, rd = 0, cd = 0;)
	if \(arg\[0] == '\''\.'\'' && arg\[1] == '\''/'\''\)
		cd = 2;8??0?
grp 08??-4m 4220reg p OK ex.c:412:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	if \(path\[0] && \(\(fd = bufs_find\(path, len\)\) >= 0\)\) \{
		bufs_switch\(fd\);
		return 1;.*(	len = strlen\(arg\+cd\);)
	if \(len && \(\(fd = bufs_find\(arg\+cd, len\)\) >= 0\)\) \{
		bufs_switchwft\(fd\)9??0?
grp 09??-7m 4220reg p OK ex.c:412:a92sc %? %@2152sc!'\''00?
1;4;8;9??!219reg ex.c:4122sc %? %@2132sc!0?
?0?
%f+ 	p->mtime = mtime\(p->path\);
	p->ft = syn_filetype\(p->path\);
	lbuf_saved\(p->lb, clear\);
}

static void \*ec_setpath\(char \*loc, char \*cmd, char \*arg\)1??0?
1??+2m 51q0?
%f+ 	p->mtime = mtime\(p->path\);
	p->ft = syn_filetype\(p->path\);
	lbuf_saved\(p->lb, clear\);4??0?
4??+2m 5220reg p OK ex.c:669:a42sc %? %@2152sc!1q0?
grp 1%f+ 	p->mtime = mtime\(p->path\);.*?
	p->ft = syn_filetype\(p->path\);.*?
(	lbuf_saved\(p->lb, clear\);)7??0?
grp 07??m 5220reg p OK ex.c:669:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 		xquit = \*loc \? -xqprop \* 256 - 257 - \(abs\(xquit\) - 1\) : -xquit;
	return NULL;
}.*(	free\(xb_path\);)
	xb_path = uc_dup\(arg\);
	ex_buf->plen = strlen\(arg\);8??0?
grp 08??-5m 5220reg p OK ex.c:669:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	if \(\*arg\)
		xquit = \(abs\(atoi\(arg\)\) & 255\) \+ 1;
	if \(strchr\(cmd, '\''!'\''\)\).*(static void \*ec_read\(char \*loc, char \*cmd, char \*arg\))
\{
	sbuf obuf, \*sb;9??0?
grp 09??-11m 5220reg p OK ex.c:669:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg ex.c:6692sc %? %@2132sc!0?
?0?
%f+ EO\(pac\) EO\(pr\) EO\(ai\) EO\(err\) EO\(fr\) EO\(ish\) EO\(ic\) EO\(mpt\)
EO\(rr\) EO\(shape\) EO\(seq\) EO\(td\) EO\(order\) EO\(hll\) EO\(hlw\)
EO\(hlp\) EO\(hlr\) EO\(hl\) EO\(lim\) EO\(led\) EO\(vis\)

1??0?
1??+2m 61q0?
%f+ EO\(pac\) EO\(pr\) EO\(ai\) EO\(err\) EO\(fr\) EO\(ish\) EO\(ic\) EO\(mpt\)
EO\(rr\) EO\(shape\) EO\(seq\) EO\(td\) EO\(order\) EO\(hll\) EO\(hlw\)
EO\(hlp\) EO\(hlr\) EO\(hl\) EO\(lim\) EO\(led\) EO\(vis\)4??0?
4??+2m 6220reg p OK ex.c:1649:a42sc %? %@2152sc!1q0?
grp 1%f+ EO\(pac\) EO\(pr\) EO\(ai\) EO\(err\) EO\(fr\) EO\(ish\) EO\(ic\) EO\(mpt\).*?
EO\(rr\) EO\(shape\) EO\(seq\) EO\(td\) EO\(order\) EO\(hll\) EO\(hlw\).*?
(EO\(hlp\) EO\(hlr\) EO\(hl\) EO\(lim\) EO\(led\) EO\(vis\))7??0?
grp 07??m 6220reg p OK ex.c:1649:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	return uc_isdigit\(\*arg\) \|\| \(\*arg == '\''-'\'' && uc_isdigit\(arg\[1]\)\) \?
		atoi\(arg\) : \(unsigned char\)\*arg;
}.*(_EO\(left,)
	if \(\*loc\)
		xleft = \(xcols / 2\) \* atoi\(loc\);8??0?
grp 08??-5m 6220reg p OK ex.c:1649:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	}
	return xkwdrs \? NULL : xserr;
}.*(	else if \(\*arg\))
		xleft = atoi\(arg\);
	else if \(lbuf_get\(xb, xrow\)\)9??0?
grp 09??-8m 6220reg p OK ex.c:1649:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg ex.c:16492sc %? %@2132sc!0?
?0?
%f+ 
_EO\(ts, xts = \*arg \? eo_val\(arg\) : !xts; xts = MAX\(0, xts\); return NULL;\)
_EO\(grp, xgrp = \(\*arg \? eo_val\(arg\) : !xgrp\) \* 2; xgrp = MAX\(0, xgrp\); return NULL;\)

1??0?
1??m 71q0?
;0fr.,$f+ ^_EO\(ts, xts = \*arg \? eo_val\(arg\) : !xts; xts = MAX\(0, xts\); return NULL;\)$4??0?
4??-1m 7220reg p OK ex.c:1650:a42sc %? %@2152sc!fr 981qfr 980?
m 01;0grp 1%f> 	return uc_isdigit\(\*arg\) \|\| \(\*arg == '\''-'\'' && uc_isdigit\(arg\[1]\)\) \?
		atoi\(arg\) : \(unsigned char\)\*arg;
}.*(_EO\(left,)
	if \(\*loc\)
		xleft = \(xcols / 2\) \* atoi\(loc\);8??0?
grp 08??-4m 7220reg p OK ex.c:1650:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	}
	return xkwdrs \? NULL : xserr;
}.*(	else if \(\*arg\))
		xleft = atoi\(arg\);
	else if \(lbuf_get\(xb, xrow\)\)9??0?
grp 09??-7m 7220reg p OK ex.c:1650:a92sc %? %@2152sc!'\''00?
1;4;8;9??!219reg ex.c:16502sc %? %@2132sc!0?
?0?
%f+ 	EO\(err\),
	\{"ef!", ec_fuzz},
	\{"ef", ec_fuzz},
	\{"e!", ec_edit},
	\{"e", ec_edit},
	\{"ft", ec_ft},1??0?
1??+2m 81q0?
%f+ 	EO\(err\),
	\{"ef!", ec_fuzz},
	\{"ef", ec_fuzz},4??0?
4??+2m 8220reg p OK ex.c:1695:a42sc %? %@2152sc!1q0?
grp 1%f+ 	EO\(err\),.*?
	\{"ef!", ec_fuzz},.*?
(	\{"ef", ec_fuzz},)7??0?
grp 07??m 8220reg p OK ex.c:1695:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	\{"p", ec_print},
	EO\(ai\),
	\{"ac", ec_setacreg},.*(	\{"fd", ec_setdir},)
	\{"fp", ec_setdir},
	EO\(fr\),8??0?
grp 08??-4m 8220reg p OK ex.c:1695:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	EO\(pr\),
	\{"pu", ec_put},
	\{"ph", ec_setenc},.*(	\{"f\+", ec_find},)
	\{"f-", ec_find},
	\{"f>", ec_find},9??0?
grp 09??-7m 8220reg p OK ex.c:1695:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg ex.c:16952sc %? %@2132sc!0?
?0?
%f+ 	\{"f>", ec_find},
	\{"f<", ec_find},
	\{"f", ec_fuzz},
	EO\(ish\),
	\{"inc", ec_setincl},
	EO\(ic\),1??0?
1??+2m 91q0?
%f+ 	\{"f>", ec_find},
	\{"f<", ec_find},
	\{"f", ec_fuzz},4??0?
4??+2m 9220reg p OK ex.c:1706:a42sc %? %@2152sc!1q0?
grp 1%f+ 	\{"f>", ec_find},.*?
	\{"f<", ec_find},.*?
(	\{"f", ec_fuzz},)7??0?
grp 07??m 9220reg p OK ex.c:1706:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	EO\(fr\),
	\{"f\+", ec_find},
	\{"f-", ec_find},.*(	\{"i", ec_insert},)
	\{"d", ec_delete},
	EO\(grp\),8??0?
grp 08??-4m 9220reg p OK ex.c:1706:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	\{"ft", ec_ft},
	\{"fd", ec_setdir},
	\{"fp", ec_setdir},.*(	\{"g!", ec_glob},)
	\{"g", ec_glob},
	EO\(mpt\),9??0?
grp 09??-7m 9220reg p OK ex.c:1706:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg ex.c:17062sc %? %@2132sc!0?
?0?
%f+ 	EO\(seq\),
	\{"sc!", ec_specials},
	\{"sc", ec_specials},
	\{"s", ec_substitute},
	\{"x!", ec_write},
	\{"x", ec_write},1??0?
1??+2m 101q0?
%f+ 	EO\(seq\),
	\{"sc!", ec_specials},
	\{"sc", ec_specials},4??0?
4??+2m 10220reg p OK ex.c:1736:a42sc %? %@2152sc!1q0?
grp 1%f+ 	EO\(seq\),.*?
	\{"sc!", ec_specials},.*?
(	\{"sc", ec_specials},)7??0?
grp 07??m 10220reg p OK ex.c:1736:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	\{"ub", ec_setenc},
	\{"ud", ec_undoredo},
	EO\(shape\),.*(	\{"ya!", ec_yank},)
	\{"ya\+", ec_yank},
	\{"ya", ec_yank},8??0?
grp 08??-4m 10220reg p OK ex.c:1736:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	\{"w", ec_write},
	\{"uc", ec_setenc},
	\{"uz", ec_setenc},.*(	\{"cm!", ec_cmap},)
	\{"cm", ec_cmap},
	\{"cd", ec_chdir},9??0?
grp 09??-7m 10220reg p OK ex.c:1736:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg ex.c:17362sc %? %@2132sc!0?
'\''1i int xet;			/* expandtab - use spaces for indentation */
int xsw = 8;			/* shiftwidth - indentation step */
int xidt = 500;			/* auto-detect indent on file open */
??!219reg ex.c:14:m12sc %? %@2142sc!0?
'\''2i 	bufs[i].et = 0;
	bufs[i].sw = 8;
	bufs[i].ts = 8;
??!219reg ex.c:168:m22sc %? %@2142sc!0?
'\''3i 	tempbufs[i].et = 0;
	tempbufs[i].sw = 8;
	tempbufs[i].ts = 8;
??!219reg ex.c:180:m32sc %? %@2142sc!0?
'\''4i static void ex_detect_indent(struct buf *p)
{
	int n = lbuf_len(p->lb);
	int max = n < xidt ? n : xidt;
	int tab_lines = 0, space_lines = 0;
	int prev = 0;			/* previous line'\''s leading spaces */
	int delta[129];			/* delta[k] = times indent jumped by k */
	memset(delta, 0, sizeof(delta));
	for (int i = 0; i < max; i++) {
		char *ln = lbuf_get(p->lb, i);
		if (!ln)
			break;
		int tabs = 0, spaces = 0;
		char *s = ln;
		for (; *s == '\'' '\'' || *s == '\''\t'\''; s++)
			*s == '\''\t'\'' ? tabs++ : spaces++;
		if (*s == '\''\n'\'' || *s == '\''\0'\'')	/* blank line: skip, keep prev */
			continue;
		if (tabs && !spaces) {
			tab_lines++;
		} else if (spaces) {
			space_lines++;
			int d = spaces - prev;
			if (d > 0 && d <= 128)
				delta[d]++;
			prev = spaces;
		} else
			prev = 0;		/* dedent to column 0 */
	}
	if (tab_lines > space_lines) {
		p->et = xet = 0;
	} else if (space_lines > 0) {
		int best = 0, bestn = 0;
		for (int d = 1; d <= 128; d++)
			if (delta[d] > bestn) {
				bestn = delta[d];
				best = d;
			}
		if (best) {
			p->et = xet = 1;
			p->sw = xsw = best;
		}
	}
}

??!219reg ex.c:412:m42sc %? %@2142sc!0?
'\''5i 	if (xidt)
		ex_detect_indent(p);
??!219reg ex.c:669:m52sc %? %@2142sc!0?
'\''6i EO(et) EO(idt)
??!219reg ex.c:1649:m62sc %? %@2142sc!0?
'\''7i _EO(sw, if (*arg) xsw = eo_val(arg); return NULL;)
??!219reg ex.c:1650:m72sc %? %@2142sc!0?
'\''8i 	EO(et),
??!219reg ex.c:1695:m82sc %? %@2142sc!0?
'\''9i 	EO(idt),
??!219reg ex.c:1706:m92sc %? %@2142sc!0?
'\''10i 	EO(sw),
??!219reg ex.c:1736:m102sc %? %@2142sc!b2%ya 98?0?
%f> 		case TK_CTL\('\''t'\''\):
			cs = uc_dup\(sb->s \+ ps\);
			sbuf_cut\(sb, ps\)
			sbuf_chr\(sb, '\''\\t'\''\)
			sbuf_str\(sb, cs\)
			free\(cs\);1??0?
1??+3m 11q0?
%f> 			sbuf_chr\(sb, '\''\\t'\''\)
			sbuf_str\(sb, cs\)
			free\(cs\);2??0?
2??m 1220reg p OK led.c:457:a22sc %? %@2152sc!1q0?
;0fr.,$f> ^			sbuf_chr\(sb, '\''\\t'\''\)$3??0?
3??m 1220reg p OK led.c:457:a32sc %? %@2152sc!fr 981qfr 980?
%f> 		case TK_CTL\('\''t'\''\):
			cs = uc_dup\(sb->s \+ ps\);
			sbuf_cut\(sb, ps\)4??0?
4??+3m 1220reg p OK led.c:457:a42sc %? %@2152sc!1q0?
%f> 			sbuf_str\(sb, cs\)
			free\(cs\);5??0?
5??-1m 1220reg p OK led.c:457:a52sc %? %@2152sc!1q0?
%f> 		.....T._C...'\''t'\''\).
	.	.....uc.....sb-.. \+ ....
....b...c.t........
.....uf.c............
	.........r.s.....\)
...f........6??0?
6??+3m 1220reg p OK led.c:457:a62sc %? %@2152sc!1q0?
grp 1%f> 		case TK_CTL\('\''t'\''\):.*?
			cs = uc_dup\(sb->s \+ ps\);.*?
			sbuf_cut\(sb, ps\).*?
(			sbuf_chr\(sb, '\''\\t'\''\))7??0?
grp 07??m 1220reg p OK led.c:457:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 			else if \(ai_max >= 0\)
				return c;
			break;.*(				if \(is->p_reg < '\''/'\'' \|\| is->p_reg >= '\''9'\''\))
					is->p_reg = '\''/'\'';
				while \(is->p_reg < '\''9'\'' && !ex_regget\(\+\+is->p_reg\)\);8??0?
grp 08??-15m 1220reg p OK led.c:457:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 		case TK_CTL\('\''w'\''\):
			if \(len - pre > 0\)
				sbuf_cut\(sb, led_lastword\(sb->s \+ pre\) \+ pre\).*(			} else \{)
				c = term_read\(0\);
				is->p_reg = c == TK_CTL\('\''\\\\'\''\) \? 0 : c;9??0?
grp 09??-18m 1220reg p OK led.c:457:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg led.c:4572sc %? %@2132sc!0?
?0?
%f+ 			sbuf_str\(sb, cs\)
			free\(cs\);
			pre\+\+;
			break;
		case TK_CTL\('\''d'\''\):1??0?
1??+2m 21q0?
%f+ 			pre\+\+;
			break;
		case TK_CTL\('\''d'\''\):2??0?
2??m 2220reg p OK led.c:460:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^			pre\+\+;$3??0?
3??m 2220reg p OK led.c:460:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 			sbuf_str\(sb, cs\)
			free\(cs\);4??0?
4??+2m 2220reg p OK led.c:460:a42sc %? %@2152sc!1q0?
%f+ 			break;
		case TK_CTL\('\''d'\''\):5??0?
5??-1m 2220reg p OK led.c:460:a52sc %? %@2152sc!1q0?
%f+ 	..s..._s..\(s......
..	....\(c...
.	.....\+.
.	...e...
	....e.T...TL.....:6??0?
6??+2m 2220reg p OK led.c:460:a62sc %? %@2152sc!1q0?
grp 1%f+ 			sbuf_str\(sb, cs\).*?
			free\(cs\);.*?
(			pre\+\+;)7??0?
grp 07??m 2220reg p OK led.c:460:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 			else if \(ai_max >= 0\)
				return c;
			break;.*(				if \(is->p_reg < '\''/'\'' \|\| is->p_reg >= '\''9'\''\))
					is->p_reg = '\''/'\'';
				while \(is->p_reg < '\''9'\'' && !ex_regget\(\+\+is->p_reg\)\);8??0?
grp 08??-12m 2220reg p OK led.c:460:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 		case TK_CTL\('\''w'\''\):
			if \(len - pre > 0\)
				sbuf_cut\(sb, led_lastword\(sb->s \+ pre\) \+ pre\).*(			} else \{)
				c = term_read\(0\);
				is->p_reg = c == TK_CTL\('\''\\\\'\''\) \? 0 : c;9??0?
grp 09??-15m 2220reg p OK led.c:460:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg led.c:4602sc %? %@2132sc!0?
?0?
%f+ 			break;
		case TK_CTL\('\''d'\''\):
			if \(sb->s\[ps] == '\'' '\'' \|\| sb->s\[ps] == '\''\\t'\''\) \{
				memmove\(&sb->s\[ps], &sb->s\[ps\+1], len - ps - 1\);
				sb->s_n--;
				pre--;1??0?
1??+2m 31q0?
%f+ 			if \(sb->s\[ps] == '\'' '\'' \|\| sb->s\[ps] == '\''\\t'\''\) \{
				memmove\(&sb->s\[ps], &sb->s\[ps\+1], len - ps - 1\);
				sb->s_n--;
				pre--;2??0?
2??m 3220reg p OK led.c:463:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^			if \(sb->s\[ps] == '\'' '\'' \|\| sb->s\[ps] == '\''\\t'\''\) \{$3??0?
3??m 3220reg p OK led.c:463:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 			break;
		case TK_CTL\('\''d'\''\):4??0?
4??+2m 3220reg p OK led.c:463:a42sc %? %@2152sc!1q0?
%f+ 				memmove\(&sb->s\[ps], &sb->s\[ps\+1], len - ps - 1\);
				sb->s_n--;
				pre--;5??0?
5??-1m 3220reg p OK led.c:463:a52sc %? %@2152sc!1q0?
%f+ ..	.r....
.	c.........L\(.d'\''.:
............\[....=. ..'\''..\|..b.>s.....=....t...\{
..		.....ve\(.......p.]. ....>..p.\+.]..le.........1.;
...	.b-.s.....
.	......-.6??0?
6??+2m 3220reg p OK led.c:463:a62sc %? %@2152sc!1q0?
grp 1%f+ 			break;.*?
		case TK_CTL\('\''d'\''\):.*?
(			if \(sb->s\[ps] == '\'' '\'' \|\| sb->s\[ps] == '\''\\t'\''\) \{)7??0?
grp 07??m 3220reg p OK led.c:463:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 			else if \(ai_max >= 0\)
				return c;
			break;.*(				if \(is->p_reg < '\''/'\'' \|\| is->p_reg >= '\''9'\''\))
					is->p_reg = '\''/'\'';
				while \(is->p_reg < '\''9'\'' && !ex_regget\(\+\+is->p_reg\)\);8??0?
grp 08??-9m 3220reg p OK led.c:463:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 		case TK_CTL\('\''w'\''\):
			if \(len - pre > 0\)
				sbuf_cut\(sb, led_lastword\(sb->s \+ pre\) \+ pre\).*(			} else \{)
				c = term_read\(0\);
				is->p_reg = c == TK_CTL\('\''\\\\'\''\) \? 0 : c;9??0?
grp 09??-12m 3220reg p OK led.c:463:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg led.c:4632sc %? %@2132sc!0?
?0?
%f+ 				pre--;
			}
			break;
		case TK_CTL\('\'']'\''\):
		case TK_CTL\('\''\\\\'\''\):
			if \(c == TK_CTL\('\'']'\''\)\) \{1??0?
1??+2m 41q0?
%f+ 				pre--;
			}
			break;4??0?
4??+2m 4220reg p OK led.c:468:a42sc %? %@2152sc!1q0?
grp 1%f+ 				pre--;.*?
			}.*?
(			break;)7??0?
grp 07??m 4220reg p OK led.c:468:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 			else if \(ai_max >= 0\)
				return c;
			break;.*(				if \(is->p_reg < '\''/'\'' \|\| is->p_reg >= '\''9'\''\))
					is->p_reg = '\''/'\'';
				while \(is->p_reg < '\''9'\'' && !ex_regget\(\+\+is->p_reg\)\);8??0?
grp 08??-4m 4220reg p OK led.c:468:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 		case TK_CTL\('\''w'\''\):
			if \(len - pre > 0\)
				sbuf_cut\(sb, led_lastword\(sb->s \+ pre\) \+ pre\).*(			} else \{)
				c = term_read\(0\);
				is->p_reg = c == TK_CTL\('\''\\\\'\''\) \? 0 : c;9??0?
grp 09??-7m 4220reg p OK led.c:468:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg led.c:4682sc %? %@2132sc!0?
'\''1c 			if (xet)
				for (int _k = 0; _k < xsw; _k++)
					sbuf_chr(sb, '\'' '\'')
			else
				sbuf_chr(sb, '\''\t'\'')
??!219reg led.c:457:m12sc %? %@2142sc!0?
'\''2s/\+\+/ += xet ? xsw : 1/??!219reg led.c:460:m22sc %? %@2142sc!0?
'\''3c 			if (xet) {
				int _k;
				for (_k = 0; _k < xsw && sb->s[ps + _k] == '\'' '\''; _k++);
				if (_k) {
					memmove(&sb->s[ps], &sb->s[ps + _k], len - ps - _k);
					sb->s_n -= _k;
					pre -= _k;
				}
			} else if (sb->s[ps] == '\'' '\'' || sb->s[ps] == '\''\t'\'') {
??!219reg led.c:463:m32sc %? %@2142sc!0?
'\''4i 		case '\''\t'\'':
			if (xet)
				for (int _l = 0; _l < xsw; _l++)
					sbuf_chr(sb, '\'' '\'')
			else
				sbuf_chr(sb, '\''\t'\'')
			break;
??!219reg led.c:468:m42sc %? %@2142sc!b3%ya 98?0?
%f> 			if \(dir < 0\) \{
				if \(\*ln != '\'' '\'' && \*ln != '\''\\t'\''\)
					break;
				ln\+\+;
			} else if \(\*ln != '\''\\n'\'' \|\| r1 == r2\)
				sbuf_chr\(sb, '\''\\t'\''\)
		}
		sbufn_str\(sb, ln\)
		lbuf_edit\(xb, sb->s, i, i \+ 1, 0, 0\);1??0?
1??+3m 11q0?
%f> 				ln\+\+;
			} else if \(\*ln != '\''\\n'\'' \|\| r1 == r2\)
				sbuf_chr\(sb, '\''\\t'\''\)
		}
		sbufn_str\(sb, ln\)
		lbuf_edit\(xb, sb->s, i, i \+ 1, 0, 0\);2??0?
2??m 1220reg p OK vi.c:937:a22sc %? %@2152sc!1q0?
%f> 				ln\+\+;
			} else if \(\*ln != '\''\\n'\'' \|\| r1 == r2\)
				sbuf_chr\(sb, '\''\\t'\''\)3??0?
3??m 1220reg p OK vi.c:937:a32sc %? %@2152sc!1q0?
%f> 			if \(dir < 0\) \{
				if \(\*ln != '\'' '\'' && \*ln != '\''\\t'\''\)
					break;4??0?
4??+3m 1220reg p OK vi.c:937:a42sc %? %@2152sc!1q0?
%f> 		}
		sbufn_str\(sb, ln\)
		lbuf_edit\(xb, sb->s, i, i \+ 1, 0, 0\);5??0?
5??-3m 1220reg p OK vi.c:937:a52sc %? %@2152sc!1q0?
%f> ..	i. ..i... .\)..
..	... \(... !......&. .l. ........
.	........;
.	.	l....
.	........i. .....!. ..n..............
....s.u._.h.\(......t..
.	.
.........tr.......\)
.	.b...e.i..x.....-.s,.i,.i.. ....,..\).6??0?
6??+3m 1220reg p OK vi.c:937:a62sc %? %@2152sc!1q0?
grp 1%f> 			if \(dir < 0\) \{.*?
				if \(\*ln != '\'' '\'' && \*ln != '\''\\t'\''\).*?
					break;.*?
(				ln\+\+;)7??0?
grp 07??m 1220reg p OK vi.c:937:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 		if \(!\(ln = lbuf_get\(xb, i\)\)\)
			continue;
		for \(c = 0; c < count; c\+\+\) \{.*(		sbuf_cut\(sb, 0\))
	}
	xoff = lbuf_indents\(xb, r1\);8??0?
grp 08??-6m 1220reg p OK vi.c:937:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	char \*ln;
	int i, c;
	for \(i = r1; i <= r2; i\+\+\) \{.*(static int vc_motion\(int cmd\))
\{
	int r1 = xrow, r2 = xrow;	/\* region rows \*/9??0?
grp 09??-12m 1220reg p OK vi.c:937:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg vi.c:9372sc %? %@2132sc!0?
'\''1,#+2c 				if (xet && *ln == '\'' '\'') {
					int k;
					for (k = 0; k < xsw && *ln == '\'' '\''; k++)
						ln++;
				} else
					ln++;
			} else if (*ln != '\''\n'\'' || r1 == r2) {
				if (xet) {
					for (int k = 0; k < xsw; k++)
						sbuf_chr(sb, '\'' '\'')
				} else
					sbuf_chr(sb, '\''\t'\'')
			}
??!219reg vi.c:937:m12sc %? %@2142sc!b4%ya 98?0?
%f> 	int plen, row, off, top;
	long mtime;			/\* modification time \*/
	signed char td;			/\* text direction \*/
};
/\* ex options \*/
extern int xleft;1??0?
1??+2m 11q0?
%f> 	int plen, row, off, top;
	long mtime;			/\* modification time \*/
	signed char td;			/\* text direction \*/4??0?
4??+2m 1220reg p OK vi.h:409:a42sc %? %@2152sc!1q0?
grp 1%f> 	int plen, row, off, top;.*?
	long mtime;			/\* modification time \*/.*?
(	signed char td;			/\* text direction \*/)7??0?
grp 07??m 1220reg p OK vi.h:409:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	char \*ft;			/\* file type \*/
	char \*path;			/\* file path \*/
	struct lbuf \*lb;.*(extern int xvis;)
extern int xai;
extern int xic;8??0?
grp 08??-4m 1220reg p OK vi.h:409:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> char \*led_read\(int \*kmap, int c\);
int led_pos\(char \*s, int pos\);
void led_done\(void\);.*(extern int xhl;)
extern int xhll;
extern int xhlw;9??0?
grp 09??-7m 1220reg p OK vi.h:409:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg vi.h:4092sc %? %@2132sc!0?
?0?
%f+ extern int xshape;
extern int xorder;
extern int xts;
extern int xish;
extern int xgrp;
extern int xpac;1??0?
1??+2m 21q0?
%f+ extern int xshape;
extern int xorder;
extern int xts;4??0?
4??+2m 2220reg p OK vi.h:425:a42sc %? %@2152sc!1q0?
grp 1%f+ extern int xshape;.*?
extern int xorder;.*?
(extern int xts;)7??0?
grp 07??m 2220reg p OK vi.h:425:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> extern int xhlr;
extern int xled;
extern int xtd;.*(extern int xmpt;)
extern int xpr;
extern int xlim;8??0?
grp 08??-4m 2220reg p OK vi.h:425:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> extern int xhll;
extern int xhlw;
extern int xhlp;.*(extern int xseq;)
extern int xerr;
extern int xfr;9??0?
grp 09??-7m 2220reg p OK vi.h:425:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg vi.h:4252sc %? %@2132sc!0?
?0?
%f+ 	xoff = buf->off; \\
	xtop = buf->top; \\
	xtd = buf->td; \\

#define exbuf_save\(buf\) \\
	buf->row = xrow; \\1??0?
1??+2m 31q0?
%f+ 	xoff = buf->off; \\
	xtop = buf->top; \\
	xtd = buf->td; \\4??0?
4??+2m 3220reg p OK vi.h:466:a42sc %? %@2152sc!1q0?
grp 1%f+ 	xoff = buf->off; \\.*?
	xtop = buf->top; \\.*?
(	xtd = buf->td; \\)7??0?
grp 07??m 3220reg p OK vi.h:466:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> #define xb ex_buf->lb
#define exbuf_load\(buf\) \\
	xrow = buf->row; \\.*(void bufs_switch\(int idx\);)
void temp_open\(int i, char \*name, char \*ft\);
void temp_switch\(int i, int swap\);8??0?
grp 08??-11m 3220reg p OK vi.h:466:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> #define istempbuf\(buf\) \(buf >= tempbufs && buf < tempbufs \+ LEN\(tempbufs\)\)
#define xb_path ex_buf->path
#define xb_ft ex_buf->ft.*(void temp_write\(int i, char \*str\);)
void temp_pos\(int i, int row, int off, int top\);
void ex\(void\);9??0?
grp 09??-14m 3220reg p OK vi.h:466:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg vi.h:4662sc %? %@2132sc!0?
?0?
%f+ 	buf->off = xoff; \\
	buf->top = xtop; \\
	buf->td = xtd; \\

#define bufs_switchwft\(idx\) \\
\{ if \(&bufs\[idx] != ex_buf\) \{ bufs_switch\(idx\); syn_setft\(xb_ft\); } } \\1??0?
1??+2m 41q0?
%f+ 	buf->off = xoff; \\
	buf->top = xtop; \\
	buf->td = xtd; \\4??0?
4??+2m 4220reg p OK vi.h:472:a42sc %? %@2152sc!1q0?
grp 1%f+ 	buf->off = xoff; \\.*?
	buf->top = xtop; \\.*?
(	buf->td = xtd; \\)7??0?
grp 07??m 4220reg p OK vi.h:472:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> #define xb ex_buf->lb
#define exbuf_load\(buf\) \\
	xrow = buf->row; \\.*(void bufs_switch\(int idx\);)
void temp_open\(int i, char \*name, char \*ft\);
void temp_switch\(int i, int swap\);8??0?
grp 08??-5m 4220reg p OK vi.h:472:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> #define istempbuf\(buf\) \(buf >= tempbufs && buf < tempbufs \+ LEN\(tempbufs\)\)
#define xb_path ex_buf->path
#define xb_ft ex_buf->ft.*(void temp_write\(int i, char \*str\);)
void temp_pos\(int i, int row, int off, int top\);
void ex\(void\);9??0?
grp 09??-8m 4220reg p OK vi.h:472:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg vi.h:4722sc %? %@2132sc!0?
'\''1i 	int et;				/* expandtab - use spaces for indentation */
	int sw;				/* shiftwidth - indentation step */
	int ts;				/* tabspace - number of spaces for tab */
??!219reg vi.h:409:m12sc %? %@2142sc!0?
'\''2i extern int xet;
extern int xsw;
extern int xidt;
??!219reg vi.h:425:m22sc %? %@2142sc!0?
'\''3i 	xet = buf->et; \
	xsw = buf->sw; \
	xts = buf->ts; \
??!219reg vi.h:466:m32sc %? %@2142sc!0?
'\''4i 	buf->et = xet; \
	buf->sw = xsw; \
	buf->ts = xts; \
??!219reg vi.h:472:m42sc %? %@2142sc!' > "$P2VIF".0
# Compat 231 src=splits.sh
printf '%s\n' '2sc!fr 98b4%ya 98?0?
%f> 	xtop = b->top; \\
	xtd = b->td; \\
	curwin->buf = b; \\
	xet = buf->et; \\
	xsw = buf->sw; \\
	xts = buf->ts; \\

#define exbuf_save\(buf\) \\
	buf->row = xrow; \\1??0?
1??+3m 11q0?
%f> 	xet = buf->et; \\
	xsw = buf->sw; \\
	xts = buf->ts; \\

#define exbuf_save\(buf\) \\
	buf->row = xrow; \\2??0?
2??m 1220reg p OK vi.h:498:a22sc %? %@2152sc!1q0?
%f> 	xet = buf->et; \\
	xsw = buf->sw; \\
	xts = buf->ts; \\3??0?
3??m 1220reg p OK vi.h:498:a32sc %? %@2152sc!1q0?
%f> 	xtop = b->top; \\
	xtd = b->td; \\
	curwin->buf = b; \\4??0?
4??+3m 1220reg p OK vi.h:498:a42sc %? %@2152sc!1q0?
%f> 
#define exbuf_save\(buf\) \\
	buf->row = xrow; \\5??0?
5??-3m 1220reg p OK vi.h:498:a52sc %? %@2152sc!0?
1;2;3;4;5??!219reg vi.h:4982sc %? %@2132sc!0?
'\''1,#+2c 	xet = b->et; \
	xsw = b->sw; \
	xts = b->ts; \
??!219reg vi.h:498:m12sc %? %@2142sc!p compat 231 applied: src=splits.sh' > "$P2VIF".231
# Compat 232 src=incsearch.sh
printf '%s\n' '2sc!fr 98b2%ya 98?0?
%f> 				pre--;
			}
			break;
		case '\''\\t'\'':
			if \(xet\)
				for \(int _l = 0; _l < xsw; _l\+\+\)
					sbuf_chr\(sb, '\'' '\''\)
			else
				sbuf_chr\(sb, '\''\\t'\''\)
			break;
		case TK_CTL\('\'']'\''\):
		case TK_CTL\('\''\\\\'\''\):
			if \(c == TK_CTL\('\'']'\''\)\) \{1??0?
1??+3m 11q0?
%f> 		case '\''\\t'\'':
			if \(xet\)
				for \(int _l = 0; _l < xsw; _l\+\+\)
					sbuf_chr\(sb, '\'' '\''\)
			else
				sbuf_chr\(sb, '\''\\t'\''\)
			break;
		case TK_CTL\('\'']'\''\):
		case TK_CTL\('\''\\\\'\''\):
			if \(c == TK_CTL\('\'']'\''\)\) \{2??0?
2??m 1220reg p OK led.c:486:a22sc %? %@2152sc!1q0?
%f> 		case '\''\\t'\'':
			if \(xet\)
				for \(int _l = 0; _l < xsw; _l\+\+\)
					sbuf_chr\(sb, '\'' '\''\)
			else
				sbuf_chr\(sb, '\''\\t'\''\)
			break;3??0?
3??m 1220reg p OK led.c:486:a32sc %? %@2152sc!1q0?
%f> 				pre--;
			}
			break;4??0?
4??+3m 1220reg p OK led.c:486:a42sc %? %@2152sc!1q0?
%f> 		case TK_CTL\('\'']'\''\):
		case TK_CTL\('\''\\\\'\''\):
			if \(c == TK_CTL\('\'']'\''\)\) \{5??0?
5??-7m 1220reg p OK led.c:486:a52sc %? %@2152sc!0?
1;2;3;4;5??!219reg led.c:4862sc %? %@2132sc!0?
?0?
%f+ 			if \(c == '\''\\n'\'' \|\| TK_INT\(c\)\)
				return c;
			insert:
			if \(\(cs = led_read\(kmap, c\)\)\)
				sbuf_str\(sb, cs\)
		}
		is->sug = NULL;1??0?
1??+3m 21q0?
%f+ 			if \(\(cs = led_read\(kmap, c\)\)\)
				sbuf_str\(sb, cs\)
		}
		is->sug = NULL;2??0?
2??m 2220reg p OK led.c:672:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^			if \(\(cs = led_read\(kmap, c\)\)\)$3??0?
3??m 2220reg p OK led.c:672:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 			if \(c == '\''\\n'\'' \|\| TK_INT\(c\)\)
				return c;
			insert:4??0?
4??+3m 2220reg p OK led.c:672:a42sc %? %@2152sc!1q0?
%f+ 				sbuf_str\(sb, cs\)
		}
		is->sug = NULL;5??0?
5??-1m 2220reg p OK led.c:672:a52sc %? %@2152sc!0?
1;2;3;4;5??!219reg led.c:6722sc %? %@2132sc!0?
'\''1,#+6d??!219reg led.c:486:m12sc %? %@2142sc!0?
'\''2c 			if (c == '\''\t'\'' && xet) {
				for (int _l = 0; _l < xsw; _l++)
					sbuf_chr(sb, '\'' '\'')
			} else if ((cs = led_read(kmap, c)))
??!219reg led.c:672:m22sc %? %@2142sc!p compat 232 applied: src=incsearch.sh' > "$P2VIF".232
EXINIT='%ya 97:? %@97' $VI -e 'conf.c' 'ex.c' 'led.c' 'vi.c' 'vi.h' "$P2VIF".0 "$P2VIF".231 "$P2VIF".232 "$P2VIF".d

if [ $# -gt 0 ]; then
    export P2VI_PATCH="$P2VI_PATCH ${0##*/}"
    next=$1
    shift
    case $next in /*|./*|../*) "$next" "$@" ;; *) "./$next" "$@" ;; esac
fi

exit 0
=== PATCH2VI COMPAT 231 src=splits.sh ===
=== COMPAT PATCH ===
--- a/vi.h
+++ b/vi.h
@@ -495,9 +495,9 @@
 	xtop = b->top; \
 	xtd = b->td; \
 	curwin->buf = b; \
-	xet = buf->et; \
-	xsw = buf->sw; \
-	xts = buf->ts; \
+	xet = b->et; \
+	xsw = b->sw; \
+	xts = b->ts; \
 
 #define exbuf_save(buf) \
 	buf->row = xrow; \
=== END ===
=== END COMPAT ===
=== PATCH2VI COMPAT 232 src=incsearch.sh ===
=== COMPAT PATCH ===
--- a/led.c
+++ b/led.c
@@ -483,13 +483,6 @@
 				pre--;
 			}
 			break;
-		case '\t':
-			if (xet)
-				for (int _l = 0; _l < xsw; _l++)
-					sbuf_chr(sb, ' ')
-			else
-				sbuf_chr(sb, '\t')
-			break;
 		case TK_CTL(']'):
 		case TK_CTL('\\'):
 			if (c == TK_CTL(']')) {
@@ -669,7 +662,10 @@
 			if (c == '\n' || TK_INT(c))
 				return c;
 			insert:
-			if ((cs = led_read(kmap, c)))
+			if (c == '\t' && xet) {
+				for (int _l = 0; _l < xsw; _l++)
+					sbuf_chr(sb, ' ')
+			} else if ((cs = led_read(kmap, c)))
 				sbuf_str(sb, cs)
 		}
 		is->sug = NULL;
=== END ===
=== END COMPAT ===
=== PATCH2VI PATCH ===
diff --git a/conf.c b/conf.c
index ad9395c9..3719bcf9 100644
--- a/conf.c
+++ b/conf.c
@@ -297,7 +297,7 @@ return|select|switch|type|var))\\>", A(GR1, BL1 | SYN_BD, YE1)},
 (?:'[0-9]+)|([.%$]|[0-9 \t]*)?))(?:([-*-+/%])[ \t]*[0-9]+[ \t]*)*(?:[ \t]*\\|(?:[^|\\\\]|\\\\.?)*\\|?[ \t]*)*)[ \t]*\
 (?:([,;]#?)[ \t]*((?:\\|(?:[^|\\\\]|\\\\.?)*\\|?[ \t]*)*(?:(?:<(?:[^<\\\\]|\\\\.?)*<?|>(?:[^>\\\\]|\\\\.?)*>?)|\
 (?:'[0-9]+)|([.$]|[0-9 \t]*)?))(?:([-*-+/%])[ \t]*([0-9]+)[ \t]*)*(?:[ \t]*\\|(?:[^|\\\\]|\\\\.?)*\\|?)*[ \t]*)*)\
-((pac|pr|ai|ish|err|fr|ic|grp|mpt|rr|shape|seq|ts|td|order|hl[lwpr]?|left|lim|led|vis)\
+((pac|sw|et|idt|pr|ai|ish|err|fr|ic|grp|mpt|rr|shape|seq|ts|td|order|hl[lwpr]?|left|lim|led|vis)\
 |[@&!dmj]|=\\?{0,1}|\\?{1,2}[?!]?|b[psx]?|p[uh]?|ac|e[f!]?!?|f[-+><tdp]?|inc|i|sc!?|\
 (?:g!?|s)[ \t]?(.)?|q!?|reg?\\+?|rd?|w(?:q!|[q!])?|u[czbd]|x!?|ya[!+]?|cm!?|cd?)?",
 		A(BL1 | SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1)},
diff --git a/ex.c b/ex.c
index f8505153..687da3ef 100644
--- a/ex.c
+++ b/ex.c
@@ -12,6 +12,9 @@ int xtd = +1;			/* current text direction */
 int xshape = 1;			/* perform letter shaping */
 int xorder = 1;			/* change the order of characters */
 int xts = 8;			/* number of spaces for tab */
+int xet;			/* expandtab - use spaces for indentation */
+int xsw = 8;			/* shiftwidth - indentation step */
+int xidt = 500;			/* auto-detect indent on file open */
 int xish;			/* interactive shell */
 int xgrp;			/* regex search group */
 int xpac;			/* print autocomplete options */
@@ -166,6 +169,9 @@ static int bufs_open(const char *path, int len)
 	bufs[i].off = 0;
 	bufs[i].top = 0;
 	bufs[i].td = +1;
+	bufs[i].et = 0;
+	bufs[i].sw = 8;
+	bufs[i].ts = 8;
 	bufs[i].mtime = -1;
 	return i;
 }
@@ -178,6 +184,9 @@ void temp_open(int i, char *name, char *ft)
 	tempbufs[i].off = 0;
 	tempbufs[i].top = 0;
 	tempbufs[i].td = +1;
+	tempbufs[i].et = 0;
+	tempbufs[i].sw = 8;
+	tempbufs[i].ts = 8;
 	tempbufs[i].mtime = -1;
 	tempbufs[i].ft = ft;
 }
@@ -410,6 +419,51 @@ int ex_edit(const char *path, int len)
 	return 0;
 }
 
+static void ex_detect_indent(struct buf *p)
+{
+	int n = lbuf_len(p->lb);
+	int max = n < xidt ? n : xidt;
+	int tab_lines = 0, space_lines = 0;
+	int prev = 0;			/* previous line's leading spaces */
+	int delta[129];			/* delta[k] = times indent jumped by k */
+	memset(delta, 0, sizeof(delta));
+	for (int i = 0; i < max; i++) {
+		char *ln = lbuf_get(p->lb, i);
+		if (!ln)
+			break;
+		int tabs = 0, spaces = 0;
+		char *s = ln;
+		for (; *s == ' ' || *s == '\t'; s++)
+			*s == '\t' ? tabs++ : spaces++;
+		if (*s == '\n' || *s == '\0')	/* blank line: skip, keep prev */
+			continue;
+		if (tabs && !spaces) {
+			tab_lines++;
+		} else if (spaces) {
+			space_lines++;
+			int d = spaces - prev;
+			if (d > 0 && d <= 128)
+				delta[d]++;
+			prev = spaces;
+		} else
+			prev = 0;		/* dedent to column 0 */
+	}
+	if (tab_lines > space_lines) {
+		p->et = xet = 0;
+	} else if (space_lines > 0) {
+		int best = 0, bestn = 0;
+		for (int d = 1; d <= 128; d++)
+			if (delta[d] > bestn) {
+				bestn = delta[d];
+				best = d;
+			}
+		if (best) {
+			p->et = xet = 1;
+			p->sw = xsw = best;
+		}
+	}
+}
+
 static void *ec_edit(char *loc, char *cmd, char *arg)
 {
 	char msg[512];
@@ -667,6 +721,8 @@ void ex_bufpostfix(struct buf *p, int clear)
 	p->mtime = mtime(p->path);
 	p->ft = syn_filetype(p->path);
 	lbuf_saved(p->lb, clear);
+	if (xidt)
+		ex_detect_indent(p);
 }
 
 static void *ec_setpath(char *loc, char *cmd, char *arg)
@@ -1647,7 +1703,9 @@ static void *eo_##opt(char *loc, char *cmd, char *arg) { inner }
 EO(pac) EO(pr) EO(ai) EO(err) EO(fr) EO(ish) EO(ic) EO(mpt)
 EO(rr) EO(shape) EO(seq) EO(td) EO(order) EO(hll) EO(hlw)
 EO(hlp) EO(hlr) EO(hl) EO(lim) EO(led) EO(vis)
+EO(et) EO(idt)
 
+_EO(sw, if (*arg) xsw = eo_val(arg); return NULL;)
 _EO(ts, xts = *arg ? eo_val(arg) : !xts; xts = MAX(0, xts); return NULL;)
 _EO(grp, xgrp = (*arg ? eo_val(arg) : !xgrp) * 2; xgrp = MAX(0, xgrp); return NULL;)
 
@@ -1693,6 +1751,7 @@ static struct excmd {
 	EO(err),
 	{"ef!", ec_fuzz},
 	{"ef", ec_fuzz},
+	EO(et),
 	{"e!", ec_edit},
 	{"e", ec_edit},
 	{"ft", ec_ft},
@@ -1704,6 +1763,7 @@ static struct excmd {
 	{"f>", ec_find},
 	{"f<", ec_find},
 	{"f", ec_fuzz},
+	EO(idt),
 	EO(ish),
 	{"inc", ec_setincl},
 	EO(ic),
@@ -1734,6 +1794,7 @@ static struct excmd {
 	EO(seq),
 	{"sc!", ec_specials},
 	{"sc", ec_specials},
+	EO(sw),
 	{"s", ec_substitute},
 	{"x!", ec_write},
 	{"x", ec_write},
diff --git a/led.c b/led.c
index a38f7a06..329c9b24 100644
--- a/led.c
+++ b/led.c
@@ -454,18 +454,37 @@ static int led_line(sbuf *sb, int ps, int pre, char **post, int postn, char **po
 		case TK_CTL('t'):
 			cs = uc_dup(sb->s + ps);
 			sbuf_cut(sb, ps)
-			sbuf_chr(sb, '\t')
+			if (xet)
+				for (int _k = 0; _k < xsw; _k++)
+					sbuf_chr(sb, ' ')
+			else
+				sbuf_chr(sb, '\t')
 			sbuf_str(sb, cs)
 			free(cs);
-			pre++;
+			pre += xet ? xsw : 1;
 			break;
 		case TK_CTL('d'):
-			if (sb->s[ps] == ' ' || sb->s[ps] == '\t') {
+			if (xet) {
+				int _k;
+				for (_k = 0; _k < xsw && sb->s[ps + _k] == ' '; _k++);
+				if (_k) {
+					memmove(&sb->s[ps], &sb->s[ps + _k], len - ps - _k);
+					sb->s_n -= _k;
+					pre -= _k;
+				}
+			} else if (sb->s[ps] == ' ' || sb->s[ps] == '\t') {
 				memmove(&sb->s[ps], &sb->s[ps+1], len - ps - 1);
 				sb->s_n--;
 				pre--;
 			}
 			break;
+		case '\t':
+			if (xet)
+				for (int _l = 0; _l < xsw; _l++)
+					sbuf_chr(sb, ' ')
+			else
+				sbuf_chr(sb, '\t')
+			break;
 		case TK_CTL(']'):
 		case TK_CTL('\\'):
 			if (c == TK_CTL(']')) {
diff --git a/vi.c b/vi.c
index 2f4ccc2b..61562dcf 100644
--- a/vi.c
+++ b/vi.c
@@ -934,9 +934,19 @@ static void vi_shift(int r1, int r2, int dir, int count)
 			if (dir < 0) {
 				if (*ln != ' ' && *ln != '\t')
 					break;
-				ln++;
-			} else if (*ln != '\n' || r1 == r2)
-				sbuf_chr(sb, '\t')
+				if (xet && *ln == ' ') {
+					int k;
+					for (k = 0; k < xsw && *ln == ' '; k++)
+						ln++;
+				} else
+					ln++;
+			} else if (*ln != '\n' || r1 == r2) {
+				if (xet) {
+					for (int k = 0; k < xsw; k++)
+						sbuf_chr(sb, ' ')
+				} else
+					sbuf_chr(sb, '\t')
+			}
 		}
 		sbufn_str(sb, ln)
 		lbuf_edit(xb, sb->s, i, i + 1, 0, 0);
diff --git a/vi.h b/vi.h
index 0bb77c0b..ca2a6780 100644
--- a/vi.h
+++ b/vi.h
@@ -407,6 +407,9 @@ struct buf {
 	int plen, row, off, top;
 	long mtime;			/* modification time */
 	signed char td;			/* text direction */
+	int et;				/* expandtab - use spaces for indentation */
+	int sw;				/* shiftwidth - indentation step */
+	int ts;				/* tabspace - number of spaces for tab */
 };
 /* ex options */
 extern int xleft;
@@ -423,6 +426,9 @@ extern int xtd;
 extern int xshape;
 extern int xorder;
 extern int xts;
+extern int xet;
+extern int xsw;
+extern int xidt;
 extern int xish;
 extern int xgrp;
 extern int xpac;
@@ -464,12 +470,18 @@ extern struct buf *ex_pbuf;
 	xoff = buf->off; \
 	xtop = buf->top; \
 	xtd = buf->td; \
+	xet = buf->et; \
+	xsw = buf->sw; \
+	xts = buf->ts; \
 
 #define exbuf_save(buf) \
 	buf->row = xrow; \
 	buf->off = xoff; \
 	buf->top = xtop; \
 	buf->td = xtd; \
+	buf->et = xet; \
+	buf->sw = xsw; \
+	buf->ts = xts; \
 
 #define bufs_switchwft(idx) \
 { if (&bufs[idx] != ex_buf) { bufs_switch(idx); syn_setft(xb_ft); } } \
