#!/bin/sh -e
# Generated by patch2vi from unified diff
# Available separators: 0003-0010 0013-0014 0016-0037 0107-0110 0112 0120-0121 0123-0124 0126 0130-0132 0136 0176-0377

VI=${VI:-vi}
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi binary" >&2
    exit 1
fi

# Env switches:
# Phase 1 (search/mark) reports nothing by default
#   DBG1=1 reports failures and which fallback anchor
#   resolved a group, QF1=1 also quits on failure
# Phase 2 (edits) reports and quits by default
#   DBG2=1 silences it, QF2=1 keeps going after an error
# INTR=1 enters vi at the failing code line in this
#   script, for state inspection mid execution

# Body too large for EXINIT/argv: stage it in a file
( : > /tmp/p2vi.$$ ) 2>/dev/null && P2VIF=/tmp/p2vi.$$ || P2VIF=./p2vi.$$
trap 'rm -f "$P2VIF"' EXIT

# Patch: led.c
printf '%s%s%s\n' '|sc! |:vis 3ic 0217reg prFp FAIL %@219pr? %@212214reg ? %@217? %@211216reg ? %@220221reg vis 2q!1211reg ? %@221'\
"${DBG1:+213reg ? %@217? %@210215reg ? %@220}\
${DBG2:+ya!214ya!216}\
${QF1:+210reg vis 2q!1}\
${QF2:+ya!221}\
${INTR:+212reg |sc|vis 2:fr 0:e $0:83reg %@47:%f> 219reg %@219:&Q:b0:|sc! |:vis 3q1}"\
'fr 98b0%ya 98?0?
%f> static sbuf \*suggestsb;
static sbuf \*acsb;
sbuf \*led_attsb;

1??0?
1??m 11q0?
;0fr.,$f> ^static sbuf \*suggestsb;$4??0?
4??m 1220reg p OK led.c:1:a42sc %? %@2152sc!fr 98fr 980?
1;4??!219reg led.c:12sc %? %@2132sc!0?
?0?
%f+ 	if \(!xled\)
		return;
	ren_state \*r = ren_position\(s0\);
	int j, c, l, i, o, n = r->n;
	int att_old = 0, atti = 0, cterm = cend - cbeg;
	char \*bound = NULL;1??0?
1??+2m 21q0?
%f+ 	if \(!xled\)
		return;
	ren_state \*r = ren_position\(s0\);4??0?
4??+2m 2220reg p OK led.c:146:a42sc %? %@2152sc!1q0?
grp 1%f+ 	if \(!xled\).*?
		return;.*?
(	ren_state \*r = ren_position\(s0\);)7??0?
grp 07??m 2220reg p OK led.c:146:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> /\* render and highlight a line \*/
void led_render\(char \*s0, int cbeg, int cend\)
\{.*(		o = cbeg;)
		for \(c = cterm-1; c >= 0; c--, o\+\+\)
			off\[c] = o <= r->cmax \? r->col\[o] : -1;8??0?
grp 08??-12m 2220reg p OK led.c:146:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	} \\
	att_old = att_new; \\
} } \\.*(		for \(c = cbeg; c < cend; c\+\+\))
			off\[c - cbeg] = c <= r->cmax \? r->col\[c] : -1;
	}9??0?
grp 09??-16m 2220reg p OK led.c:146:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg led.c:1462sc %? %@2132sc!0?
?0?
%f+ 	char \*bound = NULL;
	char \*\*chrs = r->chrs;	/\* chrs\[i]: the i-th character in s0 \*/
	int off\[cterm\+1];	/\* off\[i]: the character at screen position i \*/
	int att\[cterm\+1];	/\* att\[i]: the attributes of i-th character \*/
	int stt\[cterm\+1];	/\* stt\[i]: remap off indexes \*/
	int ctt\[cterm\+1];	/\* ctt\[i]: cterm bound attrs \*/
	int ctx = r->ctx;
	off\[cterm] = -1;
	if \(ctx < 0\) \{1??0?
1??+3m 31q0?
%f+ 	int att\[cterm\+1];	/\* att\[i]: the attributes of i-th character \*/
	int stt\[cterm\+1];	/\* stt\[i]: remap off indexes \*/
	int ctt\[cterm\+1];	/\* ctt\[i]: cterm bound attrs \*/
	int ctx = r->ctx;
	off\[cterm] = -1;
	if \(ctx < 0\) \{2??0?
2??m 3220reg p OK led.c:152:a22sc %? %@2152sc!1q0?
%f+ 	int att\[cterm\+1];	/\* att\[i]: the attributes of i-th character \*/
	int stt\[cterm\+1];	/\* stt\[i]: remap off indexes \*/
	int ctt\[cterm\+1];	/\* ctt\[i]: cterm bound attrs \*/3??0?
3??m 3220reg p OK led.c:152:a32sc %? %@2152sc!1q0?
%f+ 	char \*bound = NULL;
	char \*\*chrs = r->chrs;	/\* chrs\[i]: the i-th character in s0 \*/
	int off\[cterm\+1];	/\* off\[i]: the character at screen position i \*/4??0?
4??+3m 3220reg p OK led.c:152:a42sc %? %@2152sc!1q0?
%f+ 	int ctx = r->ctx;
	off\[cterm] = -1;
	if \(ctx < 0\) \{5??0?
5??-3m 3220reg p OK led.c:152:a52sc %? %@2152sc!1q0?
%f+ ...ar..b............
	.ha. .....s.=....c.rs......h.s........ .....ch.ra...r.........
	i.t o...c......].	.....f.i.....e.....a.ter....s.r..n......i.. i \*.
..........t...\+1.;.....tt..]..... a...i..........-....h..a.......
	.nt....\[c....\+.......s.......r.ma...f....d...s...
..n. ct..c...m.1..	/\*..tt\[.]. ...r........a.tr....
	.n......=........
.of..cte... =..1.
	....c.x.<... \{6??0?
6??+3m 3220reg p OK led.c:152:a62sc %? %@2152sc!1q0?
grp 1%f+ 	char \*bound = NULL;.*?
	char \*\*chrs = r->chrs;	/\* chrs\[i]: the i-th character in s0 \*/.*?
	int off\[cterm\+1];	/\* off\[i]: the character at screen position i \*/.*?
(	int att\[cterm\+1];	/\* att\[i]: the attributes of i-th character \*/)7??0?
grp 07??m 3220reg p OK led.c:152:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> /\* render and highlight a line \*/
void led_render\(char \*s0, int cbeg, int cend\)
\{.*(		o = cbeg;)
		for \(c = cterm-1; c >= 0; c--, o\+\+\)
			off\[c] = o <= r->cmax \? r->col\[o] : -1;8??0?
grp 08??-6m 3220reg p OK led.c:152:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	} \\
	att_old = att_new; \\
} } \\.*(		for \(c = cbeg; c < cend; c\+\+\))
			off\[c - cbeg] = c <= r->cmax \? r->col\[c] : -1;
	}9??0?
grp 09??-10m 3220reg p OK led.c:152:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg led.c:1522sc %? %@2132sc!0?
?0?
%f+ 			off\[c - cbeg] = c <= r->cmax \? r->col\[c] : -1;
	}
	if \(r->cmax > cterm \|\| cbeg\) \{
		i = ctx < 0 \? cterm-1 : 0;
		o = off\[i];
		if \(o >= 0 && cbeg && r->pos\[o] < cbeg\)1??0?
1??+2m 41q0?
%f+ 			off\[c - cbeg] = c <= r->cmax \? r->col\[c] : -1;
	}
	if \(r->cmax > cterm \|\| cbeg\) \{4??0?
4??+2m 4220reg p OK led.c:165:a42sc %? %@2152sc!1q0?
grp 1%f+ 			off\[c - cbeg] = c <= r->cmax \? r->col\[c] : -1;.*?
	}.*?
(	if \(r->cmax > cterm \|\| cbeg\) \{)7??0?
grp 07??m 4220reg p OK led.c:165:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 			off\[c] = o <= r->cmax \? r->col\[o] : -1;
	} else \{
		for \(c = cbeg; c < cend; c\+\+\).*(				off\[ctx < 0 \? i-- : i\+\+] = -1;)
		i = ctx < 0 \? 0 : cterm-1;
		o = off\[i];8??0?
grp 08??-5m 4220reg p OK led.c:165:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	if \(ctx < 0\) \{
		o = cbeg;
		for \(c = cterm-1; c >= 0; c--, o\+\+\).*(		if \(o >= 0 && r->cmax > cterm && r->pos\[o] \+ r->wid\[o] > cend\))
			while \(off\[i] == o\)
				off\[ctx < 0 \? i\+\+ : i--] = -1;9??0?
grp 09??-8m 4220reg p OK led.c:165:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg led.c:1652sc %? %@2132sc!0?
?0?
%f+ 		if \(o >= 0 && r->cmax > cterm && r->pos\[o] \+ r->wid\[o] > cend\)
			while \(off\[i] == o\)
				off\[ctx < 0 \? i\+\+ : i--] = -1;
		for \(i = 0, c = 0; i < cterm;\) \{
			if \(\(o = off\[i\+\+]\) >= 0\) \{
				att\[c\+\+] = o;
				for \(; off\[i] == o; i\+\+\);1??0?
1??+3m 51q0?
%f+ 		for \(i = 0, c = 0; i < cterm;\) \{
			if \(\(o = off\[i\+\+]\) >= 0\) \{
				att\[c\+\+] = o;
				for \(; off\[i] == o; i\+\+\);2??0?
2??m 5220reg p OK led.c:176:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^		for \(i = 0, c = 0; i < cterm;\) \{$3??0?
3??m 5220reg p OK led.c:176:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 		if \(o >= 0 && r->cmax > cterm && r->pos\[o] \+ r->wid\[o] > cend\)
			while \(off\[i] == o\)
				off\[ctx < 0 \? i\+\+ : i--] = -1;4??0?
4??+3m 5220reg p OK led.c:176:a42sc %? %@2152sc!1q0?
%f+ 			if \(\(o = off\[i\+\+]\) >= 0\) \{
				att\[c\+\+] = o;
				for \(; off\[i] == o; i\+\+\);5??0?
5??-1m 5220reg p OK led.c:176:a52sc %? %@2152sc!1q0?
%f+ .... \(...=....&....c..x.. ..... &. r.>...\[.. ..r...id........n.\)
..........o..\[.. ....\)
	.......c.. ..... ....: i........;
..f..... ..., ...... i.. ....m.. .
...i...\(. . .ff..............
	........\+\+. ..o.
...	........f.\[i...=.o.....\).6??0?
6??+3m 5220reg p OK led.c:176:a62sc %? %@2152sc!1q0?
grp 1%f+ 		if \(o >= 0 && r->cmax > cterm && r->pos\[o] \+ r->wid\[o] > cend\).*?
			while \(off\[i] == o\).*?
				off\[ctx < 0 \? i\+\+ : i--] = -1;.*?
(		for \(i = 0, c = 0; i < cterm;\) \{)7??0?
grp 07??m 5220reg p OK led.c:176:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 				off\[ctx < 0 \? i-- : i\+\+] = -1;
		i = ctx < 0 \? 0 : cterm-1;
		o = off\[i];.*(			while \(j >= 0 && att\[j] > key0\) \{)
				att\[j \+ 1] = att\[j];
				stt\[j \+ 1] = stt\[j];8??0?
grp 08??-10m 5220reg p OK led.c:176:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 		o = off\[i];
		if \(o >= 0 && cbeg && r->pos\[o] < cbeg\)
			while \(off\[i] == o\).*(				j = j - 1;)
			}
			att\[j \+ 1] = key0;9??0?
grp 09??-13m 5220reg p OK led.c:176:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg led.c:1762sc %? %@2132sc!0?
?0?
%f+ 				for \(; off\[i] == o; i\+\+\);
			}
		}
		stt\[0] = 0;
		for \(i = 1; i < c; i\+\+\) \{
			int key0 = att\[i];1??0?
1??+2m 61q0?
%f+ 				for \(; off\[i] == o; i\+\+\);
			}
		}4??0?
4??+2m 6220reg p OK led.c:181:a42sc %? %@2152sc!1q0?
grp 1%f+ 				for \(; off\[i] == o; i\+\+\);.*?
			}.*?
(		})7??0?
grp 07??m 6220reg p OK led.c:181:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 				off\[ctx < 0 \? i-- : i\+\+] = -1;
		i = ctx < 0 \? 0 : cterm-1;
		o = off\[i];.*(			while \(j >= 0 && att\[j] > key0\) \{)
				att\[j \+ 1] = att\[j];
				stt\[j \+ 1] = stt\[j];8??0?
grp 08??-5m 6220reg p OK led.c:181:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 		o = off\[i];
		if \(o >= 0 && cbeg && r->pos\[o] < cbeg\)
			while \(off\[i] == o\).*(				j = j - 1;)
			}
			att\[j \+ 1] = key0;9??0?
grp 09??-8m 6220reg p OK led.c:181:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg led.c:1812sc %? %@2132sc!0?
?0?
%f+ 		sbuf_nul4\(bsb\)
		bound = bsb->s;
	}
	memset\(att, 0, MIN\(n, cterm\+1\) \* sizeof\(att\[0]\)\);
	if \(xhl\)1??0?
1??+3m 71q0?
%f+ 	memset\(att, 0, MIN\(n, cterm\+1\) \* sizeof\(att\[0]\)\);
	if \(xhl\)2??0?
2??m 7220reg p OK led.c:203:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^	memset\(att, 0, MIN\(n, cterm\+1\) \* sizeof\(att\[0]\)\);$3??0?
3??m 7220reg p OK led.c:203:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 		sbuf_nul4\(bsb\)
		bound = bsb->s;
	}4??0?
4??+3m 7220reg p OK led.c:203:a42sc %? %@2152sc!1q0?
;0fr.,$f+ ^	if \(xhl\)$5??0?
5??-1m 7220reg p OK led.c:203:a52sc %? %@2152sc!fr 981qfr 980?
%f+ .....f...l......
	.bou............
.}
....s.t......0,....\(.. ..e...1.........f..........
	......l\)6??0?
6??+3m 7220reg p OK led.c:203:a62sc %? %@2152sc!1q0?
grp 1%f+ 		sbuf_nul4\(bsb\).*?
		bound = bsb->s;.*?
	}.*?
(	memset\(att, 0, MIN\(n, cterm\+1\) \* sizeof\(att\[0]\)\);)7??0?
grp 07??m 7220reg p OK led.c:203:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 			stt\[i] = att\[i];
			sbuf_mem\(bsb, chrs\[att\[i]], uc_len\(chrs\[att\[i]]\)\)
		}.*(		for \(; \(char\*\)p < &led_attsb->s\[led_attsb->s_n]; p\+\+\) \{)
			if \(p->s != s0 && p->s\)
				continue;8??0?
grp 08??-6m 7220reg p OK led.c:203:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 		sbuf_smake\(bsb, cterm\*4\);
		for \(i = 0; i < c; i\+\+\) \{
			ctt\[stt\[i]] = i;.*(			if \(!bound\))
				att\[p->off] = syn_merge\(att\[p->off], p->att\);
			else if \(c && stt\[0] <= p->off && stt\[c-1] >= p->off\) \{9??0?
grp 09??-9m 7220reg p OK led.c:203:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg led.c:2032sc %? %@2132sc!0?
?0?
%f+ 	if \(xhl\)
		syn_highlight\(att, bound \? bound : s0, MIN\(n, cterm\)\);
	free\(bound\);
	if \(led_attsb && xhl\) \{
		led_att \*p = \(led_att\*\)led_attsb->s;1??0?
1??+1m 81q0?
%f+ 		syn_highlight\(att, bound \? bound : s0, MIN\(n, cterm\)\);
	free\(bound\);
	if \(led_attsb && xhl\) \{
		led_att \*p = \(led_att\*\)led_attsb->s;2??0?
2??m 8220reg p OK led.c:205:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^		syn_highlight\(att, bound \? bound : s0, MIN\(n, cterm\)\);$3??0?
3??m 8220reg p OK led.c:205:a32sc %? %@2152sc!fr 981qfr 980?
;0fr.,$f+ ^	if \(xhl\)$4??0?
4??+1m 8220reg p OK led.c:205:a42sc %? %@2152sc!fr 981qfr 980?
%f+ 	free\(bound\);
	if \(led_attsb && xhl\) \{
		led_att \*p = \(led_att\*\)led_attsb->s;5??0?
5??-1m 8220reg p OK led.c:205:a52sc %? %@2152sc!1q0?
%f+ .if \(...\)
	.s.........g...........n. ....un..........N........m.\).
..r.e\(..u.d.;
....\(...................
..l.._.......=...e...t.....d.a..s.-...6??0?
6??+1m 8220reg p OK led.c:205:a62sc %? %@2152sc!1q0?
grp 1%f+ 	if \(xhl\).*?
(		syn_highlight\(att, bound \? bound : s0, MIN\(n, cterm\)\);)7??0?
grp 07??m 8220reg p OK led.c:205:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 			stt\[i] = att\[i];
			sbuf_mem\(bsb, chrs\[att\[i]], uc_len\(chrs\[att\[i]]\)\)
		}.*(		for \(; \(char\*\)p < &led_attsb->s\[led_attsb->s_n]; p\+\+\) \{)
			if \(p->s != s0 && p->s\)
				continue;8??0?
grp 08??-4m 8220reg p OK led.c:205:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 		sbuf_smake\(bsb, cterm\*4\);
		for \(i = 0; i < c; i\+\+\) \{
			ctt\[stt\[i]] = i;.*(			if \(!bound\))
				att\[p->off] = syn_merge\(att\[p->off], p->att\);
			else if \(c && stt\[0] <= p->off && stt\[c-1] >= p->off\) \{9??0?
grp 09??-7m 8220reg p OK led.c:205:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg led.c:2052sc %? %@2132sc!0?
?0?
%f+ 			if \(!bound\)
				att\[p->off] = syn_merge\(att\[p->off], p->att\);
			else if \(c && stt\[0] <= p->off && stt\[c-1] >= p->off\) \{
				i = p->off - stt\[0];
				if \(i < c && stt\[i] == p->off\) \{
					att\[i] = syn_merge\(att\[i], p->att\);
					continue; /\* text not reordered \*/1??0?
1??+3m 91q0?
%f+ 				i = p->off - stt\[0];
				if \(i < c && stt\[i] == p->off\) \{
					att\[i] = syn_merge\(att\[i], p->att\);
					continue; /\* text not reordered \*/2??0?
2??m 9220reg p OK led.c:215:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^				i = p->off - stt\[0];$3??0?
3??m 9220reg p OK led.c:215:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 			if \(!bound\)
				att\[p->off] = syn_merge\(att\[p->off], p->att\);
			else if \(c && stt\[0] <= p->off && stt\[c-1] >= p->off\) \{4??0?
4??+3m 9220reg p OK led.c:215:a42sc %? %@2152sc!1q0?
%f+ 				if \(i < c && stt\[i] == p->off\) \{
					att\[i] = syn_merge\(att\[i], p->att\);
					continue; /\* text not reordered \*/5??0?
5??-1m 9220reg p OK led.c:215:a52sc %? %@2152sc!1q0?
%f+ ....f.\(!......
...	.......o........n.........t\[...off.........\).
.		...e....\(.....s......<..p.>..f ...s...c.1. ...p....f...
.	....=...>........t....
.......\(........ st.........-......\{
............. ..n....g................\).
......on...... /\* ..xt.....r.....red...6??0?
6??+3m 9220reg p OK led.c:215:a62sc %? %@2152sc!1q0?
grp 1%f+ 			if \(!bound\).*?
				att\[p->off] = syn_merge\(att\[p->off], p->att\);.*?
			else if \(c && stt\[0] <= p->off && stt\[c-1] >= p->off\) \{.*?
(				i = p->off - stt\[0];)7??0?
grp 07??m 9220reg p OK led.c:215:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 		for \(; \(char\*\)p < &led_attsb->s\[led_attsb->s_n]; p\+\+\) \{
			if \(p->s != s0 && p->s\)
				continue;.*(				for \(l = 0, j = c - 1; l <= j;\) \{)
					i = l \+ \(j - l\) / 2;
					if \(stt\[i] == p->off\) \{8??0?
grp 08??-5m 9220reg p OK led.c:215:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	free\(bound\);
	if \(led_attsb && xhl\) \{
		led_att \*p = \(led_att\*\)led_attsb->s;.*(						att\[i] = syn_merge\(att\[i], p->att\);)
						break;
					} else if \(stt\[i] < p->off\)9??0?
grp 09??-8m 9220reg p OK led.c:215:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg led.c:2152sc %? %@2132sc!0?
'\''1i #define LEDBACK 300
#define LEDFORW 300

??!219reg led.c:1:m12sc %? %@2142sc!0?
'\''2i 	int fcbeg = cbeg - LEDBACK < 0 ? 0 : cbeg - LEDBACK;
	int fcend = cend + LEDFORW;
	int fcterm = fcend - fcbeg; /* fake the render dimensions */
??!219reg led.c:146:m22sc %? %@2142sc!0?
'\''3,#+2c 	int att[fcterm+1];	/* att[i]: the attributes of i-th character */
	int stt[fcterm+1];	/* stt[i]: remap off indexes */
	int ctt[fcterm+1];	/* ctt[i]: cterm bound attrs */
??!219reg led.c:152:m32sc %? %@2142sc!0?
'\''4i 		c = 0;
??!219reg led.c:165:m42sc %? %@2142sc!0?
'\''5c 		l = cbeg <= r->cmax ? r->col[cbeg] : -1;
		for (o = 0; l > 0 && l <= n && o < LEDBACK; o++) {
			if (r->pos[l] < cbeg && c < fcterm) {
				atti++;
				att[c++] = l;
			}
			l -= ctx;
		}
		for (i = 0; i < cterm;) {
??!219reg led.c:176:m52sc %? %@2142sc!0?
'\''6i 		l = cend <= r->cmax ? r->col[cend] : -1;
		for (o = 0; l > 0 && l <= n && o < LEDFORW; o++) {
			if (r->pos[l] >= cend && c < fcterm) {
				att[c++] = l;
			}
			l += ctx;
		}
??!219reg led.c:181:m62sc %? %@2142sc!0?
'\''7s/ c/ fc/??!219reg led.c:203:m72sc %? %@2142sc!0?
'\''8s/ c/ fc/??!219reg led.c:205:m82sc %? %@2142sc!0?
'\''9s/0/atti/??!219reg led.c:215:m92sc %? %@2142sc!vis 2b0w2q' > "$P2VIF"
EXINIT='%ya 97:? %@97' $VI -e 'led.c' "$P2VIF"

if [ $# -gt 0 ]; then
    export P2VI_PATCH="$P2VI_PATCH ${0##*/}"
    next=$1
    shift
    case $next in /*|./*|../*) "$next" "$@" ;; *) "./$next" "$@" ;; esac
fi

exit 0
=== PATCH2VI PATCH ===
diff --git a/led.c b/led.c
index a38f7a06..bcbe59be 100644
--- a/led.c
+++ b/led.c
@@ -1,4 +1,7 @@
 static sbuf *suggestsb;
+#define LEDBACK 300
+#define LEDFORW 300
+
 static sbuf *acsb;
 sbuf *led_attsb;
 
@@ -144,14 +147,17 @@ void led_render(char *s0, int cbeg, int cend)
 	if (!xled)
 		return;
 	ren_state *r = ren_position(s0);
+	int fcbeg = cbeg - LEDBACK < 0 ? 0 : cbeg - LEDBACK;
+	int fcend = cend + LEDFORW;
+	int fcterm = fcend - fcbeg; /* fake the render dimensions */
 	int j, c, l, i, o, n = r->n;
 	int att_old = 0, atti = 0, cterm = cend - cbeg;
 	char *bound = NULL;
 	char **chrs = r->chrs;	/* chrs[i]: the i-th character in s0 */
 	int off[cterm+1];	/* off[i]: the character at screen position i */
-	int att[cterm+1];	/* att[i]: the attributes of i-th character */
-	int stt[cterm+1];	/* stt[i]: remap off indexes */
-	int ctt[cterm+1];	/* ctt[i]: cterm bound attrs */
+	int att[fcterm+1];	/* att[i]: the attributes of i-th character */
+	int stt[fcterm+1];	/* stt[i]: remap off indexes */
+	int ctt[fcterm+1];	/* ctt[i]: cterm bound attrs */
 	int ctx = r->ctx;
 	off[cterm] = -1;
 	if (ctx < 0) {
@@ -163,6 +169,7 @@ void led_render(char *s0, int cbeg, int cend)
 			off[c - cbeg] = c <= r->cmax ? r->col[c] : -1;
 	}
 	if (r->cmax > cterm || cbeg) {
+		c = 0;
 		i = ctx < 0 ? cterm-1 : 0;
 		o = off[i];
 		if (o >= 0 && cbeg && r->pos[o] < cbeg)
@@ -173,12 +180,27 @@ void led_render(char *s0, int cbeg, int cend)
 		if (o >= 0 && r->cmax > cterm && r->pos[o] + r->wid[o] > cend)
 			while (off[i] == o)
 				off[ctx < 0 ? i++ : i--] = -1;
-		for (i = 0, c = 0; i < cterm;) {
+		l = cbeg <= r->cmax ? r->col[cbeg] : -1;
+		for (o = 0; l > 0 && l <= n && o < LEDBACK; o++) {
+			if (r->pos[l] < cbeg && c < fcterm) {
+				atti++;
+				att[c++] = l;
+			}
+			l -= ctx;
+		}
+		for (i = 0; i < cterm;) {
 			if ((o = off[i++]) >= 0) {
 				att[c++] = o;
 				for (; off[i] == o; i++);
 			}
 		}
+		l = cend <= r->cmax ? r->col[cend] : -1;
+		for (o = 0; l > 0 && l <= n && o < LEDFORW; o++) {
+			if (r->pos[l] >= cend && c < fcterm) {
+				att[c++] = l;
+			}
+			l += ctx;
+		}
 		stt[0] = 0;
 		for (i = 1; i < c; i++) {
 			int key0 = att[i];
@@ -200,9 +222,9 @@ void led_render(char *s0, int cbeg, int cend)
 		sbuf_nul4(bsb)
 		bound = bsb->s;
 	}
-	memset(att, 0, MIN(n, cterm+1) * sizeof(att[0]));
+	memset(att, 0, MIN(n, fcterm+1) * sizeof(att[0]));
 	if (xhl)
-		syn_highlight(att, bound ? bound : s0, MIN(n, cterm));
+		syn_highlight(att, bound ? bound : s0, MIN(n, fcterm));
 	free(bound);
 	if (led_attsb && xhl) {
 		led_att *p = (led_att*)led_attsb->s;
@@ -212,7 +234,7 @@ void led_render(char *s0, int cbeg, int cend)
 			if (!bound)
 				att[p->off] = syn_merge(att[p->off], p->att);
 			else if (c && stt[0] <= p->off && stt[c-1] >= p->off) {
-				i = p->off - stt[0];
+				i = p->off - stt[atti];
 				if (i < c && stt[i] == p->off) {
 					att[i] = syn_merge(att[i], p->att);
 					continue; /* text not reordered */
