#!/bin/sh -e
# Generated by patch2vi from unified diff
# Available separators: 0003-0010 0013-0014 0016-0037 0112 0120-0121 0126 0176-0377

VI=${VI:-vi}
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi binary" >&2
    exit 1
fi

# Env switches:
# Phase 1 (search/mark) reports nothing by default
#   DBG1=1 reports failures and which fallback anchor
#   resolved a group, QF1=1 also quits on failure
# Phase 2 (edits) reports and quits by default
#   DBG2=1 silences it, QF2=1 keeps going after an error
# INTR=1 enters vi at the failing code line in this
#   script, for state inspection mid execution

# Body too large for EXINIT/argv: stage it in a file
( : > /tmp/p2vi.$$ ) 2>/dev/null && P2VIF=/tmp/p2vi.$$ || P2VIF=./p2vi.$$
trap 'rm -f "$P2VIF"' EXIT

# Patch: conf.c ex.c led.c vi.c vi.h
printf '%s%s%s\n' '|sc! |:vis 3ic 0217reg prFp FAIL %@219pr? %@212214reg ? %@217? %@211216reg ? %@220221reg vis 2q!1211reg ? %@221'\
"${DBG1:+213reg ? %@217? %@210215reg ? %@220}\
${DBG2:+ya!214ya!216}\
${QF1:+210reg vis 2q!1}\
${QF2:+ya!221}\
${INTR:+212reg |sc|vis 2:fr 0:e $0:83reg %@47:%f> 219reg %@219:&Q:b0:|sc! |:vis 3q1}"\
'fr 98b0%ya 98?0?
%f> \(\?:\(\[,;]#\?\)\[ \\t]\*\(\(\?:\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\(\?:\(\?:<\(\?:\[\^<\\\\\\\\]\|\\\\\\\\\.\?\)\*<\?\|>\(\?:\[\^>\\\\\\\\]\|\\\\\\\\\.\?\)\*>\?\)\|\\
\(\?:'\''\[0-9]\+\)\|\(\[\.\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\(\[0-9]\+\)\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\)\*\[ \\t]\*\)\*\)\\
\(\(pac\|pr\|ai\|ish\|err\|fr\|ic\|grp\|mpt\|rr\|shape\|seq\|ts\|td\|order\|hl\[lwpr]\?\|left\|lim\|led\|vis\)\\
\|\[@&!dmj]\|=\\\\\?\{0,1}\|\\\\\?\{1,2}\[\?!]\?\|b\[psx]\?\|p\[uh]\?\|ac\|e\[f!]\?!\?\|f\[-\+><tdp]\?\|inc\|i\|sc!\?\|\\
\(\?:g!\?\|s\)\[ \\t]\?\(\.\)\?\|q!\?\|reg\?\\\\\+\?\|rd\?\|w\(\?:q!\|\[q!]\)\?\|u\[czbd]\|x!\?\|ya\[!\+]\?\|cm!\?\|cd\?\)\?",
		A\(BL1 \| SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1\)},
	\{ex_ft, "\\\\\\\\\(\.\)", A\(AY1 \| SYN_BD, YE\)},1??0?
1??+3m 11q0?
%f> \|\[@&!dmj]\|=\\\\\?\{0,1}\|\\\\\?\{1,2}\[\?!]\?\|b\[psx]\?\|p\[uh]\?\|ac\|e\[f!]\?!\?\|f\[-\+><tdp]\?\|inc\|i\|sc!\?\|\\
\(\?:g!\?\|s\)\[ \\t]\?\(\.\)\?\|q!\?\|reg\?\\\\\+\?\|rd\?\|w\(\?:q!\|\[q!]\)\?\|u\[czbd]\|x!\?\|ya\[!\+]\?\|cm!\?\|cd\?\)\?",
		A\(BL1 \| SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1\)},
	\{ex_ft, "\\\\\\\\\(\.\)", A\(AY1 \| SYN_BD, YE\)},2??0?
2??m 1220reg p OK conf.c:301:a22sc %? %@2152sc!1q0?
;0fr.,$f> ^\|\[@&!dmj]\|=\\\\\?\{0,1}\|\\\\\?\{1,2}\[\?!]\?\|b\[psx]\?\|p\[uh]\?\|ac\|e\[f!]\?!\?\|f\[-\+><tdp]\?\|inc\|i\|sc!\?\|\\$3??0?
3??m 1220reg p OK conf.c:301:a32sc %? %@2152sc!fr 981qfr 980?
%f> \(\?:\(\[,;]#\?\)\[ \\t]\*\(\(\?:\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\(\?:\(\?:<\(\?:\[\^<\\\\\\\\]\|\\\\\\\\\.\?\)\*<\?\|>\(\?:\[\^>\\\\\\\\]\|\\\\\\\\\.\?\)\*>\?\)\|\\
\(\?:'\''\[0-9]\+\)\|\(\[\.\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\(\[0-9]\+\)\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\)\*\[ \\t]\*\)\*\)\\
\(\(pac\|pr\|ai\|ish\|err\|fr\|ic\|grp\|mpt\|rr\|shape\|seq\|ts\|td\|order\|hl\[lwpr]\?\|left\|lim\|led\|vis\)\\4??0?
4??+3m 1220reg p OK conf.c:301:a42sc %? %@2152sc!1q0?
%f> \(\?:g!\?\|s\)\[ \\t]\?\(\.\)\?\|q!\?\|reg\?\\\\\+\?\|rd\?\|w\(\?:q!\|\[q!]\)\?\|u\[czbd]\|x!\?\|ya\[!\+]\?\|cm!\?\|cd\?\)\?",
		A\(BL1 \| SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1\)},
	\{ex_ft, "\\\\\\\\\(\.\)", A\(AY1 \| SYN_BD, YE\)},5??0?
5??-1m 1220reg p OK conf.c:301:a52sc %? %@2152sc!1q0?
%f> .\?...............................\\].......\)\*..\|.\[..t...\*.\?..\?:........\\.......\\.............>\\.\\....\\...\?.\*.....
......-..........\|......t............\*../........................\*.....\\..\*\\\\...........]\|....\.\?...\\\|..\*...t]\*.\*..
.....\|p.....is.....\|........p............e.........d......\|..\[l.pr...l.....im......i...
.\[..!...........,1.......,.........\[..x]..........c....!]\?......\+...d...\|...\|i.......
\(\?..!\?..\).................g.\\.\+\?..d.\|w...........\?.....b.....\?...\[...\?........\?....
	.A\(......S.._.D..RE, ... R.,..., .....M.........E. .H..............1......},
	....f.......\\\(.\).....A...\|........ ....,6??0?
6??+3m 1220reg p OK conf.c:301:a62sc %? %@2152sc!1q0?
grp 1%f> \(\?:\(\[,;]#\?\)\[ \\t]\*\(\(\?:\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\(\?:\(\?:<\(\?:\[\^<\\\\\\\\]\|\\\\\\\\\.\?\)\*<\?\|>\(\?:\[\^>\\\\\\\\]\|\\\\\\\\\.\?\)\*>\?\)\|\\.*?
\(\?:'\''\[0-9]\+\)\|\(\[\.\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\(\[0-9]\+\)\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\)\*\[ \\t]\*\)\*\)\\.*?
\(\(pac\|pr\|ai\|ish\|err\|fr\|ic\|grp\|mpt\|rr\|shape\|seq\|ts\|td\|order\|hl\[lwpr]\?\|left\|lim\|led\|vis\)\\.*?
(\|\[@&!dmj]\|=\\\\\?\{0,1}\|\\\\\?\{1,2}\[\?!]\?\|b\[psx]\?\|p\[uh]\?\|ac\|e\[f!]\?!\?\|f\[-\+><tdp]\?\|inc\|i\|sc!\?\|\\)7??0?
grp 07??m 1220reg p OK conf.c:301:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	\{ex_ft, "\.\+", A\(AY1 \| SYN_BD\), 1},
	\{ex_ft, ":\[ \\t]\*\(\(\(\(\?:\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\(\?:\(\?:<\(\?:\[\^<\\\\\\\\]\|\\\\\\\\\.\?\)\*<\?\|>\(\?:\[\^>\\\\\\\\]\|\\\\\\\\\.\?\)\*>\?\)\|\\
\(\?:'\''\[0-9]\+\)\|\(\[\.%\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\[0-9]\+\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\)\[ \\t]\*\\.*(	\{vs_ft, "\.\+", A\(AY1 \| SYN_BD\), 1},)
	\{vs_ft, "\(\^\[\?/]\)\|\(\\\\\\\\\[<>]\|\\\\\(\\\\\?\[:=!<>#]\|\\\\\[\\\\\^\?\(\(\?:\\\\\\\\\.\?\|\[\^\\\\]]\)\*\)]\|\\\\\[\|\[\.\^\$\\\\\(\)\*\+\|\?]\|\\\\\{\(\[0-9]\*\(,\)\?\[0-9]\*\)\?}\?\)\|\\\\\\\\\(\.\)",
		A\(SYN_BD, BL1, WH1, GR1, RE1, WH1, YE\)},8??0?
grp 08??-6m 1220reg p OK conf.c:301:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	\{ac_ft, "\[\^ \\t-/:-@\[-\^\{-~]\+\(\?:\(\\n\$\)\|\\n\)\|\\n\|\(\[\^\\n]\+\(\\n\)\)",
		A\(NA, SYN_BGMK\(RE1\), SYN_BGMK\(AY1\), SYN_BGMK\(AY\)\)},
	\{ac_ft, "\[\^ \\t-/:-@\[-\^\{-~]\+\$\|\(\.\+\$\)", A\(NA, SYN_BGMK\(AY1\)\)},.*(	\{vs_ft, "\(\\\\\\\\\)\(\.\)\(\?:\(-\)\(\?:\(\\\\\\\\\(\.\)\)\|\[\^\\\\\\\\\\\\]]\)\)\?\|\[\^\\\\\\\\\[\^]\(-\)\(\?:\(\\\\\\\\\(\.\)\)\|\.\)\|\\)
\[\^\\\\\\\\\[\^]\\\\\^\(-\)\(\?:\(\\\\\\\\\(\.\)\)\|\[\^\\\\\\\\]\)\|\\\\\^\(-\)\[\^\\\\\\\\]",
		A\(GR1 \| SYN_BD \| SYN_ATT, 1, GR1, AY1, YE, WH1, AY1, YE, WH1, AY1, YE, WH1, AY1, YE, WH1\), 2},9??0?
grp 09??-9m 1220reg p OK conf.c:301:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg conf.c:3012sc %? %@2132sc!0?
'\''1s/\|sc/m!?|i|sc!?|nm/??!219reg conf.c:301:m12sc %? %@2142sc!b1%ya 98?0?
%f> int xleft;			/\* the first visible column \*/
int xvis;			/\* startup flags \*/
int xai = 1;			/\* autoindent option \*/1??0?
1??m 11q0?
;0fr.,$f> ^int xleft;			/\* the first visible column \*/$4??0?
4??m 1220reg p OK ex.c:0:a42sc %? %@2152sc!fr 98fr 980?
1;4??!219reg ex.c:02sc %? %@2132sc!0?
?0?
%f+ 	return NULL;
}

static void \*ec_buffer\(char \*loc, char \*cmd, char \*arg\)
\{
	int n = atoi\(arg\);1??0?
1??+2m 21q0?
%f+ 	return NULL;
}

4??0?
4??+2m 2220reg p OK ex.c:622:a42sc %? %@2152sc!1q0?
m 01;0grp 1%f> 		return xuerr;
	xrow = nbeg;
	xoff = off;.*(	if \(!arg\[0]\) \{)
		char ln\[512];
		for \(int i = 0; i < xbufcur; i\+\+\) \{8??0?
grp 08??-4m 2220reg p OK ex.c:622:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	}
	if \(lbuf_search\(xb, xkwdrs, xkwddir, beg, end,
			pskip, nskip, &nbeg, &off\)\).*(			char c = ex_buf == bufs\+i \? '\''%'\'' : '\'' '\'';)
			c = ex_pbuf == bufs\+i \? '\''#'\'' : c;
			snprintf\(ln, LEN\(ln\), "%d %c %s", i,9??0?
grp 09??-7m 2220reg p OK ex.c:622:a92sc %? %@2152sc!'\''00?
1;4;8;9??!219reg ex.c:6222sc %? %@2132sc!0?
?0?
%f+ 	EO\(ish\),
	\{"inc", ec_setincl},
	EO\(ic\),
	\{"i", ec_insert},
	\{"d", ec_delete},
	EO\(grp\),1??0?
1??+2m 31q0?
%f+ 	EO\(ish\),
	\{"inc", ec_setincl},
	EO\(ic\),4??0?
4??+2m 3220reg p OK ex.c:1709:a42sc %? %@2152sc!1q0?
grp 1%f+ 	EO\(ish\),.*?
	\{"inc", ec_setincl},.*?
(	EO\(ic\),)7??0?
grp 07??m 3220reg p OK ex.c:1709:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	\{"f>", ec_find},
	\{"f<", ec_find},
	\{"f", ec_fuzz},.*(	\{"g!", ec_glob},)
	\{"g", ec_glob},
	EO\(mpt\),8??0?
grp 08??-4m 3220reg p OK ex.c:1709:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	EO\(fr\),
	\{"f\+", ec_find},
	\{"f-", ec_find},.*(	\{"m", ec_mark},)
	\{"q!", ec_quit},
	\{"q", ec_quit},9??0?
grp 09??-7m 3220reg p OK ex.c:1709:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg ex.c:17092sc %? %@2132sc!0?
?0?
%f+ 	\{"g", ec_glob},
	EO\(mpt\),
	\{"m", ec_mark},
	\{"q!", ec_quit},
	\{"q", ec_quit},
	\{"reg\+", ec_regprint},1??0?
1??+2m 41q0?
%f+ 	\{"g", ec_glob},
	EO\(mpt\),
	\{"m", ec_mark},4??0?
4??+2m 4220reg p OK ex.c:1716:a42sc %? %@2152sc!1q0?
grp 1%f+ 	\{"g", ec_glob},.*?
	EO\(mpt\),.*?
(	\{"m", ec_mark},)7??0?
grp 07??m 4220reg p OK ex.c:1716:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	\{"d", ec_delete},
	EO\(grp\),
	\{"g!", ec_glob},.*(	\{"reg", ec_regprint},)
	\{"re", ec_krsset},
	\{"rd", ec_undoredo},8??0?
grp 08??-4m 4220reg p OK ex.c:1716:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	\{"inc", ec_setincl},
	EO\(ic\),
	\{"i", ec_insert},.*(	EO\(rr\),)
	\{"r", ec_read},
	\{"wq!", ec_write},9??0?
grp 09??-7m 4220reg p OK ex.c:1716:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg ex.c:17162sc %? %@2132sc!0?
'\''1-1i static char *nmaps[LEN(kmaps)][256];	/* normal mode key remaps */
static char *imaps[LEN(kmaps)][256];	/* insert mode key remaps */
??!219reg ex.c:0:m12sc %? %@2142sc!0?
'\''2i static void *ec_map(char *loc, char *cmd, char *arg)
{
	char **map = cmd[0] == '\''n'\'' ? nmaps[xkmap] : imaps[xkmap];
	int unmap = !!strchr(cmd, '\''!'\'');
	if (!arg[0]) {
		char msg[64];
		for (int i = 0; i < 256; i++) {
			if (map[i]) {
				snprintf(msg, sizeof(msg), "%c\t%s", i, map[i]);
				ex_print(msg, msg_ft)
			}
		}
		return NULL;
	}
	int c = (unsigned char)arg[0];
	if (unmap) {
		free(map[c]);
		map[c] = NULL;
	} else {
		if (!arg[1])
			return "missing argument";
		free(map[c]);
		map[c] = uc_dup(arg + 1);
	}
	return NULL;
}

int map_read(int mode, int winch)
{
	int c = term_read(winch);
	if (ibuf_cnt != 1)
		return c;
	char **map = mode ? imaps[xkmap] : nmaps[xkmap];
	if (c > 0 && c < 256 && map[c]) {
		term_push(map[c], strlen(map[c]));
		return term_read(winch);
	}
	return c;
}

??!219reg ex.c:622:m22sc %? %@2142sc!0?
'\''3i 	{"im!", ec_map},
	{"im", ec_map},
??!219reg ex.c:1709:m32sc %? %@2142sc!0?
'\''4i 	{"nm!", ec_map},
	{"nm", ec_map},
??!219reg ex.c:1716:m42sc %? %@2142sc!b2%ya 98?0?
%f> 	do \{
		led_printparts\(sb, pre, ps, \*post, postn, poff\);
		len = sb->s_n;
		c = term_read\(TK_CTL\('\''l'\''\)\);
		noredraw:
		switch \(c\) \{
		case TK_CTL\('\''h'\''\):1??0?
1??+3m 11q0?
%f> 		c = term_read\(TK_CTL\('\''l'\''\)\);
		noredraw:
		switch \(c\) \{
		case TK_CTL\('\''h'\''\):2??0?
2??m 1220reg p OK led.c:434:a22sc %? %@2152sc!1q0?
;0fr.,$f> ^		c = term_read\(TK_CTL\('\''l'\''\)\);$3??0?
3??m 1220reg p OK led.c:434:a32sc %? %@2152sc!fr 981qfr 980?
%f> 	do \{
		led_printparts\(sb, pre, ps, \*post, postn, poff\);
		len = sb->s_n;4??0?
4??+3m 1220reg p OK led.c:434:a42sc %? %@2152sc!1q0?
%f> 		noredraw:
		switch \(c\) \{
		case TK_CTL\('\''h'\''\):5??0?
5??-1m 1220reg p OK led.c:434:a52sc %? %@2152sc!1q0?
%f> 	....
	.l.........a....s.,.pre,..s..\*p.....p..... ...f\);
		..... .b..._..
..... ..r._...d..._......'\''..;
.	..r..r...
.	sw......c\)..
.	.a...TK.C.....'\''\):6??0?
6??+3m 1220reg p OK led.c:434:a62sc %? %@2152sc!1q0?
grp 1%f> 	do \{.*?
		led_printparts\(sb, pre, ps, \*post, postn, poff\);.*?
		len = sb->s_n;.*?
(		c = term_read\(TK_CTL\('\''l'\''\)\);)7??0?
grp 07??m 1220reg p OK led.c:434:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	char \*cs;
	int len, c, i;
	sbuf \*reg;.*(			c = 127;)
		case 127:
			if \(len - pre > 0\)8??0?
grp 08??-4m 1220reg p OK led.c:434:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> static int led_line\(sbuf \*sb, int ps, int pre, char \*\*post, int postn, char \*\*postref,
	int ai_max, int \*poff, int \*kmap, ins_state \*is, int orow, int crow, int ctop, int flg\)
\{.*(				sbuf_cut\(sb, led_lastchar\(sb->s \+ pre\) \+ pre\))
			else
				return c;9??0?
grp 09??-7m 1220reg p OK led.c:434:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg led.c:4342sc %? %@2132sc!0?
?'\''1s/term_read\(/map_read(1, /1??1??1q'\''1s/term(_r.*d\()/map\11, /2??2??'\''1220reg p OK led.c:434:s22sc %? %@2162sc!0?
1;2??!219reg led.c:434:m12sc %? %@2142sc!0?
b3%ya 98?0?
%f> 
static int vi_yankbuf\(int winch\)
\{
	int c = term_read\(winch\);
	if \(c == '\''"'\''\)
		return term_read\(0\);
	term_dec\(\)1??0?
1??+3m 11q0?
%f> 	int c = term_read\(winch\);
	if \(c == '\''"'\''\)
		return term_read\(0\);
	term_dec\(\)2??0?
2??m 1220reg p OK vi.c:265:a22sc %? %@2152sc!1q0?
;0fr.,$f> ^	int c = term_read\(winch\);$3??0?
3??m 1220reg p OK vi.c:265:a32sc %? %@2152sc!fr 981qfr 980?
%f> 
static int vi_yankbuf\(int winch\)
\{4??0?
4??+3m 1220reg p OK vi.c:265:a42sc %? %@2152sc!1q0?
%f> 	if \(c == '\''"'\''\)
		return term_read\(0\);
	term_dec\(\)5??0?
5??-1m 1220reg p OK vi.c:265:a52sc %? %@2152sc!1q0?
%f> 
..a.i...........nk.u..i.t.w..c.\)
\{
.... . ......_.....w....\).
....\(.........
..re.... .er.......0.;
..e.._d..\(.6??0?
6??+3m 1220reg p OK vi.c:265:a62sc %? %@2152sc!1q0?
grp 1%f> .*?
static int vi_yankbuf\(int winch\).*?
\{.*?
(	int c = term_read\(winch\);)7??0?
grp 07??m 1220reg p OK vi.c:265:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	int kmap = 0;
	return vi_prompt\(msg, ex_ft, insert, ret, &kmap, mlen\);
}.*(static int vi_prefix\(void\))
\{
	int n = 0;8??0?
grp 08??-7m 1220reg p OK vi.c:265:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	syn_setft\(xb_ft\);
	return sb->s;
}.*(	if \(c >= '\''1'\'' && c <= '\''9'\''\) \{)
		while \(c >= '\''0'\'' && c <= '\''9'\''\) \{
			n = n \* 10 \+ c - '\''0'\'';9??0?
grp 09??-11m 1220reg p OK vi.c:265:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg vi.c:2652sc %? %@2132sc!0?
?0?
%f+ static int vi_prefix\(void\)
\{
	int n = 0;
	int c = term_read\(0\);
	if \(c >= '\''1'\'' && c <= '\''9'\''\) \{
		while \(c >= '\''0'\'' && c <= '\''9'\''\) \{
			n = n \* 10 \+ c - '\''0'\'';1??0?
1??+3m 21q0?
%f+ 	int c = term_read\(0\);
	if \(c >= '\''1'\'' && c <= '\''9'\''\) \{
		while \(c >= '\''0'\'' && c <= '\''9'\''\) \{
			n = n \* 10 \+ c - '\''0'\'';2??0?
2??m 2220reg p OK vi.c:275:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^	int c = term_read\(0\);$3??0?
3??m 2220reg p OK vi.c:275:a32sc %? %@2152sc!fr 981qfr 980?
%f+ static int vi_prefix\(void\)
\{
	int n = 0;4??0?
4??+3m 2220reg p OK vi.c:275:a42sc %? %@2152sc!1q0?
%f+ 	if \(c >= '\''1'\'' && c <= '\''9'\''\) \{
		while \(c >= '\''0'\'' && c <= '\''9'\''\) \{
			n = n \* 10 \+ c - '\''0'\'';5??0?
5??-1m 2220reg p OK vi.c:275:a52sc %? %@2152sc!1q0?
%f+ ...... .....i...ef........
\{
........ ..
	........t.r.....d...;
.i...c..=.'\''..... c..= ......
	...... \(........... c.<. ...\)..
	........\*......c.....'\''.6??0?
6??+3m 2220reg p OK vi.c:275:a62sc %? %@2152sc!1q0?
grp 1%f+ static int vi_prefix\(void\).*?
\{.*?
	int n = 0;.*?
(	int c = term_read\(0\);)7??0?
grp 07??m 2220reg p OK vi.c:275:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	term_dec\(\)
	return -1;
}.*(static int vi_digit\(void\))
\{
	int c = term_read\(0\);8??0?
grp 08??-10m 2220reg p OK vi.c:275:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	int c = term_read\(winch\);
	if \(c == '\''"'\''\)
		return term_read\(0\);.*(	if \(c >= '\''0'\'' && c <= '\''9'\''\))
		return c - '\''0'\'';
	return -1;9??0?
grp 09??-13m 2220reg p OK vi.c:275:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg vi.c:2752sc %? %@2132sc!0?
?0?
%f+ 	if \(c >= '\''1'\'' && c <= '\''9'\''\) \{
		while \(c >= '\''0'\'' && c <= '\''9'\''\) \{
			n = n \* 10 \+ c - '\''0'\'';
			c = term_read\(0\);
		}
	}
	return n;1??0?
1??+3m 31q0?
%f+ 			c = term_read\(0\);
		}
	}
	return n;2??0?
2??m 3220reg p OK vi.c:279:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^			c = term_read\(0\);$3??0?
3??m 3220reg p OK vi.c:279:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 	if \(c >= '\''1'\'' && c <= '\''9'\''\) \{
		while \(c >= '\''0'\'' && c <= '\''9'\''\) \{
			n = n \* 10 \+ c - '\''0'\'';4??0?
4??+3m 3220reg p OK vi.c:279:a42sc %? %@2152sc!1q0?
%f+ 		}
	}
	return n;5??0?
5??-1m 3220reg p OK vi.c:279:a52sc %? %@2152sc!1q0?
%f+ ...... ...... .. ...=..... .
.	w..l.....>. ...... ...........
		.. ....\* .............
.... . ...._....\(...
.	.
	.
.r....n.n.6??0?
6??+3m 3220reg p OK vi.c:279:a62sc %? %@2152sc!1q0?
grp 1%f+ 	if \(c >= '\''1'\'' && c <= '\''9'\''\) \{.*?
		while \(c >= '\''0'\'' && c <= '\''9'\''\) \{.*?
			n = n \* 10 \+ c - '\''0'\'';.*?
(			c = term_read\(0\);)7??0?
grp 07??m 3220reg p OK vi.c:279:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	term_dec\(\)
	return -1;
}.*(static int vi_digit\(void\))
\{
	int c = term_read\(0\);8??0?
grp 08??-6m 3220reg p OK vi.c:279:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	int c = term_read\(winch\);
	if \(c == '\''"'\''\)
		return term_read\(0\);.*(	if \(c >= '\''0'\'' && c <= '\''9'\''\))
		return c - '\''0'\'';
	return -1;9??0?
grp 09??-9m 3220reg p OK vi.c:279:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg vi.c:2792sc %? %@2132sc!0?
?0?
%f+ 
static int vi_digit\(void\)
\{
	int c = term_read\(0\);
	if \(c >= '\''0'\'' && c <= '\''9'\''\)
		return c - '\''0'\'';
	return -1;1??0?
1??+3m 41q0?
%f+ 	int c = term_read\(0\);
	if \(c >= '\''0'\'' && c <= '\''9'\''\)
		return c - '\''0'\'';
	return -1;2??0?
2??m 4220reg p OK vi.c:287:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^	int c = term_read\(0\);$3??0?
3??m 4220reg p OK vi.c:287:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 
static int vi_digit\(void\)
\{4??0?
4??+3m 4220reg p OK vi.c:287:a42sc %? %@2152sc!1q0?
%f+ 	if \(c >= '\''0'\'' && c <= '\''9'\''\)
		return c - '\''0'\'';
	return -1;5??0?
5??-1m 4220reg p OK vi.c:287:a52sc %? %@2152sc!1q0?
%f+ 
.t......nt..i............
\{
..............re..\(...
........= '\''.. &.....=...'\''.
		...... .....0.;
..e.u......6??0?
6??+3m 4220reg p OK vi.c:287:a62sc %? %@2152sc!1q0?
grp 1%f+ .*?
static int vi_digit\(void\).*?
\{.*?
(	int c = term_read\(0\);)7??0?
grp 07??m 4220reg p OK vi.c:287:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	}
	return n;
}.*(static int vi_off2col\(struct lbuf \*lb, int row, int off\))
\{
	char \*ln = lbuf_get\(lb, row\);8??0?
grp 08??-6m 4220reg p OK vi.c:287:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 			n = n \* 10 \+ c - '\''0'\'';
			c = term_read\(0\);
		}.*(static int vi_col2off\(struct lbuf \*lb, int row, int col\))
\{
	char \*ln = lbuf_get\(lb, row\);9??0?
grp 09??-12m 4220reg p OK vi.c:287:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg vi.c:2872sc %? %@2132sc!0?
?0?
%f+ 	int cnt = vi_arg \? vi_arg : 1;
	int mv, i, dir, var;

	mv = term_read\(0\);
	switch \(mv\) \{
	case '\'','\'':
	case '\'';'\'':1??0?
1??+3m 51q0?
%f+ 	mv = term_read\(0\);
	switch \(mv\) \{
	case '\'','\'':
	case '\'';'\'':2??0?
2??m 5220reg p OK vi.c:526:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^	mv = term_read\(0\);$3??0?
3??m 5220reg p OK vi.c:526:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 	int cnt = vi_arg \? vi_arg : 1;
	int mv, i, dir, var;

4??0?
4??+3m 5220reg p OK vi.c:526:a42sc %? %@2152sc!1q0?
%f+ 	switch \(mv\) \{
	case '\'','\'':
	case '\'';'\'':5??0?
5??-1m 5220reg p OK vi.c:526:a52sc %? %@2152sc!1q0?
%f+ ..n. ........_..... .._..g.:.1.
	in..m.. ....... ..r.

.m......r._.e...0..
.s..t....... .
...s.....:
	.... ..'\''.6??0?
6??+3m 5220reg p OK vi.c:526:a62sc %? %@2152sc!1q0?
grp 1%f+ 	int cnt = vi_arg \? vi_arg : 1;.*?
	int mv, i, dir, var;.*?
.*?
(	mv = term_read\(0\);)7??0?
grp 07??m 5220reg p OK vi.c:526:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	static int srow\[5], soff\[5], lkwdcnt;
	static int cadir = 1;
	char \*cs;.*(		if \(!vi_charlast\[0]\))
			return -1;
		if \(mv == '\'','\''\)8??0?
grp 08??-4m 5220reg p OK vi.c:526:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> \{
	static sbuf \*savepath\[5];
	static rset \*bre;.*(			mv = vi_charcmd == '\''F'\'' \|\| vi_charcmd == '\''T'\'')
				\? tolower\(vi_charcmd\) : toupper\(vi_charcmd\);
		else9??0?
grp 09??-7m 5220reg p OK vi.c:526:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg vi.c:5262sc %? %@2132sc!0?
?0?
%f+ 			char \*cmd;
			term_dec\(\)
			re_motion:
			c = term_read\(TK_CTL\('\''l'\''\)\);
			switch \(c\) \{
			case TK_CTL\('\''b'\''\):
				vi_scrollbackward\(MAX\(1, vi_arg\) \* \(xrows - 1\)\);1??0?
1??+3m 61q0?
%f+ 			c = term_read\(TK_CTL\('\''l'\''\)\);
			switch \(c\) \{
			case TK_CTL\('\''b'\''\):
				vi_scrollbackward\(MAX\(1, vi_arg\) \* \(xrows - 1\)\);2??0?
2??m 6220reg p OK vi.c:1222:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^			c = term_read\(TK_CTL\('\''l'\''\)\);$3??0?
3??m 6220reg p OK vi.c:1222:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 			char \*cmd;
			term_dec\(\)
			re_motion:4??0?
4??+3m 6220reg p OK vi.c:1222:a42sc %? %@2152sc!1q0?
%f+ 			switch \(c\) \{
			case TK_CTL\('\''b'\''\):
				vi_scrollbackward\(MAX\(1, vi_arg\) \* \(xrows - 1\)\);5??0?
5??-1m 6220reg p OK vi.c:1222:a52sc %? %@2152sc!1q0?
%f+ .	.......cmd.
.....r.......
....e...t....
.		c.=....m.r.a...K....\(..'\''...
...s..t.h...\).\{
..	.a...T._..L...'\''\):
....v.......l.....a........,...........\(..ow..-.....6??0?
6??+3m 6220reg p OK vi.c:1222:a62sc %? %@2152sc!1q0?
grp 1%f+ 			char \*cmd;.*?
			term_dec\(\).*?
			re_motion:.*?
(			c = term_read\(TK_CTL\('\''l'\''\)\);)7??0?
grp 07??m 6220reg p OK vi.c:1222:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 			xrow = nrow;
			xoff = noff;
		} else if \(mv == 0\) \{.*(			case TK_CTL\('\''f'\''\):)
				vi_scrollforward\(MAX\(1, vi_arg\) \* \(xrows - 1\)\);
				xoff = lbuf_indents\(xb, xrow\);8??0?
grp 08??-7m 6220reg p OK vi.c:1222:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 			if \(\(orow != nrow \|\| ooff != noff\) &&
					strchr\("%'\''`GHML/\?\{}\[]", mv\)\)
				lbuf_mark\(xb, '\''`'\'', orow, ooff\);.*(			case TK_CTL\('\''e'\''\):)
				vi_scrolley = vi_arg \? vi_arg : vi_scrolley;
				vi_scrollforward\(MAX\(1, vi_scrolley\)\);9??0?
grp 09??-12m 6220reg p OK vi.c:1222:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg vi.c:12222sc %? %@2132sc!0?
?0?
%f+ 				break;
			case '\''v'\'':
				vi_mod \|= 2;
				k = term_read\(0\);
				switch \(k\) \{
				case '\''\.'\'':
					while \(vi_arg\) \{1??0?
1??+3m 71q0?
%f+ 				k = term_read\(0\);
				switch \(k\) \{
				case '\''\.'\'':
					while \(vi_arg\) \{2??0?
2??m 7220reg p OK vi.c:1347:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^				k = term_read\(0\);$3??0?
3??m 7220reg p OK vi.c:1347:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 				break;
			case '\''v'\'':
				vi_mod \|= 2;4??0?
4??+3m 7220reg p OK vi.c:1347:a42sc %? %@2152sc!1q0?
%f+ 				switch \(k\) \{
				case '\''\.'\'':
					while \(vi_arg\) \{5??0?
5??-1m 7220reg p OK vi.c:1347:a52sc %? %@2152sc!1q0?
%f+ ...	b.ea..
....... ..'\''.
		..........=...
.	.........m_r.....\);
.....w.tc...k...
..	...s.....:
..	..........i.......6??0?
6??+3m 7220reg p OK vi.c:1347:a62sc %? %@2152sc!1q0?
grp 1%f+ 				break;.*?
			case '\''v'\'':.*?
				vi_mod \|= 2;.*?
(				k = term_read\(0\);)7??0?
grp 07??m 7220reg p OK vi.c:1347:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 					vi_lnnum = vi_arg \? vi_lnnum \| vi_arg : !vi_lnnum;
				vi_lncol = 0;
				vi_mod \|= 1;.*(						term_push\("j", 1\);)
						term_push\(rep_cmd, rep_len\);
						if \(strchr\("iIoOaAsScC", rep_cmd\[0]\)\) \{8??0?
grp 08??-4m 7220reg p OK vi.c:1347:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 				if \(vi_lnnum & vi_arg\)
					vi_lnnum = vi_lnnum & ~vi_arg;
				else.*(							term_push\("0", 1\);)
							if \(noff\)
								vi_argcmd\(noff, '\''l'\''\);9??0?
grp 09??-7m 7220reg p OK vi.c:1347:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg vi.c:13472sc %? %@2132sc!0?
?0?
%f+ 				break;
			case '\''c'\'':
			case '\''d'\'':
				k = term_read\(0\);
				if \(k == '\''i'\''\) \{
					k = term_read\(0\);
					char pairs\[2];1??0?
1??+3m 81q0?
%f+ 				k = term_read\(0\);
				if \(k == '\''i'\''\) \{
					k = term_read\(0\);
					char pairs\[2];2??0?
2??m 8220reg p OK vi.c:1469:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^				k = term_read\(0\);$3??0?
3??m 8220reg p OK vi.c:1469:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 				break;
			case '\''c'\'':
			case '\''d'\'':4??0?
4??+3m 8220reg p OK vi.c:1469:a42sc %? %@2152sc!1q0?
%f+ 				if \(k == '\''i'\''\) \{
					k = term_read\(0\);
					char pairs\[2];5??0?
5??-1m 8220reg p OK vi.c:1469:a52sc %? %@2152sc!1q0?
%f+ 			..r..k.
..	.as. .c.:
...ca.. ....
	..	. ....r..r..d.0\);
.	.	.. ......'\''.....
	...........m_........
...	...a...a.r..2..6??0?
6??+3m 8220reg p OK vi.c:1469:a62sc %? %@2152sc!1q0?
grp 1%f+ 				break;.*?
			case '\''c'\'':.*?
			case '\''d'\'':.*?
(				k = term_read\(0\);)7??0?
grp 07??m 8220reg p OK vi.c:1469:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 					continue;
				} else if \(!xmpt\)
					xmpt = 1;.*(					switch\(k\) \{)
					case '\''\)'\'': case '\''\('\'': pairs\[0]='\''\('\''; pairs\[1]='\''\)'\''; break;
					case '\'']'\'': case '\''\['\'': pairs\[0]='\''\['\''; pairs\[1]='\'']'\''; break;8??0?
grp 08??-4m 8220reg p OK vi.c:1469:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 				free\(ln\);
				if \(xquit\) \{
					xmpt = xmpt \? xmpt : \(xgrec > 1\);.*(					case '\''}'\'': case '\''\{'\'': pairs\[0]='\''\{'\''; pairs\[1]='\''}'\''; break;)
					case '\''>'\'': case '\''<'\'': pairs\[0]='\''<'\''; pairs\[1]='\''>'\''; break;
					default: pairs\[0] = k; pairs\[1] = k; break;9??0?
grp 09??-7m 8220reg p OK vi.c:1469:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg vi.c:14692sc %? %@2132sc!0?
?0?
%f+ 				vi_mod \|= vc_put\(c\);
				break;
			case '\''z'\'':
				k = term_read\(0\);
				switch \(k\) \{
				case '\''\\n'\'':
					xtop = xrow;1??0?
1??+3m 91q0?
%f+ 				k = term_read\(0\);
				switch \(k\) \{
				case '\''\\n'\'':
					xtop = xrow;2??0?
2??m 9220reg p OK vi.c:1590:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^				k = term_read\(0\);$3??0?
3??m 9220reg p OK vi.c:1590:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 				vi_mod \|= vc_put\(c\);
				break;
			case '\''z'\'':4??0?
4??+3m 9220reg p OK vi.c:1590:a42sc %? %@2152sc!1q0?
%f+ 				switch \(k\) \{
				case '\''\\n'\'':
					xtop = xrow;5??0?
5??-1m 9220reg p OK vi.c:1590:a52sc %? %@2152sc!1q0?
%f+ 	.		.......\|. vc.pu.....
	.........
.....s...z'\''.
	..	... ..rm.r...\(...
	..........\(k\)..
		....s.......
......... . .row.6??0?
6??+3m 9220reg p OK vi.c:1590:a62sc %? %@2152sc!1q0?
grp 1%f+ 				vi_mod \|= vc_put\(c\);.*?
				break;.*?
			case '\''z'\'':.*?
(				k = term_read\(0\);)7??0?
grp 07??m 9220reg p OK vi.c:1590:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 				break;
			case '\''p'\'':
			case '\''P'\'':.*(				case '\''\.'\'':)
					xtop = MAX\(0, xrow - xrows / 2\);
					break;8??0?
grp 08??-5m 9220reg p OK vi.c:1590:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 				break;
			case '\''m'\'':
				lbuf_mark\(xb, term_read\(0\), xrow, xoff\);.*(				case '\''-'\'':)
					xtop = MAX\(0, xrow - xrows \+ 1\);
					break;9??0?
grp 09??-8m 9220reg p OK vi.c:1590:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg vi.c:15902sc %? %@2132sc!0?
?0?
%f+ 				vi_mod \|= 1;
				break;
			case '\''g'\'':
				k = term_read\(0\);
				if \(k == '\''g'\''\)
					term_push\("1G", 2\);
				else if \(k == '\''a'\''\) \{1??0?
1??+3m 101q0?
%f+ 				k = term_read\(0\);
				if \(k == '\''g'\''\)
					term_push\("1G", 2\);
				else if \(k == '\''a'\''\) \{2??0?
2??m 10220reg p OK vi.c:1622:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^				k = term_read\(0\);$3??0?
3??m 10220reg p OK vi.c:1622:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 				vi_mod \|= 1;
				break;
			case '\''g'\'':4??0?
4??+3m 10220reg p OK vi.c:1622:a42sc %? %@2152sc!1q0?
%f+ 				if \(k == '\''g'\''\)
					term_push\("1G", 2\);
				else if \(k == '\''a'\''\) \{5??0?
5??-1m 10220reg p OK vi.c:1622:a52sc %? %@2152sc!1q0?
%f+ .	.	............
...	br....
.........g'\'':
...	k ....r._re......
..		...\(...=.....
		....e.._....\(.......\).
...	.ls...f..k .=..... .6??0?
6??+3m 10220reg p OK vi.c:1622:a62sc %? %@2152sc!1q0?
grp 1%f+ 				vi_mod \|= 1;.*?
				break;.*?
			case '\''g'\'':.*?
(				k = term_read\(0\);)7??0?
grp 07??m 10220reg p OK vi.c:1622:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 					xkmap_alt = k - '\''0'\'';
					break;
				}.*(					vi_tsm = 1;)
					goto status;
				} else if \(k == '\''w'\''\) \{8??0?
grp 08??-4m 10220reg p OK vi.c:1622:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 					break;
				case '\''1'\'':
				case '\''2'\'':.*(					preserve\(int, xgrp, xgrp = 2;\))
					preserve\(int, xvis, xvis = 1;\)
					n = vi_arg \? vi_arg : 80;9??0?
grp 09??-7m 10220reg p OK vi.c:1622:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg vi.c:16222sc %? %@2132sc!0?
?0?
%f+ 					continue;
				break;
			case '\''Z'\'':
				k = term_read\(0\);
				if \(TK_INT\(k\)\)
					continue;
				if \(k == '\''Z'\''\) \{1??0?
1??+3m 111q0?
%f+ 				k = term_read\(0\);
				if \(TK_INT\(k\)\)
					continue;
				if \(k == '\''Z'\''\) \{2??0?
2??m 11220reg p OK vi.c:1694:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^				k = term_read\(0\);$3??0?
3??m 11220reg p OK vi.c:1694:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 					continue;
				break;
			case '\''Z'\'':4??0?
4??+3m 11220reg p OK vi.c:1694:a42sc %? %@2152sc!1q0?
%f+ 				if \(TK_INT\(k\)\)
					continue;
				if \(k == '\''Z'\''\) \{5??0?
5??-1m 11220reg p OK vi.c:1694:a52sc %? %@2152sc!1q0?
%f+ .	...c.....ue.
....b.e...
......e.....
..		....t.rm.........
.......\(.K.......\)
..		..........
.		.i...k ....... .6??0?
6??+3m 11220reg p OK vi.c:1694:a62sc %? %@2152sc!1q0?
grp 1%f+ 					continue;.*?
				break;.*?
			case '\''Z'\'':.*?
(				k = term_read\(0\);)7??0?
grp 07??m 11220reg p OK vi.c:1694:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 				led_modeswap\(\);
				vi_mod \|= 1;
				if \(xquit\).*(					ex_exec\("x"\);)
					continue;
				}8??0?
grp 08??-4m 11220reg p OK vi.c:1694:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 			case '\''Q'\'':
				term_pos\(xrow - xtop, 0\);
				xleft = vi_arg \? xleft : 0;.*(				xquit = vi_arg \? -vi_arg \* 256 - 257 : 1;)
				if \(k == '\''z'\''\)
					term_push\("\\n", 1\);9??0?
grp 09??-7m 11220reg p OK vi.c:1694:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg vi.c:16942sc %? %@2132sc!0?
?'\''1s/term_read\(/map_read(0, /1??1??1q'\''1s/term(_.*\()/map\10, /2??2??'\''1220reg p OK vi.c:265:s22sc %? %@2162sc!0?
1;2??!219reg vi.c:265:m12sc %? %@2142sc!0?
?'\''2s/term_read\(/map_read(0, /1??1??1q'\''2s/term(_.*0)/map\1, 0/2??2??'\''2220reg p OK vi.c:275:s22sc %? %@2162sc!0?
1;2??!219reg vi.c:275:m22sc %? %@2142sc!0?
?'\''3s/term_read\(/map_read(0, /1??1??1q'\''3s/term(_.*0)/map\1, 0/2??2??'\''3220reg p OK vi.c:279:s22sc %? %@2162sc!0?
1;2??!219reg vi.c:279:m32sc %? %@2142sc!0?
?'\''4s/term_read\(/map_read(0, /1??1??1q'\''4s/term(_.*0)/map\1, 0/2??2??'\''4220reg p OK vi.c:287:s22sc %? %@2162sc!0?
1;2??!219reg vi.c:287:m42sc %? %@2142sc!0?
'\''5c 	mv = map_read(0, 0);
??!219reg vi.c:526:m52sc %? %@2142sc!0?
?'\''6s/term_read\(/map_read(0, /1??1??1q'\''6s/term(_r.*d\()/map\10, /2??2??'\''6220reg p OK vi.c:1222:s22sc %? %@2162sc!0?
1;2??!219reg vi.c:1222:m62sc %? %@2142sc!0?
?'\''7s/term_read\(/map_read(0, /1??1??1q'\''7s/term(_.*0)/map\1, 0/2??2??'\''7220reg p OK vi.c:1347:s22sc %? %@2162sc!0?
1;2??!219reg vi.c:1347:m72sc %? %@2142sc!0?
?'\''8s/term_read\(/map_read(0, /1??1??1q'\''8s/term(_.*0)/map\1, 0/2??2??'\''8220reg p OK vi.c:1469:s22sc %? %@2162sc!0?
1;2??!219reg vi.c:1469:m82sc %? %@2142sc!0?
?'\''9s/term_read\(/map_read(0, /1??1??1q'\''9s/term(_.*0)/map\1, 0/2??2??'\''9220reg p OK vi.c:1590:s22sc %? %@2162sc!0?
1;2??!219reg vi.c:1590:m92sc %? %@2142sc!0?
?'\''10s/term_read\(/map_read(0, /1??1??1q'\''10s/term(_.*0)/map\1, 0/2??2??'\''10220reg p OK vi.c:1622:s22sc %? %@2162sc!0?
1;2??!219reg vi.c:1622:m102sc %? %@2142sc!0?
?'\''11s/term_read\(/map_read(0, /1??1??1q'\''11s/term(_.*0)/map\1, 0/2??2??'\''11220reg p OK vi.c:1694:s22sc %? %@2162sc!0?
1;2??!219reg vi.c:1694:m112sc %? %@2142sc!0?
b4%ya 98?0?
%f> #define bufs_switchwft\(idx\) \\
\{ if \(&bufs\[idx] != ex_buf\) \{ bufs_switch\(idx\); syn_setft\(xb_ft\); } } \\

void bufs_switch\(int idx\);
void temp_open\(int i, char \*name, char \*ft\);
void temp_switch\(int i, int swap\);1??0?
1??+2m 11q0?
%f> #define bufs_switchwft\(idx\) \\
\{ if \(&bufs\[idx] != ex_buf\) \{ bufs_switch\(idx\); syn_setft\(xb_ft\); } } \\

4??0?
4??+2m 1220reg p OK vi.h:476:a42sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	buf->off = xoff; \\
	buf->top = xtop; \\
	buf->td = xtd; \\.*(void temp_write\(int i, char \*str\);)
void temp_pos\(int i, int row, int off, int top\);
void ex\(void\);8??0?
grp 08??-4m 1220reg p OK vi.h:476:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	xoff = buf->off; \\
	xtop = buf->top; \\
	xtd = buf->td; \\.*(void \*ex_exec\(const char \*ln\);)
#define ex_command\(ln\) \{ ex_exec\(ln\); ex_regput\('\'':'\'', ln, 0\); }
void ex_cprint\(char \*line, char \*ft, int r, int c, int left, int flg\);9??0?
grp 09??-7m 1220reg p OK vi.h:476:a92sc %? %@2152sc!'\''00?
1;4;8;9??!219reg vi.h:4762sc %? %@2132sc!0?
'\''1i int map_read(int mode, int winch);
??!219reg vi.h:476:m12sc %? %@2142sc!vis 2b0wb1wb2wb3wb4w2q' > "$P2VIF"
EXINIT='%ya 97:? %@97' $VI -e 'conf.c' 'ex.c' 'led.c' 'vi.c' 'vi.h' "$P2VIF"

if [ $# -gt 0 ]; then
    export P2VI_PATCH="$P2VI_PATCH ${0##*/}"
    next=$1
    shift
    case $next in /*|./*|../*) "$next" "$@" ;; *) "./$next" "$@" ;; esac
fi

exit 0
=== PATCH2VI PATCH ===
diff --git a/conf.c b/conf.c
index ad9395c9..3324eff9 100644
--- a/conf.c
+++ b/conf.c
@@ -298,7 +298,7 @@ return|select|switch|type|var))\\>", A(GR1, BL1 | SYN_BD, YE1)},
 (?:([,;]#?)[ \t]*((?:\\|(?:[^|\\\\]|\\\\.?)*\\|?[ \t]*)*(?:(?:<(?:[^<\\\\]|\\\\.?)*<?|>(?:[^>\\\\]|\\\\.?)*>?)|\
 (?:'[0-9]+)|([.$]|[0-9 \t]*)?))(?:([-*-+/%])[ \t]*([0-9]+)[ \t]*)*(?:[ \t]*\\|(?:[^|\\\\]|\\\\.?)*\\|?)*[ \t]*)*)\
 ((pac|pr|ai|ish|err|fr|ic|grp|mpt|rr|shape|seq|ts|td|order|hl[lwpr]?|left|lim|led|vis)\
-|[@&!dmj]|=\\?{0,1}|\\?{1,2}[?!]?|b[psx]?|p[uh]?|ac|e[f!]?!?|f[-+><tdp]?|inc|i|sc!?|\
+|[@&!dmj]|=\\?{0,1}|\\?{1,2}[?!]?|b[psx]?|p[uh]?|ac|e[f!]?!?|f[-+><tdp]?|inc|im!?|i|sc!?|nm!?|\
 (?:g!?|s)[ \t]?(.)?|q!?|reg?\\+?|rd?|w(?:q!|[q!])?|u[czbd]|x!?|ya[!+]?|cm!?|cd?)?",
 		A(BL1 | SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1)},
 	{ex_ft, "\\\\(.)", A(AY1 | SYN_BD, YE)},
diff --git a/ex.c b/ex.c
index f8505153..c4b1e3aa 100644
--- a/ex.c
+++ b/ex.c
@@ -1,3 +1,5 @@
+static char *nmaps[LEN(kmaps)][256];	/* normal mode key remaps */
+static char *imaps[LEN(kmaps)][256];	/* insert mode key remaps */
 int xleft;			/* the first visible column */
 int xvis;			/* startup flags */
 int xai = 1;			/* autoindent option */
@@ -620,6 +622,46 @@ static void *ec_find(char *loc, char *cmd, char *arg)
 	return NULL;
 }
 
+static void *ec_map(char *loc, char *cmd, char *arg)
+{
+	char **map = cmd[0] == 'n' ? nmaps[xkmap] : imaps[xkmap];
+	int unmap = !!strchr(cmd, '!');
+	if (!arg[0]) {
+		char msg[64];
+		for (int i = 0; i < 256; i++) {
+			if (map[i]) {
+				snprintf(msg, sizeof(msg), "%c\t%s", i, map[i]);
+				ex_print(msg, msg_ft)
+			}
+		}
+		return NULL;
+	}
+	int c = (unsigned char)arg[0];
+	if (unmap) {
+		free(map[c]);
+		map[c] = NULL;
+	} else {
+		if (!arg[1])
+			return "missing argument";
+		free(map[c]);
+		map[c] = uc_dup(arg + 1);
+	}
+	return NULL;
+}
+
+int map_read(int mode, int winch)
+{
+	int c = term_read(winch);
+	if (ibuf_cnt != 1)
+		return c;
+	char **map = mode ? imaps[xkmap] : nmaps[xkmap];
+	if (c > 0 && c < 256 && map[c]) {
+		term_push(map[c], strlen(map[c]));
+		return term_read(winch);
+	}
+	return c;
+}
+
 static void *ec_buffer(char *loc, char *cmd, char *arg)
 {
 	int n = atoi(arg);
@@ -1707,6 +1749,8 @@ static struct excmd {
 	EO(ish),
 	{"inc", ec_setincl},
 	EO(ic),
+	{"im!", ec_map},
+	{"im", ec_map},
 	{"i", ec_insert},
 	{"d", ec_delete},
 	EO(grp),
@@ -1714,6 +1758,8 @@ static struct excmd {
 	{"g", ec_glob},
 	EO(mpt),
 	{"m", ec_mark},
+	{"nm!", ec_map},
+	{"nm", ec_map},
 	{"q!", ec_quit},
 	{"q", ec_quit},
 	{"reg+", ec_regprint},
diff --git a/led.c b/led.c
index a38f7a06..a097fb1d 100644
--- a/led.c
+++ b/led.c
@@ -431,7 +431,7 @@ static int led_line(sbuf *sb, int ps, int pre, char **post, int postn, char **po
 	do {
 		led_printparts(sb, pre, ps, *post, postn, poff);
 		len = sb->s_n;
-		c = term_read(TK_CTL('l'));
+		c = map_read(1, TK_CTL('l'));
 		noredraw:
 		switch (c) {
 		case TK_CTL('h'):
diff --git a/vi.c b/vi.c
index 2f4ccc2b..ba517a6e 100644
--- a/vi.c
+++ b/vi.c
@@ -262,7 +262,7 @@ static char *vi_enprompt(char *msg, char *insert, int *ret, int *mlen)
 
 static int vi_yankbuf(int winch)
 {
-	int c = term_read(winch);
+	int c = map_read(0, winch);
 	if (c == '"')
 		return term_read(0);
 	term_dec()
@@ -272,11 +272,11 @@ static int vi_yankbuf(int winch)
 static int vi_prefix(void)
 {
 	int n = 0;
-	int c = term_read(0);
+	int c = map_read(0, 0);
 	if (c >= '1' && c <= '9') {
 		while (c >= '0' && c <= '9') {
 			n = n * 10 + c - '0';
-			c = term_read(0);
+			c = map_read(0, 0);
 		}
 	}
 	return n;
@@ -284,7 +284,7 @@ static int vi_prefix(void)
 
 static int vi_digit(void)
 {
-	int c = term_read(0);
+	int c = map_read(0, 0);
 	if (c >= '0' && c <= '9')
 		return c - '0';
 	return -1;
@@ -523,7 +523,7 @@ static int vi_region(int cmd, int *row, int *off)
 	int cnt = vi_arg ? vi_arg : 1;
 	int mv, i, dir, var;
 
-	mv = term_read(0);
+	mv = map_read(0, 0);
 	switch (mv) {
 	case ',':
 	case ';':
@@ -1219,7 +1219,7 @@ void vi(int init)
 			char *cmd;
 			term_dec()
 			re_motion:
-			c = term_read(TK_CTL('l'));
+			c = map_read(0, TK_CTL('l'));
 			switch (c) {
 			case TK_CTL('b'):
 				vi_scrollbackward(MAX(1, vi_arg) * (xrows - 1));
@@ -1344,7 +1344,7 @@ void vi(int init)
 				break;
 			case 'v':
 				vi_mod |= 2;
-				k = term_read(0);
+				k = map_read(0, 0);
 				switch (k) {
 				case '.':
 					while (vi_arg) {
@@ -1466,7 +1466,7 @@ void vi(int init)
 				break;
 			case 'c':
 			case 'd':
-				k = term_read(0);
+				k = map_read(0, 0);
 				if (k == 'i') {
 					k = term_read(0);
 					char pairs[2];
@@ -1587,7 +1587,7 @@ void vi(int init)
 				vi_mod |= vc_put(c);
 				break;
 			case 'z':
-				k = term_read(0);
+				k = map_read(0, 0);
 				switch (k) {
 				case '\n':
 					xtop = xrow;
@@ -1619,7 +1619,7 @@ void vi(int init)
 				vi_mod |= 1;
 				break;
 			case 'g':
-				k = term_read(0);
+				k = map_read(0, 0);
 				if (k == 'g')
 					term_push("1G", 2);
 				else if (k == 'a') {
@@ -1691,7 +1691,7 @@ void vi(int init)
 					continue;
 				break;
 			case 'Z':
-				k = term_read(0);
+				k = map_read(0, 0);
 				if (TK_INT(k))
 					continue;
 				if (k == 'Z') {
diff --git a/vi.h b/vi.h
index 0bb77c0b..a0b9a549 100644
--- a/vi.h
+++ b/vi.h
@@ -474,6 +474,7 @@ extern struct buf *ex_pbuf;
 #define bufs_switchwft(idx) \
 { if (&bufs[idx] != ex_buf) { bufs_switch(idx); syn_setft(xb_ft); } } \
 
+int map_read(int mode, int winch);
 void bufs_switch(int idx);
 void temp_open(int i, char *name, char *ft);
 void temp_switch(int i, int swap);
