#!/bin/sh

p2v_usage() {
	cat <<'EOF'
Patch2vi utility functions

Source on demand:   . ./patch2vi.sh
Then call:          patch2vi_wrapper [flag] input.patch [output.sh]
                    gitdiff2vi [flags] [output.sh]
                    regen input.sh
                    rebuild target.sh
                    extract_patches [file.sh]
                    extract_compats [file.sh]
                    view_patch file.sh
                    compat_order [README]
                    compat_check [max]
                    recompat target.sh [origin.sh]
                    reindex [file.sh | 1]
                    discard_compats [file.sh]
                    run_patches [1]
                    regen_all [1]
                    rebuild_all [1]

Set $P2VI to point to patch2vi binary.
Functions look for the binary as ./patch2vi, then as patch2vi on $PATH.
EOF
}

# $0 is this file's path only when it was run, never when it was sourced.
case "$0" in
*patch2vi.sh)	p2v_usage >&2; exit 1 ;;
esac

P2VI=${P2VI:-./patch2vi}
P2VITMP=/tmp/p2vi.tmp.$$
# Whitespace IFS: a sourced shell may have set IFS to anything, so every
# subshell below that splits a list restores this first.
P2VIFS=' 	
'
# awk prelude: lbl() joins the src= fields of a compat header into its label.
P2VLBL='
function lbl(  i, s) {
	for (i = 1; i <= NF; i++)
		if (substr($i, 1, 4) == "src=")
			s = s (s == "" ? "" : " ") substr($i, 5)
	return s
}'

# --- helpers -----------------------------------------------------------------

# Is $1 one of our generated scripts?
p2v_ours() { head -2 "$1" | grep -q "Generated by patch2vi"; }

# Every generated script in the current directory, one per line.
p2v_scripts() {
	for s in *.sh
	do
		p2v_ours "$s" && printf '%s\n' "$s"
	done
	return 0
}

# What a bulk command works on: $1 alone, or every script when $1 is empty.
# A named file that is not ours fails.
p2v_list() {
	case "$1" in
	"")	p2v_scripts ;;
	*)	p2v_ours "$1" && printf '%s\n' "$1" ;;
	esac
}

# -C, -E and -I all open the editor: led keeps it from drawing, :q from
# stopping in it. A caller's own P2VI_EX wins.
p2v_batch() { export P2VI_EX="${P2VI_EX:-led 0:q}"; }

# Replace a script's embedded patch (everything past the marker) with $2.
# Its own temp file, since $2 is often $P2VITMP.
p2v_splice() {
	sed '/^=== PATCH2VI PATCH ===$/q' "$1" > "$P2VITMP.splice"
	cat "$2" >> "$P2VITMP.splice"
	cp "$P2VITMP.splice" "$1"
	rm -f "$P2VITMP.splice"
	chmod +x "$1"	# written by sed, not by patch2vi's own -o
}

# Untracked files are invisible to git diff, so they are staged as
# intent-to-add before a diff and dropped again after it.
p2v_newfiles() { git ls-files --others --exclude-standard; }
p2v_addnew() {
	[ -n "$1" ] && printf '%s\n' "$1" | xargs git add -N
	return 0
}
p2v_dropnew() {
	if [ -n "$1" ]; then
		printf '%s\n' "$1" | xargs git reset -q HEAD --
		printf '%s\n' "$1" | xargs rm -f
	fi
	return 0
}

# git $@ over the sources a patch may touch: everything but our own scripts and
# the files extracted from them. The pathspec is spelled out as real arguments
# rather than word-split out of a variable, which needs a space in IFS and
# quietly collapses into one nonsense pathspec where there is none.
p2v_git_src() {
	git "$@" -- ':!*.sh' ':!*.patch' ':!compat'
}

# The tree back to HEAD with the scripts in scope, sparing $1 and everything
# extracted out of them.
p2v_checkout_but() {
	git checkout -- . ":!$1" ':!*.patch' ':!compat' >/dev/null 2>&1
}

# Undo a script run: sources back to HEAD, leavings dropped. With $1 the
# scripts go back too, all but $1 itself - a patch may edit a .sh of its own,
# cbuild.sh say, and a run that leaves one behind hands the next caller a dirty
# tree, which rebuild reads as a body. Without it every script is spared, so
# one this very run rewrote is not reverted along with the sources.
p2v_restore() {
	new=$(p2v_newfiles | grep -v '^compat/' || true)
	if [ -n "$1" ]; then
		p2v_checkout_but "$1"
	else
		p2v_git_src checkout >/dev/null 2>&1
	fi
	p2v_dropnew "$new"
}

# patch2vi opens /dev/tty for its editor, which a pipeline or a CI job does not
# have; script(1) then supplies one. Paths with spaces do not survive this.
p2v_tty() {
	# The probe runs in a subshell: a redirection that fails is fatal to a
	# non-interactive POSIX shell, and a bare "{ : >/dev/tty; }" then takes
	# the whole script down instead of falling through to the fallback.
	if ( : >/dev/tty ) 2>/dev/null; then
		"$@"
	else	# "$*" joins on the first character of IFS, a space only if the
		# shell this was sourced into left IFS alone
		( IFS=' '; script -qec "$*" /dev/null )
	fi
}

# The binary: one already here wins, one installed in $PATH is the fallback -
# command -v does the looking, which is what makes this script usable from a
# tree with no patch2vi of its own. No subshell: the $P2VI resolved here has to
# reach the caller, export only runs downhill.
p2v_getbin() {
	[ -x $P2VI ] && return 0
	if p2v_bin=$(command -v "${P2VI##*/}") && [ -x "$p2v_bin" ]
	then	P2VI=$p2v_bin
		return 0
	fi
	echo "NO BINARY: no $P2VI and no ${P2VI##*/} on \$PATH" >&2
	return 1
}

# Write the working tree's sources to a tree object, the index left alone.
# Snapshots taken this way diff with git diff-tree, so files a run adds or
# removes come out right, unlike a diff of two copied directories.
p2v_snaptree() (
	export GIT_INDEX_FILE="$P2VITMP.idx"
	rm -f "$GIT_INDEX_FILE"
	p2v_git_src add -A
	git write-tree
	rm -f "$GIT_INDEX_FILE"
)

# The diff a just-run script produced, into $1, tree restored afterwards.
p2v_snapdiff() {
	new=$(p2v_newfiles)
	p2v_addnew "$new"
	git diff > "$1"
	git checkout . >/dev/null 2>&1
	p2v_dropnew "$new"
}

# --- compat blocks -----------------------------------------------------------

# A block records one src= field per origin, so its label is those fields in
# storage order, space joined: no origin path may hold a space, here or in any
# parser a block passes through, or the label cannot be taken apart again. It
# is otherwise kept whole - it names the stack a block was derived against, and
# two blocks belong together only when their whole stacks match.

# The label of every compat block $1 carries, one per line, in storage order.
p2v_compatsrc() {
	awk "$P2VLBL"'
	/^=== PATCH2VI COMPAT /	{ print lbl() }
	' "$1"
}

# Every distinct origin the compat blocks of $1 name, one per line.
p2v_origins() { p2v_compatsrc "$1" | tr ' ' '\n' | grep -v '^$' | sort -u; }

# First origin of label $1 into p2v_one, the rest into p2v_rest. Split by hand,
# since word splitting needs a space in IFS and a sourced shell may have any.
p2v_shift() {
	p2v_one=${1%% *}
	case $1 in
	*\ *)	p2v_rest=${1#* } ;;
	*)	p2v_rest= ;;
	esac
}

# Run "$2..." once per origin of label $1, the origin appended, in stored
# order; the first failure is the result.
p2v_eachorigin() {
	p2v_lbl="$1"
	shift
	while [ -n "$p2v_lbl" ]
	do
		p2v_shift "$p2v_lbl"
		p2v_lbl=$p2v_rest
		[ -n "$p2v_one" ] || continue
		"$@" "$p2v_one" || return $?
	done
}

# Run the origins of label $1 and then script $2, as one chain: the first is
# invoked and the rest are its arguments, so each hands the next its own name in
# $P2VI_PATCH and $2 sees exactly the origins that ran before it.
#
# One script at a time would not do. The set would stay empty at $2, so not only
# would its compat blocks stay cold - the host body's quit chain is relaxed only
# when an origin is present, so $2 would assert at its first collision and write
# nothing at all. An argument naming a script outside the tree has to be
# absolute, which is where $P2VITMP puts one.
p2v_runchain() (
	IFS=$P2VIFS
	set -- $1 "$2"
	next=$1
	shift
	case $next in
	/*)	"$next" "$@" ;;
	*)	"./$next" "$@" ;;
	esac
)

# Derive a compat block for label $1 onto target $2 from patch $3: one -C per
# origin, in stored order, since that is the order its probes were derived in.
# The first carries the -o, exactly as a single origin always did.
p2v_co() {
	p2v_rest="$1"		# saved before set -- clears the positionals
	p2v_tgt="$2"
	p2v_pat="$3"
	set --
	p2v_flag=-oC
	while [ -n "$p2v_rest" ]
	do
		p2v_shift "$p2v_rest"
		[ -n "$p2v_one" ] || continue
		set -- "$@" "$p2v_flag" "$p2v_one"
		p2v_flag=-C
	done
	p2v_tty $P2VI "$@" "$p2v_tgt" "$p2v_pat"
}

# $1 without the stored compat blocks whose label is $2, on stdout; with no $2,
# without any of them. A block is only the record of a resolution: the ex
# commands that carry it out sit in the emitted body, so a stripped script has
# to be re-emitted (p2v_reemit) before it runs as one that never had them.
p2v_stripcompat() {
	awk -v src="$2" "$P2VLBL"'
	/^=== PATCH2VI COMPAT /	{ if (src == "" || lbl() == src) skip = 1 }
	!skip			{ print }
	/^=== END COMPAT ===$/	{ skip = 0 }
	' "$1"
}

# Split the compat blocks of $1 into directory $2: block N's verbatim
# === COMPAT PATCH === diff lands in $2/N.patch, and one "N <label>" line per
# block goes to stdout, in storage order. A block with an empty diff still gets
# its (empty) file, so the numbering never drifts from the stored order. Read
# the listing whole before opening a file: a block is announced before it is
# filled.
p2v_splitcompat() {
	awk -v dir="$2" "$P2VLBL"'
	/^=== PATCH2VI COMPAT /	{
		n++
		out = dir "/" n ".patch"
		printf "" > out
		print n " " lbl()
		incb = 1
		inpat = 0
		next
	}
	incb && $0 == "=== COMPAT PATCH ===" { inpat = 1; next }
	incb && inpat && $0 == "=== END ===" { inpat = 0; next }
	incb && $0 == "=== END COMPAT ===" { incb = 0; next }
	inpat			{ print > out }
	' "$1"
}

# --- conversion --------------------------------------------------------------

# Re-emit $1 in place from what it already carries: its embedded patch and its
# stored compat blocks both, no editor and no tree state involved. The write is
# atomic, so patch2vi reading the file it is about to replace is safe. This is
# what a script stripped of blocks (p2v_stripcompat) needs before it runs as
# one that never had them.
p2v_reemit() { $P2VI -o "$1" "$1"; }

# Convert a .patch file to a nextvi shell script. The leading flag is
# optional (relative anchors are patch2vi's default; -a buys absolute line
# numbers) and is forwarded untouched.
# Usage: patch2vi_wrapper [flag] input.patch [output.sh]
patch2vi_wrapper() {
	p2v_fl=
	case $1 in
	-*)	p2v_fl=$1
		shift
		;;
	esac
	if [ -z "$1" ]; then
		echo "Usage: patch2vi_wrapper [flag] input.patch [output.sh]" >&2
		return 1
	fi
	p2v_getbin || return 1
	if [ -n "$2" ]; then
		output="$2"
	else
		case "$1" in
		*.patch)	output="${1%.patch}.sh" ;;
		*)		output="$1.sh" ;;
		esac
	fi
	$P2VI $p2v_fl -o "$output" "$1"	# -o already makes it executable
	echo "Generated: $output"
}

# Run "$@" (from $2 on) with the tree back at HEAD, so patch2vi validates its
# fuzz against the original sources rather than against an already patched tree.
# New files (which have no pre-patch original) and $1 itself stay. Intent-to-add
# (git add -N) entries break both stash push and pop, so they are unstaged
# around the stash. The tree is restored even when the command fails, whose
# status is what this returns.
p2v_stashed_run() (
	IFS=$P2VIFS	# $ita and $stashed below are split on it
	keep="$1"
	shift
	ita=$(git diff --name-only --diff-filter=A -- ":!$keep")
	[ -n "$ita" ] && git reset -q -- $ita
	stashed=$(git diff --name-only --diff-filter=MD -- ":!$keep")
	[ -n "$stashed" ] && git stash push -q -- $stashed
	"$@"
	st=$?
	[ -n "$stashed" ] && git stash pop -q
	[ -n "$ita" ] && git add -N -- $ita
	return $st
)

# Regenerate a script from the patch it already carries, with only that patch
# applied. -o rewrites it in place, atomically. The leading flag is optional
# and forwarded untouched (relative anchors are patch2vi's default).
patch2vi_stashed() {
	p2v_fl=
	case $1 in
	-*)	p2v_fl=$1
		shift
		;;
	esac
	p2v_stashed_run "$1" $P2VI $p2v_fl -o "$1" "$1"
	echo "Generated: $1" >&2
}

# Convert the current git diff to a nextvi shell script, to stdout when the
# output file is omitted.
#
# An output that is already one of our scripts keeps everything it stores - its
# compat blocks above all - and only its embedded patch is replaced; anything
# else is written from the bare diff and converted from that. Dropping the
# blocks is discard_compats' job, never a side effect of a regeneration.
# Usage: gitdiff2vi [flags] [output.sh]
gitdiff2vi() {
	p2v_getbin || return 1
	p2v_fl=
	case $1 in
	-*)	p2v_fl=$1
		shift
		;;
	esac
	if [ -z "$1" ]; then
		git diff | $P2VI $p2v_fl
		return
	fi
	git diff -- ":!$1" > "$P2VITMP"
	if [ -f "$1" ] && p2v_ours "$1"; then
		p2v_splice "$1" "$P2VITMP"
	else	# -o keeps the mode of a file that already exists, so the
		# executable bit has to be set here
		cp "$P2VITMP" "$1"
		chmod +x "$1"
	fi
	rm -f "$P2VITMP"
	patch2vi_stashed $p2v_fl "$1"
}

# Regenerate a script from the whole working tree, in place. Everything is
# staged first, so files the tree gained are in the diff too: that is what this
# has over gitdiff2vi, whose plain git diff cannot see an untracked file.
# Usage: regen input.sh
regen() {
	if [ -z "$1" ]; then
		echo "Usage: regen input.sh" >&2
		return 1
	fi
	p2v_getbin || return 1
	git add .
	# the script's own diff is not part of the patch it carries
	git diff --staged -- ":!$1" > "$P2VITMP"
	git reset -q
	p2v_splice "$1" "$P2VITMP"
	rm -f "$P2VITMP"
	patch2vi_stashed "$1"
}

# The -C pass of rebuild: every saved block back onto the script, in storage
# order, one call each (a block is one diff, and one call stores one block, so
# the count comes out as it went in; a block gated on a stack of origins takes
# one -C per origin within that one call). Run with the tree at HEAD.
#
# Deriving a block replays the origin, and a replay writes the sections it edits
# out, so the tree does not come back clean on its own. The sources go back to
# HEAD afterwards and the files the pass brought into being are dropped - only
# those, the ones already there are the caller's. This has to happen before the
# caller's stash comes home, or it lands on the replay's leavings.
# Usage: p2v_reapply workdir target.sh
p2v_reapply() {
	p2v_newfiles | sort > "$1/pre"
	p2v_st=0
	# The listing is read off its own descriptor, since a -C call inherits
	# this loop's stdin and the editor it hands over to reads the rest of
	# the blocks away - they would then never be re-applied, silently.
	while read -r line <&3
	do
		n=${line%% *}
		origin=${line#* }	# the label, spaces and all
		[ "$origin" = "$line" ] && origin=
		if [ -z "$origin" ]; then
			printf "%s\n" "NO ORIGIN: block $n of $2, cannot re-derive" >&2
			p2v_st=1
			break
		fi
		if [ ! -s "$1/$n.patch" ]; then
			printf "%s\n" "EMPTY: block $n of $2 from $origin, dropped" >&2
			continue
		fi
		printf "%s\n" "COMPAT: $2 <- $origin (block $n)" >&2
		# The stored diff goes back as a script, not as a diff: -C
		# matches a pre-applied diff's image exactly, context and all,
		# and an origin that drifted under context the block only
		# borrowed then kills a block that still applies perfectly well.
		# A generated script's anchors search for their text instead, so
		# the same drift is absorbed and what -C stores is the diff of
		# where the block actually landed.
		$P2VI "$1/$n.patch" > "$1/$n.sh"
		chmod +x "$1/$n.sh"
		if ! p2v_co "$origin" "$2" "$1/$n.sh"; then
			p2v_st=1
			break
		fi
	done 3< "$1/blocks"
	# the scripts are in scope too, a replayed patch may edit one; the
	# target is not, it is what this pass is rewriting
	p2v_checkout_but "$2"
	p2v_newfiles | sort > "$1/post"
	left=$(comm -13 "$1/pre" "$1/post")
	[ -n "$left" ] && printf '%s\n' "$left" | xargs rm -f
	return $p2v_st
}

# Regenerate a script whole: its base patch and its compat blocks both.
#
# regen refreshes the base patch and re-emits the body, but the compat blocks
# come back out of storage as they went in, and a block's diff was taken against
# the base as it read then: its context, and the anchors emitted from it, name
# text the base may since have moved or rewritten. So the blocks come off, the
# base is regenerated without them, and each block's stored === COMPAT PATCH ===
# diff goes back to -C, which re-derives it against the base that now exists.
# The stored diff is verbatim, which is what lets it come back out as the patch
# its author handed in.
#
# A block that will not replay at all is a hard error, and then the script is
# put back the way it was: resolve that collision by hand and hand the result
# to -C instead.
#
# The working tree is the script's body, as it is for regen, and both states it
# can be in mean something. A clean tree has none to offer, so the script
# supplies its own: it is run, read back, and put back afterwards, and out comes
# the same script re-aimed at today's sources. A dirty tree is taken as it
# stands - the caller's edits become the body - and is left alone at the end.
# Only the target's own effect belongs there: an origin applied to the tree, or
# a block that fired in it, lands in the base patch as if the script had made it.
# Usage: rebuild target.sh
rebuild() (
	if [ -z "$1" ]; then
		echo "Usage: rebuild target.sh" >&2
		return 1
	fi
	target="$1"
	p2v_ours "$target" || return 1
	p2v_getbin || return 1
	p2v_batch
	work="$P2VITMP.rebuild"
	rm -rf "$work"
	mkdir -p "$work"
	cp "$target" "$work/orig.sh"
	# untracked files count: regen stages everything before it diffs
	own=
	if [ -z "$(git status --porcelain)" ]; then
		# the tree regen reads the base out of, made here and dropped
		# here; a target that cannot even apply to a clean tree would
		# hand it a partial one
		own=1
		if ! "./$target"; then
			p2v_restore "$target"
			rm -rf "$work"
			printf "%s\n" "FAILED: $target does not apply, kept as it was" >&2
			return 1
		fi
	fi
	p2v_splitcompat "$target" "$work" > "$work/blocks"
	p2v_stripcompat "$target" > "$work/bare.sh"
	cp "$work/bare.sh" "$target"
	chmod +x "$target"		# written by awk, not by -o
	regen "$target"			# base only: the blocks are off
	p2v_stashed_run "$target" p2v_reapply "$work" "$target"
	st=$?
	# only a body this run made itself goes back; the caller's is theirs
	[ -n "$own" ] && p2v_restore "$target"
	if [ "$st" -ne 0 ]; then
		cp "$work/orig.sh" "$target"
		chmod +x "$target"
		rm -rf "$work"
		printf "%s\n" "FAILED: $target left as it was" >&2
		return 1
	fi
	rm -rf "$work"
	printf "%s\n" "REBUILT: $target"
)

# --- bulk operations ---------------------------------------------------------

# Write each generated script's embedded patch out as <script>.patch. Nothing is
# run and no file but the .patch is touched, so this works on a dirty tree and
# on scripts that no longer apply. For patches that reflect what the scripts
# really do, reindex first: it refreshes every embedded patch from a real run.
# Usage: extract_patches [file.sh]
extract_patches() (
	set -e
	IFS=$P2VIFS
	list=$(p2v_list "$1") || return 1
	for s in $list
	do
		out="${s%.sh}.patch"
		sed '1,/^=== PATCH2VI PATCH ===$/d' "$s" > "$out"
		if [ -s "$out" ]; then
			printf "%s\n" "EXTRACTED: $out"
		else	# no patch section, or an empty one
			rm -f "$out"
			printf "%s\n" "EMPTY: $s" >&2
		fi
	done
)

# Write every compat block a generated script carries out as a standalone
# .patch (its === COMPAT PATCH === diff, verbatim, exactly what its author
# handed to -C) and convert each one into its own runnable script. Both land
# in ./compat/ so the results stay out of p2v_scripts: they are generated
# scripts too, and reindex/run_patches must not pick them up as patches of
# their own. A block whose diff no longer applies to the tree still converts,
# with whatever fuzz patch2vi needs; a block with an empty diff is skipped.
# Naming: compat/<script>-<n>-<origins>.patch, numbered in storage order, since
# one script may carry several blocks from the same origin.
# Usage: extract_compats [file.sh]
extract_compats() (
	set -e
	IFS=$P2VIFS
	list=$(p2v_list "$1") || return 1
	p2v_getbin || return 1
	work="$P2VITMP.extract"
	rm -rf "$work"
	mkdir -p "$work" compat
	for s in $list
	do
		p2v_splitcompat "$s" "$work" > "$work/blocks"
		while read -r n src <&3
		do
			if [ ! -s "$work/$n.patch" ]; then
				printf "%s\n" "EMPTY: $s block $n" >&2
				continue
			fi
			# the whole stack names the file: every origin of
			# the label, .sh dropped, joined by -
			p="compat/${s%.sh}-$n"
			case $src in
			?*)	p="$p-$(printf '%s' "$src" |
				sed 's/\.sh$//; s/\.sh /-/g')" ;;
			esac
			mv "$work/$n.patch" "$p.patch"
			printf "%s\n" "EXTRACTED: $p.patch"
			$P2VI -o "$p.sh" "$p.patch"
			printf "%s\n" "GENERATED: $p.sh"
		done 3< "$work/blocks"
	done
	rm -rf "$work"
)

# Read-only companion to extract_patches/extract_compats: everything a single
# generated script carries - its embedded patch first, then every compat block's
# diff, in storage order - concatenated into one .patch and opened in an editor.
# Nothing in the tree is touched and no runnable script is produced, so this
# works on a dirty tree and on scripts that no longer apply.
#
# The file lands in /tmp, or in the current directory when /tmp is not writable.
# Sections are separated by a comment banner, which diff readers and syntax
# highlighters skip over, so the result still reads as a patch.
# Usage: view_patch file.sh
view_patch() (
	set -e
	IFS=$P2VIFS
	if [ -z "$1" ]; then
		echo "Usage: view_patch file.sh" >&2
		return 1
	fi
	p2v_ours "$1"
	base=${1##*/}
	base=${base%.sh}
	out="/tmp/$base.patch"
	if ! { : > "$out"; } 2>/dev/null; then
		out="$base.patch"
		: > "$out"
	fi
	work="$P2VITMP.view"
	rm -rf "$work"
	mkdir -p "$work"
	p2v_splitcompat "$1" "$work" > "$work/blocks"
	printf "%s\n" "# === $1: embedded patch ===" >> "$out"
	sed '1,/^=== PATCH2VI PATCH ===$/d' "$1" >> "$out"
	while read -r n src <&3
	do
		printf "%s\n" "# === compat $n${src:+ from $src} ===" >> "$out"
		cat "$work/$n.patch" >> "$out"
	done 3< "$work/blocks"
	rm -rf "$work"
	printf "%s\n" "VIEWING: $out" >&2
	[ -x ./vi ] && editor=./vi || editor=vi
	p2v_tty "${EDITOR:-$editor}" "$out"
)

# The origins script $1 depends on, out of the edge list compat_order builds.
p2v_deps() { awk -v s="$1" '$1 == s && NF > 1 { print $2 }' "$P2VITMP.edges"; }

# The chain $1 as the command a reader types: the first script is invoked, the
# rest are its arguments. Each one applies itself, appends its own basename to
# $P2VI_PATCH and hands the remainder to the next, so a whole stack is one
# command and every script sees exactly the origins that ran before it. This
# replaced the "./a.sh && ./b.sh" form, which had no channel for that set.
p2v_cmdline() (
	IFS=$P2VIFS
	line=
	for c in $1
	do
		[ -z "$line" ] && line="./$c" || line="$line $c"
	done
	printf "%s\n" "$line"
)

# Run each script of the list $1, in order, output dropped; the first failure is
# the result. Meant to be run on a tree at HEAD, which the caller restores.
#
# The whole list goes to the binary's own -e, which runs the scripts exactly as
# the shell would - in order, each in its own editor lifetime, stopping at the
# first failure, and reporting the status that failure had. One process does
# what was a shell, a grep and a nextvi per script, and the editor that applies
# them is the one patch2vi carries rather than whatever the PATH calls vi, so a
# search measures the scripts and not the machine it runs on.
p2v_runlist() (
	IFS=$P2VIFS
	[ -n "$1" ] || return 0
	$P2VI -e $1 >/dev/null 2>&1
)

# What the caller has of their own and a run here must not carry off: the
# scripts they edited or wrote (untracked ones are in git at all only as far as
# status sees them), the README, and $1, the file the listing is written to.
# Copied aside into $P2VITMP.keep, flat, since all of them sit in the top
# directory. Not compat/, whose scripts are extract_compats' output and are
# never run here.
p2v_keepsh() (
	IFS=$P2VIFS
	rm -rf "$P2VITMP.keep"
	mkdir -p "$P2VITMP.keep"
	git status --porcelain -- '*.sh' ':!compat' | while read -r p2v_st p2v_f
	do
		cp "$p2v_f" "$P2VITMP.keep/"
	done
	for p2v_f in README "$1"
	do
		[ -n "$p2v_f" ] && [ -e "$p2v_f" ] && cp "$p2v_f" "$P2VITMP.keep/"
	done
	return 0
)

# p2v_restore with the scripts in scope as well: a patch may edit one -
# cbuild.sh, say - and the run after it in a search would then read that edit as
# the caller's and carry it. What p2v_keepsh put aside goes back on top, since
# the checkout and the untracked sweep would both undo it.
p2v_restore_sh() (
	IFS=$P2VIFS
	p2v_restore
	git checkout -- '*.sh' ':!compat' >/dev/null 2>&1
	for p2v_k in "$P2VITMP.keep"/*
	do
		[ -e "$p2v_k" ] && cp "$p2v_k" .
	done
	return 0
)

# Depth first over the orders a chain can be applied in: $1 is the chain so far,
# $2 the candidates left. A candidate is only stepped into once the chain up to
# and including it has really applied, from a tree at HEAD, and a step that
# leads nowhere is taken back and the next candidate tried - a script that
# applies here may still leave one further along with nothing to apply to. The
# first order that takes every candidate is printed; without one, nothing is,
# and the status says so. A subshell so its variables are its own: this calls
# itself, and a plain function shares one set with every level below it.
p2v_search() (
	IFS=$P2VIFS
	if [ -z "$2" ]; then
		# an order the build already turned down is stepped over and
		# the walk goes on, so the next one out is the next order that
		# applies - never one that did not
		p2v_n=$(cat "$P2VITMP.skip" 2>/dev/null || echo 0)
		[ "$p2v_n" -le 0 ] && { printf "%s\n" "$1"; return 0; }
		printf "%s\n" "$((p2v_n - 1))" > "$P2VITMP.skip"
		return 1
	fi
	for c in $2
	do
		# an origin of c still waiting: its blocks are not in yet
		miss=
		for d in $(p2v_deps "$c")
		do
			case " $2 " in
			*" $d "*)	miss=1 ;;
			esac
		done
		[ -n "$miss" ] && continue
		p2v_restore_sh
		p2v_runlist "$1 $c" || continue
		rest=
		for o in $2
		do
			[ "$o" = "$c" ] || rest="$rest $o"
		done
		p2v_search "$1 $c" "$rest" && return 0
	done
	return 1
)

# What a run of searches needs standing before the first script is run: the
# caller's own work put aside, a source tree with nothing else of theirs in it,
# and the edge list the walks read. $1 is the file a listing is written to,
# spared along with the rest. Nothing is set up and nonzero comes back when the
# tree is dirty.
# Usage: p2v_search_begin [README]
p2v_search_begin() (
	IFS=$P2VIFS
	p2v_keepsh "$1"
	# The sources alone are the tree this measures: they are what a run
	# dirties and what the restore between runs puts back. What p2v_keepsh
	# just put aside is exempt - it goes back after every run - so an edited
	# script or README is no reason to refuse. Anything else of the caller's
	# would be taken for a script's work and reverted with it.
	dirty=$(p2v_git_src status --porcelain | while read -r st f
		do
			[ -e "$P2VITMP.keep/${f##*/}" ] || printf "%s\n" "$f"
		done)
	if [ -n "$dirty" ]; then
		echo "DIRTY TREE: commit or stash the sources first" >&2
		rm -rf "$P2VITMP.keep"
		return 1
	fi
	# Every apply goes through the binary, so a missing one is not a slow
	# search but no search at all; built here, where the tree is known to be
	# clean, rather than in the middle of one.
	p2v_getbin || return 1
	# One "script" line per script, so a script with no blocks is a node
	# too, plus one "script origin" line per origin it carries.
	for s in $(p2v_scripts)
	do
		printf "%s\n" "$s"
		p2v_origins "$s" |
		while read -r d
		do
			printf "%s %s\n" "$s" "$d"
		done
	done > "$P2VITMP.edges"
)

# What p2v_search_begin and the searches after it left behind, dropped.
p2v_search_end() {
	rm -rf "$P2VITMP.keep"
	rm -f "$P2VITMP.edges" "$P2VITMP.skip" "$P2VITMP.build"
}

# The closure of $1's origins with $1 itself, an origin ahead of what names it
# and $1 last of all: the candidates a search is given, in the order the edges
# ask for.
p2v_closure() {
	awk -v target="$1" '
	function walk(s, i) {
		if (s in seen)
			return
		seen[s] = 1
		for (i = 1; i <= ndep[s]; i++)
			walk(dep[s, i])
		print s
	}
	NF > 1 && !(($1 SUBSEP $2) in edge) {
		edge[$1 SUBSEP $2] = 1
		dep[$1, ++ndep[$1]] = $2
	}
	END { walk(target) }
	' "$P2VITMP.edges"
}

# The order the candidates $1 apply and build in, printed as the shell command
# that runs them - the scripts joined by &&, one chain to a line however long it
# runs - and meant to be copied out and run as it stands.
#
# p2v_search walks the orders the edges allow and runs every one it considers,
# so what comes out really applied, whole, on a tree at HEAD. Applying is not
# enough on its own - two orders can both apply and only one of them compile -
# so that chain, and only that chain, is built, and a chain the build turns down
# sends the search back for the next order that applies. Nothing the search
# threw away is built: an order it ruled out has a script in it that would not
# apply, and the tree that leaves behind teaches nothing.
#
# Nothing is printed and 1 comes back once no order is left, the errors of the
# last build turned down going to stderr, that build being the one that explains
# the refusal. The status lines are stderr as well, the chain itself being
# stdout; so is the output of the build that settled the chain, warnings and
# all, unless $2 asks for quiet - a caller with a hundred chains to get through
# hears the same warnings out of every one of them.
# Usage: p2v_chain candidates [quiet]
p2v_chain() (
	IFS=$P2VIFS
	skip=0
	while :
	do
		printf "%s\n" "$skip" > "$P2VITMP.skip"
		chain=$(p2v_search "" "$1")
		searched=$?
		p2v_restore_sh
		if [ "$searched" -ne 0 ]; then
			# nothing was emitted for the last build, and it is the
			# one that explains why no order is left, so its output
			# is let out here - named, since no build ran between
			# the failure and this and the errors would otherwise
			# read as a fresh one
			if [ "$skip" -gt 0 ]; then
				printf "%s\n" "LAST BUILD: $line" >&2
				cat "$P2VITMP.build" >&2
			fi
			return 1
		fi
		line=$(p2v_cmdline "$chain")
		# the chain as it will be printed, and only it, built: -O0, since
		# nothing here runs the binary, and the warnings go by where they
		# can be read against the chain that raised them
		printf "%s\n" "BUILDING: $line" >&2
		p2v_runlist "$chain"
		CFLAGS=-O0 ./cbuild.sh build > "$P2VITMP.build" 2>&1
		built=$?
		p2v_restore_sh
		if [ "$built" -eq 0 ]; then
			[ -z "$2" ] && cat "$P2VITMP.build" >&2
			printf "%s\n" "$line"
			return 0
		fi
		printf "%s\n" "BUILD FAILED: $line, trying next order" >&2
		skip=$((skip + 1))
	done
)

# The compat order: for every script that carries compat blocks, the scripts it
# needs and itself, in an order that applies.
#
# A block only applies to a tree its origin has already patched, so every src=
# is an edge origin -> script, and a script's chain is that script with every
# origin it depends on, directly or through an origin's own blocks. Scripts no
# block names are left out: nothing orders them and they apply whenever.
#
# The edges are not the whole story. Two scripts with no block between them can
# still only go one way round - one of them absorbs the other's drift and not
# the reverse - and no stored block says so. So the order is not derived, it is
# found: p2v_chain runs and builds the orders the edges allow and hands back the
# first that holds whole. Candidates are tried in edge order, so the order the
# blocks ask for is the one that comes out wherever it works. A chain no order
# applies in, or none whose orders build, is reported and left out.
#
# A chain is the whole closure of a target's origins, so what it settles is the
# one tree that has all of them in; the smaller trees the same blocks have to
# work in are compat_check's.
#
# This runs the scripts, so it wants a tree with nothing of its own in it; the
# tree is put back at HEAD afterwards.
#
# With no argument the chains go to stdout. With one, that file - the README -
# has its list of chains rewritten in place, replacing the one already there.
# Usage: compat_order [README]
compat_order() (
	IFS=$P2VIFS
	p2v_search_begin "$1" || return 1
	: > "$P2VITMP.order"
	st=0
	for target in $(awk 'NF > 1 { print $1 }' "$P2VITMP.edges" | sort -u)
	do
		printf "%s\n" "CHECKING: $target" >&2
		line=$(p2v_chain "$(p2v_closure "$target")")
		if [ -z "$line" ]; then
			printf "%s\n" "NO ORDER: $target, left out" >&2
			st=1
			continue
		fi
		printf "%s\n" "$line" >> "$P2VITMP.order"
	done
	p2v_search_end
	if [ -z "$1" ]; then
		cat "$P2VITMP.order"
		rm -f "$P2VITMP.order"
		return $st
	fi
	# The list closes the opening section, and runs from its own first line
	# to the first catalog entry. Both fences are rewritten along with what
	# they hold, so a rerun is idempotent; a README with no list yet trips
	# only the closing fence and has one inserted above it.
	awk -v order="$P2VITMP.order" '
	/^Every line below is one full chain/	{ skip = 1 }
	/^patch2vi\.sh$/			{
		skip = 0
		print "Every line below is one full chain, in an order that applies."
		print "Patches not listed are unconstrained. Combinations are generated"
		print "by compat_order in patch2vi.sh."
		print ""
		while ((getline line < order) > 0)
			print line
		close(order)
		print ""
	}
	!skip					{ print }
	' "$1" > "$P2VITMP.readme"
	cp "$P2VITMP.readme" "$1"
	rm -f "$P2VITMP.readme" "$P2VITMP.order"
	printf "%s\n" "UPDATED: $1" >&2
	return $st
)

# Every combination the candidate list $1 stands for, one to a line and in the
# order of $1: its last name - the target, which the walk prints after the
# origins it needs - is in all of them, the others are dropped in every mix. A
# list of n names makes 2^(n-1) lines, the target on its own first and the whole
# list last, so a search works its way out from the smallest tree.
p2v_subsets() {
	printf "%s\n" "$1" | awk '
	{ a[++n] = $1 }
	END {
		for (m = 0; m < 2 ^ (n - 1); m++) {
			s = ""
			for (i = 1; i < n; i++)
				if (int(m / 2 ^ (i - 1)) % 2)
					s = s a[i] " "
			print s a[n]
		}
	}
	'
}

# Every tree a stored compat block can be asked to work in, tried.
#
# compat_order settles one chain per target, the closure of its origins all of
# it in. But a block only fires when the origin it names is present, so a target
# whose blocks name several origins has as many trees to survive as those
# origins have combinations, and the closure is one of them: linewrap_v2.sh
# carries four blocks, one derived against lsp.sh, visual.sh and splits.sh
# together, and only that one is on the chain compat_order builds. The rest, and
# every target's smaller trees down to the target on its own, are what this
# walks - each combination searched and built exactly as a chain is.
#
# A combination no order applies in, or none whose orders build, is a real
# failure: a tree somebody can put together does not take its patches. Those
# combinations go to stdout as the shell command that runs them, and the count
# to stderr; a combination that holds says nothing beyond its progress lines.
# The order one came out in is not printed - compat_order is where orders are
# read. Combinations reaching outside a target's closure are not tried: no
# stored block ties those scripts together, so there is nothing there to check.
#
# Like compat_order this runs the scripts and wants a tree with nothing of its
# own in it. It builds once per combination, so it runs as long as the closures
# are wide. With a number as $1, at most that many combinations are tried for
# each target - a cap on the walk, not on the whole run, so a wide closure
# cannot eat the time of every target after it.
# Usage: compat_check [max]
compat_check() (
	IFS=$P2VIFS
	max=$1
	p2v_search_begin || return 1
	: > "$P2VITMP.bad"
	n=0
	for target in $(awk 'NF > 1 { print $1 }' "$P2VITMP.edges" | sort -u)
	do
		p2v_subsets "$(p2v_closure "$target")" > "$P2VITMP.subsets"
		combos=$(wc -l < "$P2VITMP.subsets" | tr -d ' ')
		printf "%s\n" "CHECKING: $target, $combos combinations" >&2
		# a combination at a time off fd 3, since the body runs whole
		# scripts, which own stdin; c counts this target's combinations,
		# n all of them, for the summary
		c=0
		stop=
		while read -r sub <&3
		do
			if [ -n "$max" ] && [ "$c" -ge "$max" ]; then
				stop=1
				break
			fi
			c=$((c + 1))
			n=$((n + 1))
			p2v_chain "$sub" quiet > /dev/null && continue
			line=$(p2v_cmdline "$sub")
			printf "%s\n" "FAILED: $line" >&2
			printf "%s\n" "$line" >> "$P2VITMP.bad"
		done 3< "$P2VITMP.subsets"
		[ -z "$stop" ] || continue
	done
	rm -f "$P2VITMP.subsets"
	p2v_search_end
	bad=$(wc -l < "$P2VITMP.bad" | tr -d ' ')
	printf "%s\n" "CHECKED: $n combinations, $bad failed" >&2
	cat "$P2VITMP.bad"
	rm -f "$P2VITMP.bad"
	[ "$bad" -eq 0 ]
)

# Collapse the compat blocks a script carries from one origin into a single one.
#
# A compat fix grows by addition: run origin.sh and target.sh, edit the sources
# until the collision is resolved again, and hand that edit to -C, which stacks
# another block on the target. Blocks stay stacked, so the stack is the history
# of the fix, and this turns it back into the one block it is meant to be.
#
# Nothing is read out of the old blocks, only the two trees the scripts really
# produce: A, the collision with every block from origin.sh stripped out, and B,
# the same run with all of them in. Their diff is the whole resolution as it
# stands today, and -C re-derives the block from that, which is what makes a
# collapse survive a patch2vi whose patterns now collide differently.
#
# The tree is restored, target.sh is rewritten in place: commit it afterwards.
# With no origin, every origin the target has more than one block from.
# Usage: recompat target.sh [origin.sh]
recompat() (
	set -e
	if [ -z "$1" ]; then
		echo "Usage: recompat target.sh [origin.sh]" >&2
		return 1
	fi
	target="$1"
	p2v_ours "$target"
	p2v_getbin || return 1
	if [ -n "$2" ]; then
		list="$2"
	else	# an origin with a single block is already collapsed
		list=$(p2v_compatsrc "$target" | sort | uniq -d)
		if [ -z "$list" ]; then
			printf "%s\n" "NOTHING TO COLLAPSE: $target" >&2
			return 0
		fi
	fi
	p2v_batch
	# A is the collision itself, so the target is meant to miss hunks there:
	# without this it quits at the first one and A is a half-applied tree,
	# which the -C replay - it keeps going by the same rule - never
	# reproduces, so the diff taken against it does not apply. B misses the
	# same hunks before its blocks repair them and is held to the same rule.
	export QF2=1
	work="$P2VITMP.recompat"
	# A label derived against a stack of origins holds spaces, so the labels
	# are read a line at a time rather than word split - and off fd 3, since
	# the body runs whole scripts, which own stdin. IFS is left alone: the
	# helpers this calls do split on it.
	while read -r origin <&3
	do
		[ -n "$origin" ] || continue
		p2v_eachorigin "$origin" p2v_ours
		n=$(p2v_compatsrc "$target" | grep -cxF "$origin") || n=0
		if [ "$n" -eq 0 ]; then
			printf "%s\n" "NO BLOCKS: $target from $origin" >&2
			continue
		fi
		rm -rf "$work"
		mkdir -p "$work"
		cp "$target" "$work/orig.sh"
		p2v_restore
		# A: the collision on its own. Every origin of the label runs
		# ahead of it, in stored order and in one chain: the collision a
		# stacked block resolves is the one the whole stack makes, and
		# only that tree shows it.
		p2v_stripcompat "$target" "$origin" > "$work/bare.sh"
		chmod +x "$work/bare.sh"
		p2v_reemit "$work/bare.sh"
		p2v_runchain "$origin" "$work/bare.sh"
		a=$(p2v_snaptree)
		p2v_restore
		# B: the collision with every block from this origin resolving it
		p2v_runchain "$origin" "$target"
		b=$(p2v_snaptree)
		git diff-tree -p "$a" "$b" > "$work/compat.patch"
		p2v_restore
		if [ ! -s "$work/compat.patch" ]; then
			printf "%s\n" "EMPTY: $origin resolves nothing, $target kept" >&2
			continue
		fi
		p2v_stripcompat "$target" "$origin" > "$work/new.sh"
		cp "$work/new.sh" "$target"
		chmod +x "$target"		# written by awk, not by -o
		p2v_reemit "$target"		# re-emit without the old blocks
		# the blocks came off the target before this call: a derivation
		# that fails now would leave the script stripped of them
		if ! p2v_co "$origin" "$target" "$work/compat.patch"; then
			cp "$work/orig.sh" "$target"
			chmod +x "$target"
			p2v_restore
			printf "%s\n" "FAILED: $target <- $origin, left as it was" >&2
			return 1
		fi
		p2v_restore
		printf "%s\n" "COLLAPSED: $target <- $origin, $n blocks into 1"
	done 3<<EOF
$list
EOF
	rm -rf "$work"
)

# Re-run patch2vi-generated script(s) and refresh their embedded patch from the
# resulting diff. With a file arg, only that script; otherwise all of them
# (pass 1 to also build via ./cbuild.sh after each).
# Usage: reindex [file.sh | 1]
reindex() (
	set -e
	IFS=$P2VIFS
	dobuild=
	case "$1" in
	1)	dobuild=1; list=$(p2v_scripts) ;;
	*)	list=$(p2v_list "$1") || return 1 ;;
	esac
	for s in $list
	do
		printf "%s\n" "SCRIPT: $s"
		"./$s"
		[ -n "$dobuild" ] && ./cbuild.sh build
		p2v_snapdiff "$P2VITMP"
		p2v_splice "$s" "$P2VITMP"
		rm -f "$P2VITMP"
		git add "$s"
		printf "\n"
	done
	rm -f tmp *.orig *.rej
)

# DESTRUCTIVE. Drops every compat block a generated script carries: the stored
# === PATCH2VI COMPAT === regions go, then the script is re-emitted from what
# is left, which is what takes the blocks' bodies out of it. The embedded patch
# is untouched, so only the compat side is lost - extract_compats first if the
# diffs are worth keeping. With a file arg, only that script; otherwise all of
# them.
# Usage: discard_compats [file.sh]
discard_compats() (
	set -e
	IFS=$P2VIFS
	list=$(p2v_list "$1") || return 1
	p2v_getbin || return 1
	for s in $list
	do
		grep -q '^=== PATCH2VI COMPAT ' "$s" || continue
		p2v_stripcompat "$s" > "$P2VITMP.compat"
		cp "$P2VITMP.compat" "$s"
		rm -f "$P2VITMP.compat"
		chmod +x "$s"	# written by awk, not by patch2vi's own -o
		p2v_reemit "$s"
		printf "%s\n" "DISCARDED: $s"
	done
)

# Run every patch2vi-generated script, restoring the tree after each one. Pass 1
# to also rebuild via ./cbuild.sh after each, which is what turns this into a
# smoke test of the patch set. Writing the .patch files is not its job:
# "reindex && extract_patches" refreshes them from what the scripts actually do.
# Usage: run_patches [1]
run_patches() (
	set -e
	IFS=$P2VIFS
	for s in $(p2v_scripts)
	do
		printf "%s\n" "RUNNING: $s"
		"./$s"
		[ "$1" = "1" ] && ./cbuild.sh build
		# extracted patches are not the run's leavings: keep them
		new=$(p2v_newfiles | grep -v '\.patch$' || true)
		git checkout . >/dev/null 2>&1
		p2v_dropnew "$new"
		printf "\n"
	done
)

# regen over every generated script, each one committed. A deeper reindex:
# reindex only splices a fresh diff into the patch section and leaves the body
# alone, this re-emits the body from that diff as well. Compat blocks ride along
# as stored, they are not re-derived - that is recompat's job. No editor is
# involved: a regeneration is a pure re-emission.
# By default the commits are squashed back into a single staged change at the
# end; with arg 1 the per-script commits are kept.
# Usage: regen_all [1]
regen_all() (
	set -e
	IFS=$P2VIFS
	n=0
	for s in $(p2v_scripts)
	do
		"./$s"
		new=$(p2v_newfiles)
		p2v_addnew "$new"
		gitdiff2vi "$s"
		git add "$s"
		if ! git diff --cached --quiet; then
			git commit -m "$s: regen"
			n=$((n + 1))
		fi
		git reset --hard
		p2v_dropnew "$new"
	done
	if [ -z "$1" ] && [ "$n" -gt 0 ]; then
		git reset HEAD~$n
		git add .
	fi
)

# rebuild over every generated script, each one committed. Deeper still than
# regen_all: that re-emits a body out of the diff a script already carries and
# rides its compat blocks along as stored, this re-derives every block's diff
# against the base it has just regenerated.
#
# One script at a time with a commit between, because rebuild wants a clean tree
# and the script it just rewrote has to leave the working tree before the next
# one is measured. A script rebuild refuses is left as it was and stops the run
# there, rather than leaving half the set rebuilt and half of it committed.
# By default, do not stop in the editor or let it draw, and squash all commits
# back into a single staged change at the end. With arg 1, stop in the editor
# and keep the per-script commits.
# Usage: rebuild_all [1]
rebuild_all() (
	IFS=$P2VIFS
	n=0
	if [ -n "$(git status --porcelain)" ]; then
		echo "DIRTY TREE: commit or stash first" >&2
		return 1
	fi
	[ -z "$1" ] && p2v_batch
	for s in $(p2v_scripts)
	do
		rebuild "$s" || return 1
		git add "$s"
		if ! git diff --cached --quiet; then
			git commit -m "$s: rebuild" || return 1
			n=$((n + 1))
		fi
		# The tree was clean when this started and the target is
		# committed by now, so anything still modified is the run's own
		# and goes back whole. rebuild reads a tree it did not dirty as
		# the next script's body, so nothing may be left lying here.
		git checkout -- .
		p2v_dropnew "$(p2v_newfiles)"
	done
	if [ -z "$1" ] && [ "$n" -gt 0 ]; then
		git reset HEAD~$n
		git add .
	fi
)
