#!/bin/sh -e
# Generated by patch2vi from unified diff
# Available separators: 0003-0010 0013-0014 0016-0032 0034-0037 0120-0121 0126 0132 0176 0200-0377

VI=${VI:-vi}
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi binary" >&2
    exit 1
fi

# Env switches:
# Phase 1 (search/mark) reports nothing by default
#   DBG1=1 reports failures and which fallback anchor
#   resolved a group, QF1=1 also quits on failure
# Phase 2 (edits) reports and quits by default
#   DBG2=1 silences it, QF2=1 keeps going after an error
# INTR=1 enters vi at the failing code line in this
#   script, for state inspection mid execution

# Body too large for EXINIT/argv: stage it in a file
( : > /tmp/p2vi.$$ ) 2>/dev/null && P2VIF=/tmp/p2vi.$$ || P2VIF=./p2vi.$$
trap 'rm -f "$P2VIF"' EXIT

# Patch: conf.c ex.c led.c vi.c vi.h
printf '%s%s%s\n' '|sc! |:vis 3ic 0217reg prFp FAIL %@219pr? %@212214reg ? %@217? %@211216reg ? %@220221reg vis 2q!1211reg ? %@221'\
"${DBG1:+213reg ? %@217? %@210215reg ? %@220}\
${DBG2:+ya!214ya!216}\
${QF1:+210reg vis 2q!1}\
${QF2:+ya!221}\
${INTR:+212reg |sc|vis 2:fr 0:e $0:83reg %@47:%f> 219reg %@219:&Q:b0:|sc! |:vis 3q1}"\
'fr 98b0%ya 98?0?
%f> \(\?:'\''\[0-9]\+\)\|\(\[\.%\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\[0-9]\+\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\)\[ \\t]\*\\
\(\?:\(\[,;]#\?\)\[ \\t]\*\(\(\?:\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\(\?:\(\?:<\(\?:\[\^<\\\\\\\\]\|\\\\\\\\\.\?\)\*<\?\|>\(\?:\[\^>\\\\\\\\]\|\\\\\\\\\.\?\)\*>\?\)\|\\
\(\?:'\''\[0-9]\+\)\|\(\[\.\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\(\[0-9]\+\)\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\)\*\[ \\t]\*\)\*\)\\
\(\(pac\|pr\|ai\|ish\|err\|fr\|ic\|grp\|mpt\|rr\|shape\|seq\|ts\|td\|order\|hl\[lwpr]\?\|left\|lim\|led\|vis\)\\
\|\[@&!dmj]\|=\\\\\?\{0,1}\|\\\\\?\{1,2}\[\?!]\?\|b\[psx]\?\|p\[uh]\?\|ac\|e\[f!]\?!\?\|f\[-\+><tdp]\?\|inc\|i\|sc!\?\|\\
\(\?:g!\?\|s\)\[ \\t]\?\(\.\)\?\|q!\?\|reg\?\\\\\+\?\|rd\?\|w\(\?:q!\|\[q!]\)\?\|u\[czbd]\|x!\?\|ya\[!\+]\?\|cm!\?\|cd\?\)\?",
		A\(BL1 \| SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1\)},1??0?
1??+3m 11q0?
%f> \(\(pac\|pr\|ai\|ish\|err\|fr\|ic\|grp\|mpt\|rr\|shape\|seq\|ts\|td\|order\|hl\[lwpr]\?\|left\|lim\|led\|vis\)\\
\|\[@&!dmj]\|=\\\\\?\{0,1}\|\\\\\?\{1,2}\[\?!]\?\|b\[psx]\?\|p\[uh]\?\|ac\|e\[f!]\?!\?\|f\[-\+><tdp]\?\|inc\|i\|sc!\?\|\\
\(\?:g!\?\|s\)\[ \\t]\?\(\.\)\?\|q!\?\|reg\?\\\\\+\?\|rd\?\|w\(\?:q!\|\[q!]\)\?\|u\[czbd]\|x!\?\|ya\[!\+]\?\|cm!\?\|cd\?\)\?",
		A\(BL1 \| SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1\)},2??0?
2??m 1220reg p OK conf.c:300:a22sc %? %@2152sc!1q0?
;0fr.,$f> ^\(\(pac\|pr\|ai\|ish\|err\|fr\|ic\|grp\|mpt\|rr\|shape\|seq\|ts\|td\|order\|hl\[lwpr]\?\|left\|lim\|led\|vis\)\\$3??0?
3??m 1220reg p OK conf.c:300:a32sc %? %@2152sc!fr 981qfr 980?
%f> \(\?:'\''\[0-9]\+\)\|\(\[\.%\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\[0-9]\+\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\)\[ \\t]\*\\
\(\?:\(\[,;]#\?\)\[ \\t]\*\(\(\?:\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\(\?:\(\?:<\(\?:\[\^<\\\\\\\\]\|\\\\\\\\\.\?\)\*<\?\|>\(\?:\[\^>\\\\\\\\]\|\\\\\\\\\.\?\)\*>\?\)\|\\
\(\?:'\''\[0-9]\+\)\|\(\[\.\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\(\[0-9]\+\)\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\)\*\[ \\t]\*\)\*\)\\4??0?
4??+3m 1220reg p OK conf.c:300:a42sc %? %@2152sc!1q0?
%f> \|\[@&!dmj]\|=\\\\\?\{0,1}\|\\\\\?\{1,2}\[\?!]\?\|b\[psx]\?\|p\[uh]\?\|ac\|e\[f!]\?!\?\|f\[-\+><tdp]\?\|inc\|i\|sc!\?\|\\
\(\?:g!\?\|s\)\[ \\t]\?\(\.\)\?\|q!\?\|reg\?\\\\\+\?\|rd\?\|w\(\?:q!\|\[q!]\)\?\|u\[czbd]\|x!\?\|ya\[!\+]\?\|cm!\?\|cd\?\)\?",
		A\(BL1 \| SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1\)},5??0?
5??-1m 1220reg p OK conf.c:300:a52sc %? %@2152sc!1q0?
%f> .....0.9].....\....\|.0-9..t.\*...\).\?........%... \\.]\*\[0....\[......\*...\[ ...\*..\|......\\..\\].....\..\)\*...\?..\\.]......\\t..\\
....\[,;...\)....].\(......\(\?....\\.....\\.\\\\..\).....\[.\\..\*.......:.\(..\[\^.\\........\\\.......>.\?.....\\........\.\?.\*...\|.
.....0...\+\).\(.\..........t].....\(.......\+...........\[...].\)..\\....\*..:....]...\|...\[...\\.\\.\|.....\?\)..\\..... ........
\(.....p..a........r\|.....\|......t...\|s.....se...s...\|..de..h...w..]..l.f.\|..m......i...
..@..d.j...\\....,1..\\......}.\?.].........\|p.uh.\?....e\[....!\?\|.\[-\+..tdp....n..i..c..\|.
.\?:..\?.... \\.]...\)\?..!.....\?...\?.r..............\)..............y..!..\?.c...........
......1....Y...., ....RE..R...R....H.....1....,......H., RE, .R1, .Y......\)..6??0?
6??+3m 1220reg p OK conf.c:300:a62sc %? %@2152sc!1q0?
grp 1%f> \(\?:'\''\[0-9]\+\)\|\(\[\.%\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\[0-9]\+\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\)\[ \\t]\*\\.*?
\(\?:\(\[,;]#\?\)\[ \\t]\*\(\(\?:\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\(\?:\(\?:<\(\?:\[\^<\\\\\\\\]\|\\\\\\\\\.\?\)\*<\?\|>\(\?:\[\^>\\\\\\\\]\|\\\\\\\\\.\?\)\*>\?\)\|\\.*?
\(\?:'\''\[0-9]\+\)\|\(\[\.\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\(\[0-9]\+\)\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\)\*\[ \\t]\*\)\*\)\\.*?
(\(\(pac\|pr\|ai\|ish\|err\|fr\|ic\|grp\|mpt\|rr\|shape\|seq\|ts\|td\|order\|hl\[lwpr]\?\|left\|lim\|led\|vis\)\\)7??0?
grp 07??m 1220reg p OK conf.c:300:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	\{ac_ft, "\[\^ \\t-/:-@\[-\^\{-~]\+\(\?:\(\\n\$\)\|\\n\)\|\\n\|\(\[\^\\n]\+\(\\n\)\)",
		A\(NA, SYN_BGMK\(RE1\), SYN_BGMK\(AY1\), SYN_BGMK\(AY\)\)},
	\{ac_ft, "\[\^ \\t-/:-@\[-\^\{-~]\+\$\|\(\.\+\$\)", A\(NA, SYN_BGMK\(AY1\)\)},.*(	\{vs_ft, "\.\+", A\(AY1 \| SYN_BD\), 1},)
	\{vs_ft, "\(\^\[\?/]\)\|\(\\\\\\\\\[<>]\|\\\\\(\\\\\?\[:=!<>#]\|\\\\\[\\\\\^\?\(\(\?:\\\\\\\\\.\?\|\[\^\\\\]]\)\*\)]\|\\\\\[\|\[\.\^\$\\\\\(\)\*\+\|\?]\|\\\\\{\(\[0-9]\*\(,\)\?\[0-9]\*\)\?}\?\)\|\\\\\\\\\(\.\)",
		A\(SYN_BD, BL1, WH1, GR1, RE1, WH1, YE\)},8??0?
grp 08??-7m 1220reg p OK conf.c:300:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	\{n_ft, "1\(\[ \\t]\*\[1-9]\[ \\t]\*\)9", A\(RE1, MA1 \| SYN_BD\)},
	\{n_ft, "9\[ \\t]\*\(\[1-9]\[ \\t]\*\)1", A\(RE1, MA1 \| SYN_BD\)},
	\{n_ft, "\[1-9]", A\(RE1\)},.*(	\{vs_ft, "\(\\\\\\\\\)\(\.\)\(\?:\(-\)\(\?:\(\\\\\\\\\(\.\)\)\|\[\^\\\\\\\\\\\\]]\)\)\?\|\[\^\\\\\\\\\[\^]\(-\)\(\?:\(\\\\\\\\\(\.\)\)\|\.\)\|\\)
\[\^\\\\\\\\\[\^]\\\\\^\(-\)\(\?:\(\\\\\\\\\(\.\)\)\|\[\^\\\\\\\\]\)\|\\\\\^\(-\)\[\^\\\\\\\\]",
		A\(GR1 \| SYN_BD \| SYN_ATT, 1, GR1, AY1, YE, WH1, AY1, YE, WH1, AY1, YE, WH1, AY1, YE, WH1\), 2},9??0?
grp 09??-10m 1220reg p OK conf.c:300:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg conf.c:3002sc %? %@2132sc!0?
'\''1s/\(p/(qe|p/??!219reg conf.c:300:m12sc %? %@2142sc!b1%ya 98?0?
%f> int xleft;			/\* the first visible column \*/
int xvis;			/\* startup flags \*/
int xai = 1;			/\* autoindent option \*/1??0?
1??m 11q0?
;0fr.,$f> ^int xleft;			/\* the first visible column \*/$4??0?
4??m 1220reg p OK ex.c:0:a42sc %? %@2152sc!fr 98fr 980?
1;4??!219reg ex.c:02sc %? %@2132sc!0?
?0?
%f+ EO\(pac\) EO\(pr\) EO\(ai\) EO\(err\) EO\(fr\) EO\(ish\) EO\(ic\) EO\(mpt\)
EO\(rr\) EO\(shape\) EO\(seq\) EO\(td\) EO\(order\) EO\(hll\) EO\(hlw\)
EO\(hlp\) EO\(hlr\) EO\(hl\) EO\(lim\) EO\(led\) EO\(vis\)

_EO\(ts, xts = \*arg \? eo_val\(arg\) : !xts; xts = MAX\(0, xts\); return NULL;\)
_EO\(grp, xgrp = \(\*arg \? eo_val\(arg\) : !xgrp\) \* 2; xgrp = MAX\(0, xgrp\); return NULL;\)1??0?
1??+2m 21q0?
%f+ EO\(pac\) EO\(pr\) EO\(ai\) EO\(err\) EO\(fr\) EO\(ish\) EO\(ic\) EO\(mpt\)
EO\(rr\) EO\(shape\) EO\(seq\) EO\(td\) EO\(order\) EO\(hll\) EO\(hlw\)
EO\(hlp\) EO\(hlr\) EO\(hl\) EO\(lim\) EO\(led\) EO\(vis\)4??0?
4??+2m 2220reg p OK ex.c:1649:a42sc %? %@2152sc!1q0?
grp 1%f+ EO\(pac\) EO\(pr\) EO\(ai\) EO\(err\) EO\(fr\) EO\(ish\) EO\(ic\) EO\(mpt\).*?
EO\(rr\) EO\(shape\) EO\(seq\) EO\(td\) EO\(order\) EO\(hll\) EO\(hlw\).*?
(EO\(hlp\) EO\(hlr\) EO\(hl\) EO\(lim\) EO\(led\) EO\(vis\))7??0?
grp 07??m 2220reg p OK ex.c:1649:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	return uc_isdigit\(\*arg\) \|\| \(\*arg == '\''-'\'' && uc_isdigit\(arg\[1]\)\) \?
		atoi\(arg\) : \(unsigned char\)\*arg;
}.*(_EO\(left,)
	if \(\*loc\)
		xleft = \(xcols / 2\) \* atoi\(loc\);8??0?
grp 08??-5m 2220reg p OK ex.c:1649:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	}
	return xkwdrs \? NULL : xserr;
}.*(	else if \(\*arg\))
		xleft = atoi\(arg\);
	else if \(lbuf_get\(xb, xrow\)\)9??0?
grp 09??-8m 2220reg p OK ex.c:1649:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg ex.c:16492sc %? %@2132sc!0?
?0?
%f+ 	\{"g", ec_glob},
	EO\(mpt\),
	\{"m", ec_mark},
	\{"q!", ec_quit},
	\{"q", ec_quit},
	\{"reg\+", ec_regprint},1??0?
1??+2m 31q0?
%f+ 	\{"g", ec_glob},
	EO\(mpt\),
	\{"m", ec_mark},4??0?
4??+2m 3220reg p OK ex.c:1716:a42sc %? %@2152sc!1q0?
grp 1%f+ 	\{"g", ec_glob},.*?
	EO\(mpt\),.*?
(	\{"m", ec_mark},)7??0?
grp 07??m 3220reg p OK ex.c:1716:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	\{"d", ec_delete},
	EO\(grp\),
	\{"g!", ec_glob},.*(	\{"reg", ec_regprint},)
	\{"re", ec_krsset},
	\{"rd", ec_undoredo},8??0?
grp 08??-4m 3220reg p OK ex.c:1716:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	\{"inc", ec_setincl},
	EO\(ic\),
	\{"i", ec_insert},.*(	EO\(rr\),)
	\{"r", ec_read},
	\{"wq!", ec_write},9??0?
grp 09??-7m 3220reg p OK ex.c:1716:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg ex.c:17162sc %? %@2132sc!0?
'\''1-1i int xqe = 1000;			/* exit insert via kj (delay in ms) */
??!219reg ex.c:0:m12sc %? %@2142sc!0?
'\''2i EO(qe)
??!219reg ex.c:1649:m22sc %? %@2142sc!0?
'\''3i 	EO(qe),
??!219reg ex.c:1716:m32sc %? %@2142sc!b2%ya 98?0?
%f> static sbuf \*suggestsb;
static sbuf \*acsb;
sbuf \*led_attsb;

1??0?
1??m 11q0?
;0fr.,$f> ^static sbuf \*suggestsb;$4??0?
4??m 1220reg p OK led.c:1:a42sc %? %@2152sc!fr 98fr 980?
1;4??!219reg led.c:12sc %? %@2132sc!0?
?0?
%f+ 				exbuf_load\(ex_buf\)
			}
			continue; }
		default:
			if \(c == '\''\\n'\'' \|\| TK_INT\(c\)\)
				return c;1??0?
1??+2m 21q0?
%f+ 				exbuf_load\(ex_buf\)
			}
			continue; }4??0?
4??+2m 2220reg p OK led.c:643:a42sc %? %@2152sc!1q0?
grp 1%f+ 				exbuf_load\(ex_buf\).*?
			}.*?
(			continue; })7??0?
grp 07??m 2220reg p OK led.c:643:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 				exbuf_load\(ex_buf\)
			} else if \(bidx != ex_buf - bufs && bidx < xbufcur\) \{
				ex_buf = bufs \+ bidx;.*(			if \(\(cs = led_read\(kmap, c\)\)\))
				sbuf_str\(sb, cs\)
		}8??0?
grp 08??-4m 2220reg p OK led.c:643:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 				if \(ex_buf == tmpex_buf\)
					continue;
				restore\(ex_buf\).*(		is->sug = NULL;)
		is->_sug = NULL;
		if \(ai_max >= 0 && xpac\)9??0?
grp 09??-7m 2220reg p OK led.c:643:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg led.c:6432sc %? %@2132sc!0?
'\''1i static int gettime_ms(void)
{
	struct timespec t;
	if (clock_gettime(CLOCK_MONOTONIC, &t) < 0)
		return 0;
	return t.tv_sec * 1000 + t.tv_nsec / 1000000;
}

??!219reg led.c:1:m12sc %? %@2142sc!0?
'\''2i 		case '\''j'\'':
			if (xqe && (gettime_ms() - is->quickexit) < xqe) {
				if (len - pre > 0 && sb->s[led_lastchar(sb->s)] == '\''k'\'') {
					term_push("", 2);
					continue;
				}
			}
			goto _default;
		case '\''k'\'':
			is->quickexit = gettime_ms();
_default:
??!219reg led.c:643:m22sc %? %@2142sc!b3%ya 98?0?
%f> #include <dirent\.h>
#include <signal\.h>
#include <unistd\.h>
#include <poll\.h>
#include <termios\.h>
#include <limits\.h>1??0?
1??+2m 11q0?
%f> #include <dirent\.h>
#include <signal\.h>
#include <unistd\.h>4??0?
4??+2m 1220reg p OK vi.c:9:a42sc %? %@2152sc!1q0?
grp 1%f> #include <dirent\.h>.*?
#include <signal\.h>.*?
(#include <unistd\.h>)7??0?
grp 07??m 1220reg p OK vi.c:9:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> #include <stdarg\.h>
#include <stdlib\.h>
#include <string\.h>.*(#include <sys/stat\.h>)
#include <sys/ioctl\.h>
#include <sys/wait\.h>8??0?
grp 08??-4m 1220reg p OK vi.c:9:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> #include <ctype\.h>
#include <fcntl\.h>
#include <stdio\.h>.*(#include "vi\.h")
#include "conf\.c"
#include "ex\.c"9??0?
grp 09??-7m 1220reg p OK vi.c:9:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg vi.c:92sc %? %@2132sc!0?
?0?
%f+ 				}
				xoff--;
				rep_record\(\)
				vi_mod \|= !xpac && xrow == orow \? 8 : 1;
				break;
			case '\''J'\'':1??0?
1??+2m 21q0?
%f+ 				}
				xoff--;
				rep_record\(\)4??0?
4??+2m 2220reg p OK vi.c:1554:a42sc %? %@2152sc!1q0?
grp 1%f+ 				}.*?
				xoff--;.*?
(				rep_record\(\))7??0?
grp 07??m 2220reg p OK vi.c:1554:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 					c = xoff != lbuf_eol\(xb, xrow, 1\) \? '\''i'\'' : '\''a'\'';
					xb->useq \+= xseq;
					goto insert;.*(				vc_join\(1, vi_arg <= 1 \? 2 : vi_arg\);)
				rep_record\(\)
				vi_mod \|= 1;8??0?
grp 08??-4m 2220reg p OK vi.c:1554:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 						} else
							vi_delete\(xrow, xoff - 1, xrow, xoff, 0\);
					}.*(			case '\''K'\'': \{)
				preserve\(int, xvis, xvis = 1;\)
				do \{9??0?
grp 09??-8m 2220reg p OK vi.c:1554:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg vi.c:15542sc %? %@2132sc!0?
'\''1i #include <time.h>
??!219reg vi.c:9:m12sc %? %@2142sc!0?
'\''2i 				if (xqe)
					vi_mod |= 2;
??!219reg vi.c:1554:m22sc %? %@2142sc!b4%ya 98?0?
%f> 	int p_reg;
	int lsug;
	int sug_pt;
	char \*sug;
	char \*_sug;
} ins_state;1??0?
1??+2m 11q0?
%f> 	int p_reg;
	int lsug;
	int sug_pt;4??0?
4??+2m 1220reg p OK vi.h:370:a42sc %? %@2152sc!1q0?
grp 1%f> 	int p_reg;.*?
	int lsug;.*?
(	int sug_pt;)7??0?
grp 07??m 1220reg p OK vi.h:370:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> void led_modeswap\(void\);
typedef struct \{
	int t_row;.*(#define ins_init\(is\) \\)
is\.t_row = -2; \\
is\.p_reg = xdefreg; \\8??0?
grp 08??-4m 1220reg p OK vi.h:370:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	int att;
} led_att;
extern sbuf \*led_attsb;.*(is\.lsug = 0; \\)
is\.sug_pt = -1; \\
is\.sug = NULL; \\9??0?
grp 09??-7m 1220reg p OK vi.h:370:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg vi.h:3702sc %? %@2132sc!0?
?0?
%f+ is\.p_reg = xdefreg; \\
is\.lsug = 0; \\
is\.sug_pt = -1; \\
is\.sug = NULL; \\
is\._sug = NULL; \\

1??0?
1??+2m 21q0?
%f+ is\.p_reg = xdefreg; \\
is\.lsug = 0; \\
is\.sug_pt = -1; \\4??0?
4??+2m 2220reg p OK vi.h:378:a42sc %? %@2152sc!1q0?
grp 1%f+ is\.p_reg = xdefreg; \\.*?
is\.lsug = 0; \\.*?
(is\.sug_pt = -1; \\)7??0?
grp 07??m 2220reg p OK vi.h:378:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> } ins_state;
#define ins_init\(is\) \\
is\.t_row = -2; \\.*(int led_prompt\(sbuf \*sb, char \*insert, int \*kmap, ins_state \*is, int ps, int flg\);)
int led_input\(sbuf \*sb, char \*post, int postn, int row, int flg, int \*pren\);
void led_render\(char \*s0, int cbeg, int cend\);8??0?
grp 08??-4m 2220reg p OK vi.h:378:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	int sug_pt;
	char \*sug;
	char \*_sug;.*(#define _led_render\(msg, row, col, beg, end, kill\) \\)
\{ \\
	int record = term_record; \\9??0?
grp 09??-7m 2220reg p OK vi.h:378:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg vi.h:3782sc %? %@2132sc!0?
?0?
%f+ extern int xshape;
extern int xorder;
extern int xts;
extern int xish;
extern int xgrp;
extern int xpac;1??0?
1??+2m 31q0?
%f+ extern int xshape;
extern int xorder;
extern int xts;4??0?
4??+2m 3220reg p OK vi.h:425:a42sc %? %@2152sc!1q0?
grp 1%f+ extern int xshape;.*?
extern int xorder;.*?
(extern int xts;)7??0?
grp 07??m 3220reg p OK vi.h:425:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> extern int xhlr;
extern int xled;
extern int xtd;.*(extern int xmpt;)
extern int xpr;
extern int xlim;8??0?
grp 08??-4m 3220reg p OK vi.h:425:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> extern int xhll;
extern int xhlw;
extern int xhlp;.*(extern int xseq;)
extern int xerr;
extern int xfr;9??0?
grp 09??-7m 3220reg p OK vi.h:425:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg vi.h:4252sc %? %@2132sc!0?
'\''1i 	int quickexit;
??!219reg vi.h:370:m12sc %? %@2142sc!0?
'\''2i is.quickexit = 0; \
??!219reg vi.h:378:m22sc %? %@2142sc!0?
'\''3i extern int xqe;
??!219reg vi.h:425:m32sc %? %@2142sc!vis 2b0wb1wb2wb3wb4w2q' > "$P2VIF"
EXINIT='%ya 97:? %@97' $VI -e 'conf.c' 'ex.c' 'led.c' 'vi.c' 'vi.h' "$P2VIF"

if [ $# -gt 0 ]; then
    export P2VI_PATCH="$P2VI_PATCH ${0##*/}"
    next=$1
    shift
    case $next in /*|./*|../*) "$next" "$@" ;; *) "./$next" "$@" ;; esac
fi

exit 0
=== PATCH2VI PATCH ===
diff --git a/conf.c b/conf.c
index ad9395c9..8709665d 100644
--- a/conf.c
+++ b/conf.c
@@ -297,7 +297,7 @@ return|select|switch|type|var))\\>", A(GR1, BL1 | SYN_BD, YE1)},
 (?:'[0-9]+)|([.%$]|[0-9 \t]*)?))(?:([-*-+/%])[ \t]*[0-9]+[ \t]*)*(?:[ \t]*\\|(?:[^|\\\\]|\\\\.?)*\\|?[ \t]*)*)[ \t]*\
 (?:([,;]#?)[ \t]*((?:\\|(?:[^|\\\\]|\\\\.?)*\\|?[ \t]*)*(?:(?:<(?:[^<\\\\]|\\\\.?)*<?|>(?:[^>\\\\]|\\\\.?)*>?)|\
 (?:'[0-9]+)|([.$]|[0-9 \t]*)?))(?:([-*-+/%])[ \t]*([0-9]+)[ \t]*)*(?:[ \t]*\\|(?:[^|\\\\]|\\\\.?)*\\|?)*[ \t]*)*)\
-((pac|pr|ai|ish|err|fr|ic|grp|mpt|rr|shape|seq|ts|td|order|hl[lwpr]?|left|lim|led|vis)\
+((qe|pac|pr|ai|ish|err|fr|ic|grp|mpt|rr|shape|seq|ts|td|order|hl[lwpr]?|left|lim|led|vis)\
 |[@&!dmj]|=\\?{0,1}|\\?{1,2}[?!]?|b[psx]?|p[uh]?|ac|e[f!]?!?|f[-+><tdp]?|inc|i|sc!?|\
 (?:g!?|s)[ \t]?(.)?|q!?|reg?\\+?|rd?|w(?:q!|[q!])?|u[czbd]|x!?|ya[!+]?|cm!?|cd?)?",
 		A(BL1 | SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1)},
diff --git a/ex.c b/ex.c
index f8505153..1f5e74a7 100644
--- a/ex.c
+++ b/ex.c
@@ -1,3 +1,4 @@
+int xqe = 1000;			/* exit insert via kj (delay in ms) */
 int xleft;			/* the first visible column */
 int xvis;			/* startup flags */
 int xai = 1;			/* autoindent option */
@@ -1647,6 +1648,7 @@ static void *eo_##opt(char *loc, char *cmd, char *arg) { inner }
 EO(pac) EO(pr) EO(ai) EO(err) EO(fr) EO(ish) EO(ic) EO(mpt)
 EO(rr) EO(shape) EO(seq) EO(td) EO(order) EO(hll) EO(hlw)
 EO(hlp) EO(hlr) EO(hl) EO(lim) EO(led) EO(vis)
+EO(qe)
 
 _EO(ts, xts = *arg ? eo_val(arg) : !xts; xts = MAX(0, xts); return NULL;)
 _EO(grp, xgrp = (*arg ? eo_val(arg) : !xgrp) * 2; xgrp = MAX(0, xgrp); return NULL;)
@@ -1714,6 +1716,7 @@ static struct excmd {
 	{"g", ec_glob},
 	EO(mpt),
 	{"m", ec_mark},
+	EO(qe),
 	{"q!", ec_quit},
 	{"q", ec_quit},
 	{"reg+", ec_regprint},
diff --git a/led.c b/led.c
index a38f7a06..50787614 100644
--- a/led.c
+++ b/led.c
@@ -1,4 +1,12 @@
 static sbuf *suggestsb;
+static int gettime_ms(void)
+{
+	struct timespec t;
+	if (clock_gettime(CLOCK_MONOTONIC, &t) < 0)
+		return 0;
+	return t.tv_sec * 1000 + t.tv_nsec / 1000000;
+}
+
 static sbuf *acsb;
 sbuf *led_attsb;
 
@@ -641,6 +649,17 @@ static int led_line(sbuf *sb, int ps, int pre, char **post, int postn, char **po
 				exbuf_load(ex_buf)
 			}
 			continue; }
+		case 'j':
+			if (xqe && (gettime_ms() - is->quickexit) < xqe) {
+				if (len - pre > 0 && sb->s[led_lastchar(sb->s)] == 'k') {
+					term_push("", 2);
+					continue;
+				}
+			}
+			goto _default;
+		case 'k':
+			is->quickexit = gettime_ms();
+_default:
 		default:
 			if (c == '\n' || TK_INT(c))
 				return c;
diff --git a/vi.c b/vi.c
index 2f4ccc2b..6c4368df 100644
--- a/vi.c
+++ b/vi.c
@@ -7,6 +7,7 @@
 #include <dirent.h>
 #include <signal.h>
 #include <unistd.h>
+#include <time.h>
 #include <poll.h>
 #include <termios.h>
 #include <limits.h>
@@ -1552,6 +1553,8 @@ void vi(int init)
 				}
 				xoff--;
 				rep_record()
+				if (xqe)
+					vi_mod |= 2;
 				vi_mod |= !xpac && xrow == orow ? 8 : 1;
 				break;
 			case 'J':
diff --git a/vi.h b/vi.h
index 0bb77c0b..c3f71714 100644
--- a/vi.h
+++ b/vi.h
@@ -368,6 +368,7 @@ typedef struct {
 	int p_reg;
 	int lsug;
 	int sug_pt;
+	int quickexit;
 	char *sug;
 	char *_sug;
 } ins_state;
@@ -376,6 +377,7 @@ is.t_row = -2; \
 is.p_reg = xdefreg; \
 is.lsug = 0; \
 is.sug_pt = -1; \
+is.quickexit = 0; \
 is.sug = NULL; \
 is._sug = NULL; \
 
@@ -423,6 +425,7 @@ extern int xtd;
 extern int xshape;
 extern int xorder;
 extern int xts;
+extern int xqe;
 extern int xish;
 extern int xgrp;
 extern int xpac;
