#!/bin/sh -e
# Generated by patch2vi from unified diff
# Available separators: 0003-0010 0013-0014 0016-0037 0112 0120-0121 0124 0126 0130 0132 0176-0377

VI=${VI:-vi}
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi binary" >&2
    exit 1
fi

# Env switches:
# Phase 1 (search/mark) reports nothing by default
#   DBG1=1 reports failures and which fallback anchor
#   resolved a group, QF1=1 also quits on failure
# Phase 2 (edits) reports and quits by default
#   DBG2=1 silences it, QF2=1 keeps going after an error
# INTR=1 enters vi at the failing code line in this
#   script, for state inspection mid execution

# Body too large for EXINIT/argv: stage it in a file
( : > /tmp/p2vi.$$ ) 2>/dev/null && P2VIF=/tmp/p2vi.$$ || P2VIF=./p2vi.$$
trap 'rm -f "$P2VIF"' EXIT

# Patch: conf.c ex.c lbuf.c vi.h
printf '%s%s%s\n' '|sc! |:vis 3ic 0217reg prFp FAIL %@219pr? %@212214reg ? %@217? %@211216reg ? %@220221reg vis 2q!1211reg ? %@221'\
"${DBG1:+213reg ? %@217? %@210215reg ? %@220}\
${DBG2:+ya!214ya!216}\
${QF1:+210reg vis 2q!1}\
${QF2:+ya!221}\
${INTR:+212reg |sc|vis 2:fr 0:e $0:83reg %@47:%f> 219reg %@219:&Q:b0:|sc! |:vis 3q1}"\
'fr 98b0%ya 98?0?
%f> \(\?:'\''\[0-9]\+\)\|\(\[\.\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\(\[0-9]\+\)\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\)\*\[ \\t]\*\)\*\)\\
\(\(pac\|pr\|ai\|ish\|err\|fr\|ic\|grp\|mpt\|rr\|shape\|seq\|ts\|td\|order\|hl\[lwpr]\?\|left\|lim\|led\|vis\)\\
\|\[@&!dmj]\|=\\\\\?\{0,1}\|\\\\\?\{1,2}\[\?!]\?\|b\[psx]\?\|p\[uh]\?\|ac\|e\[f!]\?!\?\|f\[-\+><tdp]\?\|inc\|i\|sc!\?\|\\
\(\?:g!\?\|s\)\[ \\t]\?\(\.\)\?\|q!\?\|reg\?\\\\\+\?\|rd\?\|w\(\?:q!\|\[q!]\)\?\|u\[czbd]\|x!\?\|ya\[!\+]\?\|cm!\?\|cd\?\)\?",
		A\(BL1 \| SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1\)},
	\{ex_ft, "\\\\\\\\\(\.\)", A\(AY1 \| SYN_BD, YE\)},
	\{ex_ft, "!\(\?:\[\^!\\\\\\\\]\|\\\\\\\\\.\?\)\*!\?\|%\(\?:#\|\[0-9]\+\|@\(\[0-9]\+\)\)\?", A\(WH1 \| SYN_BD, CY1\)},1??0?
1??+3m 11q0?
%f> \(\?:g!\?\|s\)\[ \\t]\?\(\.\)\?\|q!\?\|reg\?\\\\\+\?\|rd\?\|w\(\?:q!\|\[q!]\)\?\|u\[czbd]\|x!\?\|ya\[!\+]\?\|cm!\?\|cd\?\)\?",
		A\(BL1 \| SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1\)},
	\{ex_ft, "\\\\\\\\\(\.\)", A\(AY1 \| SYN_BD, YE\)},
	\{ex_ft, "!\(\?:\[\^!\\\\\\\\]\|\\\\\\\\\.\?\)\*!\?\|%\(\?:#\|\[0-9]\+\|@\(\[0-9]\+\)\)\?", A\(WH1 \| SYN_BD, CY1\)},2??0?
2??m 1220reg p OK conf.c:302:a22sc %? %@2152sc!1q0?
;0fr.,$f> ^\(\?:g!\?\|s\)\[ \\t]\?\(\.\)\?\|q!\?\|reg\?\\\\\+\?\|rd\?\|w\(\?:q!\|\[q!]\)\?\|u\[czbd]\|x!\?\|ya\[!\+]\?\|cm!\?\|cd\?\)\?",$3??0?
3??m 1220reg p OK conf.c:302:a32sc %? %@2152sc!fr 981qfr 980?
%f> \(\?:'\''\[0-9]\+\)\|\(\[\.\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\(\[0-9]\+\)\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\)\*\[ \\t]\*\)\*\)\\
\(\(pac\|pr\|ai\|ish\|err\|fr\|ic\|grp\|mpt\|rr\|shape\|seq\|ts\|td\|order\|hl\[lwpr]\?\|left\|lim\|led\|vis\)\\
\|\[@&!dmj]\|=\\\\\?\{0,1}\|\\\\\?\{1,2}\[\?!]\?\|b\[psx]\?\|p\[uh]\?\|ac\|e\[f!]\?!\?\|f\[-\+><tdp]\?\|inc\|i\|sc!\?\|\\4??0?
4??+3m 1220reg p OK conf.c:302:a42sc %? %@2152sc!1q0?
%f> 		A\(BL1 \| SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1\)},
	\{ex_ft, "\\\\\\\\\(\.\)", A\(AY1 \| SYN_BD, YE\)},
	\{ex_ft, "!\(\?:\[\^!\\\\\\\\]\|\\\\\\\\\.\?\)\*!\?\|%\(\?:#\|\[0-9]\+\|@\(\[0-9]\+\)\)\?", A\(WH1 \| SYN_BD, CY1\)},5??0?
5??-1m 1220reg p OK conf.c:302:a52sc %? %@2152sc!1q0?
%f> \(\?.'\''..-....\|....].........\*\)\?......\[.\*-.....\[ ....\(...9.\+........\*\(... \\t.......:.\^..\\........\..\)\*...........\*...\\
\(..a.\|..\|.i..s....r...\|..\|g......\|...s.a.....q..s\|...o.d.......w.r.....f.\|lim..e...i...
.\[.&.....\|=....0....\\...1.2.......b.p..........\?.a.\|...........-\+><tdp.\?..nc......\?\|.
.....\?\|....\\...\(..\?.......g\?..\+.\|.d.......!.\[..]..\|..c.......\?\|....\+]\?.....\|..\?\)...
........\| .YN_....... RE....,..E.............E,.......1...E...R.,..Y1. .A.\)..
..ex.....".\\...\.\).,.....1 ........, .E..,
.....ft,....\?....\\.\\..\|......\).!...\(..#...-9.\+..\(........\?"...\(....\|..Y._B....Y1...6??0?
6??+3m 1220reg p OK conf.c:302:a62sc %? %@2152sc!1q0?
grp 1%f> \(\?:'\''\[0-9]\+\)\|\(\[\.\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\(\[0-9]\+\)\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\)\*\[ \\t]\*\)\*\)\\.*?
\(\(pac\|pr\|ai\|ish\|err\|fr\|ic\|grp\|mpt\|rr\|shape\|seq\|ts\|td\|order\|hl\[lwpr]\?\|left\|lim\|led\|vis\)\\.*?
\|\[@&!dmj]\|=\\\\\?\{0,1}\|\\\\\?\{1,2}\[\?!]\?\|b\[psx]\?\|p\[uh]\?\|ac\|e\[f!]\?!\?\|f\[-\+><tdp]\?\|inc\|i\|sc!\?\|\\.*?
(\(\?:g!\?\|s\)\[ \\t]\?\(\.\)\?\|q!\?\|reg\?\\\\\+\?\|rd\?\|w\(\?:q!\|\[q!]\)\?\|u\[czbd]\|x!\?\|ya\[!\+]\?\|cm!\?\|cd\?\)\?",)7??0?
grp 07??m 1220reg p OK conf.c:302:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	\{ex_ft, ":\[ \\t]\*\(\(\(\(\?:\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\(\?:\(\?:<\(\?:\[\^<\\\\\\\\]\|\\\\\\\\\.\?\)\*<\?\|>\(\?:\[\^>\\\\\\\\]\|\\\\\\\\\.\?\)\*>\?\)\|\\
\(\?:'\''\[0-9]\+\)\|\(\[\.%\$]\|\[0-9 \\t]\*\)\?\)\)\(\?:\(\[-\*-\+/%]\)\[ \\t]\*\[0-9]\+\[ \\t]\*\)\*\(\?:\[ \\t]\*\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\)\[ \\t]\*\\
\(\?:\(\[,;]#\?\)\[ \\t]\*\(\(\?:\\\\\|\(\?:\[\^\|\\\\\\\\]\|\\\\\\\\\.\?\)\*\\\\\|\?\[ \\t]\*\)\*\(\?:\(\?:<\(\?:\[\^<\\\\\\\\]\|\\\\\\\\\.\?\)\*<\?\|>\(\?:\[\^>\\\\\\\\]\|\\\\\\\\\.\?\)\*>\?\)\|\\.*(	\{vs_ft, "\.\+", A\(AY1 \| SYN_BD\), 1},)
	\{vs_ft, "\(\^\[\?/]\)\|\(\\\\\\\\\[<>]\|\\\\\(\\\\\?\[:=!<>#]\|\\\\\[\\\\\^\?\(\(\?:\\\\\\\\\.\?\|\[\^\\\\]]\)\*\)]\|\\\\\[\|\[\.\^\$\\\\\(\)\*\+\|\?]\|\\\\\{\(\[0-9]\*\(,\)\?\[0-9]\*\)\?}\?\)\|\\\\\\\\\(\.\)",
		A\(SYN_BD, BL1, WH1, GR1, RE1, WH1, YE\)},8??0?
grp 08??-5m 1220reg p OK conf.c:302:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	\{ac_ft, "\[\^ \\t-/:-@\[-\^\{-~]\+\(\?:\(\\n\$\)\|\\n\)\|\\n\|\(\[\^\\n]\+\(\\n\)\)",
		A\(NA, SYN_BGMK\(RE1\), SYN_BGMK\(AY1\), SYN_BGMK\(AY\)\)},
	\{ac_ft, "\[\^ \\t-/:-@\[-\^\{-~]\+\$\|\(\.\+\$\)", A\(NA, SYN_BGMK\(AY1\)\)},.*(	\{vs_ft, "\(\\\\\\\\\)\(\.\)\(\?:\(-\)\(\?:\(\\\\\\\\\(\.\)\)\|\[\^\\\\\\\\\\\\]]\)\)\?\|\[\^\\\\\\\\\[\^]\(-\)\(\?:\(\\\\\\\\\(\.\)\)\|\.\)\|\\)
\[\^\\\\\\\\\[\^]\\\\\^\(-\)\(\?:\(\\\\\\\\\(\.\)\)\|\[\^\\\\\\\\]\)\|\\\\\^\(-\)\[\^\\\\\\\\]",
		A\(GR1 \| SYN_BD \| SYN_ATT, 1, GR1, AY1, YE, WH1, AY1, YE, WH1, AY1, YE, WH1, AY1, YE, WH1\), 2},9??0?
grp 09??-8m 1220reg p OK conf.c:302:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg conf.c:3022sc %? %@2132sc!0?
'\''1s/d]/dp]/??!219reg conf.c:302:m12sc %? %@2142sc!b1%ya 98?0?
%f> 	return xkwdrs \? NULL : xserr;
}

static int eo_val\(char \*arg\)
\{
	return uc_isdigit\(\*arg\) \|\| \(\*arg == '\''-'\'' && uc_isdigit\(arg\[1]\)\) \?1??0?
1??+2m 11q0?
%f> 	return xkwdrs \? NULL : xserr;
}

4??0?
4??+2m 1220reg p OK ex.c:1634:a42sc %? %@2152sc!1q0?
m 01;0grp 1%f> 		ex_krsset\(sb->s, \+1\);
		free\(sb->s\);
	}.*(EO\(pac\) EO\(pr\) EO\(ai\) EO\(err\) EO\(fr\) EO\(ish\) EO\(ic\) EO\(mpt\))
EO\(rr\) EO\(shape\) EO\(seq\) EO\(td\) EO\(order\) EO\(hll\) EO\(hlw\)
EO\(hlp\) EO\(hlr\) EO\(hl\) EO\(lim\) EO\(led\) EO\(vis\)8??0?
grp 08??-13m 1220reg p OK ex.c:1634:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 		ex_regesc\(sb, reg\.s, reg\.s \+ reg\.s_n, 1\);
		free\(reg\.s\);
		sbuf_nul\(sb\).*(_EO\(left,)
	if \(\*loc\)
		xleft = \(xcols / 2\) \* atoi\(loc\);9??0?
grp 09??-20m 1220reg p OK ex.c:1634:a92sc %? %@2152sc!'\''00?
1;4;8;9??!219reg ex.c:16342sc %? %@2132sc!0?
?0?
%f+ 	\{"uc", ec_setenc},
	\{"uz", ec_setenc},
	\{"ub", ec_setenc},
	\{"ud", ec_undoredo},
	EO\(shape\),
	EO\(seq\),1??0?
1??+2m 21q0?
%f+ 	\{"uc", ec_setenc},
	\{"uz", ec_setenc},
	\{"ub", ec_setenc},4??0?
4??+2m 2220reg p OK ex.c:1731:a42sc %? %@2152sc!1q0?
grp 1%f+ 	\{"uc", ec_setenc},.*?
	\{"uz", ec_setenc},.*?
(	\{"ub", ec_setenc},)7??0?
grp 07??m 2220reg p OK ex.c:1731:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	\{"wq", ec_write},
	\{"w!", ec_write},
	\{"w", ec_write},.*(	\{"sc!", ec_specials},)
	\{"sc", ec_specials},
	\{"s", ec_substitute},8??0?
grp 08??-4m 2220reg p OK ex.c:1731:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	EO\(rr\),
	\{"r", ec_read},
	\{"wq!", ec_write},.*(	\{"x!", ec_write},)
	\{"x", ec_write},
	\{"ya!", ec_yank},9??0?
grp 09??-7m 2220reg p OK ex.c:1731:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg ex.c:17312sc %? %@2132sc!0?
'\''1i static void *ec_undoleafs(char *loc, char *cmd, char *arg)
{
	char *s = lbuf_getleafs(xb);
	if (*arg)
		lbuf_setleaf(xb, atoi(arg));
	else
		ex_print(s, msg_ft)
	return NULL;
}

??!219reg ex.c:1634:m12sc %? %@2142sc!0?
'\''2i 	{"up", ec_undoleafs},
??!219reg ex.c:1731:m22sc %? %@2142sc!b2%ya 98?0?
%f> \{
	struct lbuf \*lb = emalloc\(sizeof\(\*lb\)\);
	memset\(lb, 0, sizeof\(\*lb\)\);
	lb->mark_sb\[0] = -1;
	lb->mark_se\[0] = -1;
	return lb;1??0?
1??+2m 11q0?
%f> \{
	struct lbuf \*lb = emalloc\(sizeof\(\*lb\)\);
	memset\(lb, 0, sizeof\(\*lb\)\);4??0?
4??+2m 1220reg p OK lbuf.c:4:a42sc %? %@2152sc!1q0?
grp 1%f> \{.*?
	struct lbuf \*lb = emalloc\(sizeof\(\*lb\)\);.*?
(	memset\(lb, 0, sizeof\(\*lb\)\);)7??0?
grp 07??m 1220reg p OK lbuf.c:4:a72sc %? %@2152sc!0?
1;4;7??!219reg lbuf.c:42sc %? %@2132sc!0?
?0?
%f+ 	return 0;
}

void lbuf_free\(struct lbuf \*lb\)
\{
	int i;1??0?
1??+2m 21q0?
%f+ 	return 0;
}

4??0?
4??+2m 2220reg p OK lbuf.c:78:a42sc %? %@2152sc!1q0?
m 01;0grp 1%f> 		return 1;
	\*pos = m\[0];
	\*off = MAX\(0, m\[1]\);.*(static int linelength\(char \*s\))
\{
	int len = dstrlen\(s, '\''\\n'\''\);8??0?
grp 08??-14m 2220reg p OK lbuf.c:78:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	else
		m = mark_find\(lb->mark, lb->mark_n, mk\);
	if \(!m \|\| m\[0] < 0\).*(/\* low-level line replacement \*/)
static int lbuf_replace\(struct lbuf \*lb, sbuf \*sb, char \*s, struct lopt \*lo, int n_del, int n_ins\)
\{9??0?
grp 09??-20m 2220reg p OK lbuf.c:78:a92sc %? %@2152sc!'\''00?
1;4;8;9??!219reg lbuf.c:782sc %? %@2132sc!0?
?0?
%f+ 	int i;
	for \(i = 0; i < lb->ln_n; i\+\+\)
		free\(lbuf_i\(lb, i\)\);
	for \(i = 0; i < lb->hist_n; i\+\+\)
		lopt_done\(&lb->hist\[i]\);
	free\(lb->hist\);
	free\(lb->mark\);
	free\(lb->ln\);1??0?
1??+3m 31q0?
%f+ 	for \(i = 0; i < lb->hist_n; i\+\+\)
		lopt_done\(&lb->hist\[i]\);
	free\(lb->hist\);
	free\(lb->mark\);
	free\(lb->ln\);2??0?
2??m 3220reg p OK lbuf.c:84:a22sc %? %@2152sc!1q0?
%f+ 	for \(i = 0; i < lb->hist_n; i\+\+\)
		lopt_done\(&lb->hist\[i]\);3??0?
3??m 3220reg p OK lbuf.c:84:a32sc %? %@2152sc!1q0?
%f+ 	int i;
	for \(i = 0; i < lb->ln_n; i\+\+\)
		free\(lbuf_i\(lb, i\)\);4??0?
4??+3m 3220reg p OK lbuf.c:84:a42sc %? %@2152sc!1q0?
%f+ 	free\(lb->hist\);
	free\(lb->mark\);
	free\(lb->ln\);5??0?
5??-2m 3220reg p OK lbuf.c:84:a52sc %? %@2152sc!1q0?
%f+ .i.t ..
.....\(.........< ..-.l.........
	.fr..\(...f.i...,.....
	....\(i.=.0. . .....>.i...n;..\+..
...o....o..\(&.....i.t.....
	..........is...
...e.....>......
..r.e.l.....\).6??0?
6??+3m 3220reg p OK lbuf.c:84:a62sc %? %@2152sc!1q0?
grp 1%f+ 	int i;.*?
	for \(i = 0; i < lb->ln_n; i\+\+\).*?
		free\(lbuf_i\(lb, i\)\);.*?
(	for \(i = 0; i < lb->hist_n; i\+\+\))7??0?
grp 07??m 3220reg p OK lbuf.c:84:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 		return 1;
	\*pos = m\[0];
	\*off = MAX\(0, m\[1]\);.*(static int linelength\(char \*s\))
\{
	int len = dstrlen\(s, '\''\\n'\''\);8??0?
grp 08??-8m 3220reg p OK lbuf.c:84:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	else
		m = mark_find\(lb->mark, lb->mark_n, mk\);
	if \(!m \|\| m\[0] < 0\).*(/\* low-level line replacement \*/)
static int lbuf_replace\(struct lbuf \*lb, sbuf \*sb, char \*s, struct lopt \*lo, int n_del, int n_ins\)
\{9??0?
grp 09??-14m 3220reg p OK lbuf.c:84:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg lbuf.c:842sc %? %@2132sc!0?
?0?
%f+ 		lopt_done\(lo\);
}

/\* append undo/redo history \*/
struct lopt \*lbuf_opt\(struct lbuf \*lb, int beg, int o1, int n_del\)
\{1??0?
1??+2m 41q0?
%f+ 		lopt_done\(lo\);
}

4??0?
4??+2m 4220reg p OK lbuf.c:160:a42sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	lb->mark_se\[0] = end;
	lb->mark_se\[1] = o2;
	if \(xseq < 0\).*(	struct lopt \*lo;)
	static struct lopt slo;
	if \(xseq < 0\)8??0?
grp 08??-4m 4220reg p OK lbuf.c:160:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> void lbuf_emark\(struct lbuf \*lb, struct lopt \*lo, int end, int o2\)
\{
	lbuf_copymark\(lo->mark_se, lb->mark_se\).*(		lo = &slo;)
	else \{
		for \(int i = lb->hist_u; i < lb->hist_n; i\+\+\)9??0?
grp 09??-7m 4220reg p OK lbuf.c:160:a92sc %? %@2152sc!'\''00?
1;4;8;9??!219reg lbuf.c:1602sc %? %@2132sc!0?
?0?
%f+ 	if \(xseq < 0\)
		lo = &slo;
	else \{
		for \(int i = lb->hist_u; i < lb->hist_n; i\+\+\)
			lopt_done\(&lb->hist\[i]\);
		lb->hist_n = lb->hist_u;
		if \(lb->hist_n == lb->hist_sz\) \{
			int sz = lb->hist_sz \+ \(lb->hist_sz \? lb->hist_sz : 128\);1??0?
1??+3m 51q0?
%f+ 		for \(int i = lb->hist_u; i < lb->hist_n; i\+\+\)
			lopt_done\(&lb->hist\[i]\);
		lb->hist_n = lb->hist_u;
		if \(lb->hist_n == lb->hist_sz\) \{
			int sz = lb->hist_sz \+ \(lb->hist_sz \? lb->hist_sz : 128\);2??0?
2??m 5220reg p OK lbuf.c:169:a22sc %? %@2152sc!1q0?
%f+ 		for \(int i = lb->hist_u; i < lb->hist_n; i\+\+\)
			lopt_done\(&lb->hist\[i]\);3??0?
3??m 5220reg p OK lbuf.c:169:a32sc %? %@2152sc!1q0?
%f+ 	if \(xseq < 0\)
		lo = &slo;
	else \{4??0?
4??+3m 5220reg p OK lbuf.c:169:a42sc %? %@2152sc!1q0?
%f+ 		lb->hist_n = lb->hist_u;
		if \(lb->hist_n == lb->hist_sz\) \{
			int sz = lb->hist_sz \+ \(lb->hist_sz \? lb->hist_sz : 128\);5??0?
5??-2m 5220reg p OK lbuf.c:169:a52sc %? %@2152sc!1q0?
%f+ ......s.q.. ..
...........;
.el.e..
.	.o. ..n....=.l......t......<...-........ ...\)
......._.....&.b->.........
		..-....._. .........._u;
	..f.......i....... .b..h.........
...... s. ....................>.i...s. \? l.....s...... .....6??0?
6??+3m 5220reg p OK lbuf.c:169:a62sc %? %@2152sc!1q0?
grp 1%f+ 	if \(xseq < 0\).*?
		lo = &slo;.*?
	else \{.*?
(		for \(int i = lb->hist_u; i < lb->hist_n; i\+\+\))7??0?
grp 07??m 5220reg p OK lbuf.c:169:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> \{
	struct lopt \*lo;
	static struct lopt slo;.*(			struct lopt \*hist = emalloc\(sz \* sizeof\(hist\[0]\)\);)
			memcpy\(hist, lb->hist, lb->hist_n \* sizeof\(hist\[0]\)\);
			free\(lb->hist\);8??0?
grp 08??-5m 5220reg p OK lbuf.c:169:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	if \(xseq < 0\)
		lopt_done\(lo\);
}.*(			lb->hist = hist;)
			lb->hist_sz = sz;
		}9??0?
grp 09??-8m 5220reg p OK lbuf.c:169:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg lbuf.c:1692sc %? %@2132sc!0?
?0?
%f+ void lbuf_saved\(struct lbuf \*lb, int clear\)
\{
	if \(clear\) \{
		for \(int i = 0; i < lb->hist_n; i\+\+\)
			lopt_done\(&lb->hist\[i]\);
		lb->hist_n = 0;
		lb->hist_u = 0;1??0?
1??+3m 61q0?
%f+ 		for \(int i = 0; i < lb->hist_n; i\+\+\)
			lopt_done\(&lb->hist\[i]\);
		lb->hist_n = 0;
		lb->hist_u = 0;2??0?
2??m 6220reg p OK lbuf.c:453:a22sc %? %@2152sc!1q0?
%f+ 		for \(int i = 0; i < lb->hist_n; i\+\+\)
			lopt_done\(&lb->hist\[i]\);3??0?
3??m 6220reg p OK lbuf.c:453:a32sc %? %@2152sc!1q0?
%f+ void lbuf_saved\(struct lbuf \*lb, int clear\)
\{
	if \(clear\) \{4??0?
4??+3m 6220reg p OK lbuf.c:453:a42sc %? %@2152sc!1q0?
%f+ 		lb->hist_n = 0;
		lb->hist_u = 0;5??0?
5??-2m 6220reg p OK lbuf.c:453:a52sc %? %@2152sc!1q0?
%f+ ...d.l.u...av...s.......b....l...i.t c...r.
\{
	i...........
.	....\(..t . ...... <.l......t_...i.\+.
.....p._..................;
.	.......t...=...
.......i...u = ..6??0?
6??+3m 6220reg p OK lbuf.c:453:a62sc %? %@2152sc!1q0?
grp 1%f+ void lbuf_saved\(struct lbuf \*lb, int clear\).*?
\{.*?
	if \(clear\) \{.*?
(		for \(int i = 0; i < lb->hist_n; i\+\+\))7??0?
grp 07??m 6220reg p OK lbuf.c:453:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	}
	lb->modified = lb->hist_u != lb->saved;
	return 0;.*(int lbuf_indents\(struct lbuf \*lb, int r\))
\{
	char \*ln = lbuf_get\(lb, r\);8??0?
grp 08??-9m 6220reg p OK lbuf.c:453:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	} else \{
		lbuf_copymark\(lb->mark_sb, lb->tmp_mark\)
		lbuf_copymark\(lb->mark_se, \(lb->tmp_mark \+ 2\)\).*(	int o;)
	if \(!ln\)
		return 0;9??0?
grp 09??-12m 6220reg p OK lbuf.c:453:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg lbuf.c:4532sc %? %@2132sc!0?
?0?
%f+ 		lb->hist_n = 0;
		lb->hist_u = 0;
	}
	lb->modified = 0;
	lb->saved = lb->hist_u;1??0?
1??+1m 71q0?
%f+ 		lb->hist_n = 0;
		lb->hist_u = 0;4??0?
4??+1m 7220reg p OK lbuf.c:456:a42sc %? %@2152sc!1q0?
grp 1%f+ 		lb->hist_n = 0;.*?
(		lb->hist_u = 0;)7??0?
grp 07??m 7220reg p OK lbuf.c:456:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	}
	lb->modified = lb->hist_u != lb->saved;
	return 0;.*(int lbuf_indents\(struct lbuf \*lb, int r\))
\{
	char \*ln = lbuf_get\(lb, r\);8??0?
grp 08??-6m 7220reg p OK lbuf.c:456:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	} else \{
		lbuf_copymark\(lb->mark_sb, lb->tmp_mark\)
		lbuf_copymark\(lb->mark_se, \(lb->tmp_mark \+ 2\)\).*(	int o;)
	if \(!ln\)
		return 0;9??0?
grp 09??-9m 7220reg p OK lbuf.c:456:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg lbuf.c:4562sc %? %@2132sc!0?
'\''1i 	sbuf_make(lb->rehist, 128)
??!219reg lbuf.c:4:m12sc %? %@2142sc!0?
'\''2i static void lbuf_freeleafs(struct lbuf *lb)
{
	char *ptr = lb->rehist->s;
	struct lopt *hist;
	int n, i, c;
	sbuf *freedsb; sbuf_make(freedsb, 128)
	for (i = 0; i < lb->hist_n; i++) {
		sbuf_mem(freedsb, &lb->hist[i].mark, (int)sizeof(void*))
		lopt_done(&lb->hist[i]);
	}
	while (lb->rehist->s_n > ptr - lb->rehist->s) {
		n = *(int*)ptr;
		hist = (struct lopt*)&ptr[sizeof(n)];
		for (i = 0; i < n; i++) {
			for (c = 0; c < freedsb->s_n; c+=sizeof(void*))
				if (*(void**)((char*)freedsb->s + c) == hist[i].mark)
					goto skip;
			sbuf_mem(freedsb, &hist[i].mark, (int)sizeof(void*))
			lopt_done(&hist[i]);
			skip:;
		}
		ptr += n * sizeof(lb->hist[0]) + sizeof(n);
	}
	sbuf_free(lb->rehist)
	sbuf_free(freedsb)
}

??!219reg lbuf.c:78:m22sc %? %@2142sc!0?
'\''3,#+1c 	lbuf_freeleafs(lb);
??!219reg lbuf.c:84:m32sc %? %@2142sc!0?
'\''4i void lbuf_setleaf(struct lbuf *lb, int leaf)
{
	char *ptr1 = lb->rehist->s, *ptr2;
	int n, i, off = -1;
	for (i = 0; lb->rehist->s_n > ptr1 - lb->rehist->s; i++) {
		n = *(int*)ptr1;
		if (i == leaf) {
			off = ptr1 - lb->rehist->s;
			break;
		}
		ptr1 += n * sizeof(lb->hist[0]) + sizeof(lb->hist_n);
	}
	if (off < 0)
		return;
	while (!lbuf_undo(lb, &xrow, &xoff));
	i = lb->hist_n - lb->hist_u;
	if (i) {
		sbuf_mem(lb->rehist, &lb->hist_n, (int)sizeof(lb->hist_n))
		sbuf_mem(lb->rehist, lb->hist, (int)(lb->hist_n * sizeof(lb->hist[0])));
		ptr1 = lb->rehist->s + off;
		lb->hist_n = n;
		lb->hist_u = 0;
		if (lb->hist_n >= lb->hist_sz) {
			free(lb->hist);
			int sz = lb->hist_n * 2;
			struct lopt *hist = emalloc(sz * sizeof(hist[0]));
			lb->hist = hist;
			lb->hist_sz = sz;
		}
		memcpy(lb->hist, &ptr1[sizeof(n)], n * sizeof(lb->hist[0]));
		ptr2 = &ptr1[n * sizeof(lb->hist[0]) + sizeof(n)];
		if (lb->rehist->s_n > ptr2 - lb->rehist->s)
			memmove(ptr1, ptr2, lb->rehist->s_n - (ptr2 - lb->rehist->s));
		lb->rehist->s_n -= ptr2 - ptr1;
		while (!lbuf_redo(lb, &xrow, &xoff));
	}
}

char *lbuf_getleafs(struct lbuf *lb)
{
	char *ptr = lb->rehist->s, *bptr;
	int n, i;
	char buf[100];
	sbuf_smake(sb, 128)
	for (i = 0; lb->rehist->s_n > ptr - lb->rehist->s; i++) {
		n = *(int*)ptr;
		bptr = itoa(i, buf);
		*bptr++ = '\''='\'';
		bptr = itoa(n, bptr);
		*bptr++ = '\''|'\'';
		*bptr++ = '\''\0'\'';
		sbuf_str(sb, buf);
		ptr += n * sizeof(lb->hist[0]) + sizeof(lb->hist_n);
	}
	sbufn_ret(sb, sb->s)
}

??!219reg lbuf.c:160:m42sc %? %@2142sc!0?
'\''5,#+1c 		int i = lb->hist_n - lb->hist_u;
		if (i) {
			sbuf_mem(lb->rehist, &lb->hist_n, (int)sizeof(lb->hist_n))
			sbuf_mem(lb->rehist, lb->hist, (int)(lb->hist_n * sizeof(lb->hist[0])));
		}
??!219reg lbuf.c:169:m52sc %? %@2142sc!0?
'\''6,#+1c 		lbuf_freeleafs(lb);
??!219reg lbuf.c:453:m62sc %? %@2142sc!0?
'\''7i 		sbuf_make(lb->rehist, 128)
??!219reg lbuf.c:456:m72sc %? %@2142sc!b3%ya 98?0?
%f> struct lbuf \{
	char \*\*ln;			/\* buffer lines \*/
	struct lopt \*hist;		/\* buffer history \*/
	int \*mark;			/\* mark id, row & off triplets \*/
	int mark_n;			/\* number of marks in mark\[] \*/
	int mark_sb\[2];			/\* \[ mark row & off \*/1??0?
1??+2m 11q0?
%f> struct lbuf \{
	char \*\*ln;			/\* buffer lines \*/
	struct lopt \*hist;		/\* buffer history \*/4??0?
4??+2m 1220reg p OK vi.h:139:a42sc %? %@2152sc!1q0?
grp 1%f> struct lbuf \{.*?
	char \*\*ln;			/\* buffer lines \*/.*?
(	struct lopt \*hist;		/\* buffer history \*/)7??0?
grp 07??m 1220reg p OK vi.h:139:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	int len;
	int grec;
};.*(	int mark_se\[2];			/\* ] mark row & off \*/)
	int tmp_mark\[4];		/\* aux mark state \*/
	int ln_n;			/\* number of lines in ln\[] \*/8??0?
grp 08??-4m 1220reg p OK vi.h:139:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	int ref;		/\* ins/del ref exists on lbuf \*/
};
struct linfo \{.*(	int ln_sz;			/\* size of ln\[] \*/)
	int useq;			/\* current operation sequence \*/
	int modified;			/\* modification state \*/9??0?
grp 09??-7m 1220reg p OK vi.h:139:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg vi.h:1392sc %? %@2132sc!0?
?0?
%f+ int lbuf_findchar\(struct lbuf \*lb, char \*cs, int cmd, int n, int \*r, int \*o\);
int lbuf_search\(struct lbuf \*lb, rset \*re, int dir, int beg, int end, int pskip,
		int nskip, int \*r, int \*o\);
#define lbuf_dedup\(lb, str, n\) \\
\{ for \(int i = 0; i < lbuf_len\(lb\);\) \{ \\
	char \*s = lbuf_get\(lb, i\); \\1??0?
1??+2m 21q0?
%f+ int lbuf_findchar\(struct lbuf \*lb, char \*cs, int cmd, int n, int \*r, int \*o\);
int lbuf_search\(struct lbuf \*lb, rset \*re, int dir, int beg, int end, int pskip,
		int nskip, int \*r, int \*o\);4??0?
4??+2m 2220reg p OK vi.h:181:a42sc %? %@2152sc!1q0?
grp 1%f+ int lbuf_findchar\(struct lbuf \*lb, char \*cs, int cmd, int n, int \*r, int \*o\);.*?
int lbuf_search\(struct lbuf \*lb, rset \*re, int dir, int beg, int end, int pskip,.*?
(		int nskip, int \*r, int \*o\);)7??0?
grp 07??m 2220reg p OK vi.h:181:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> int lbuf_indents\(struct lbuf \*lb, int r\);
int lbuf_eol\(struct lbuf \*lb, int r, int state\);
int lbuf_next\(struct lbuf \*lb, int dir, int \*r, int \*o\);.*(	if \(n == lbuf_s\(s\)->len && !memcmp\(str, s, n\)\) \\)
		lbuf_edit\(lb, NULL, i, i \+ 1, 0, 0\); \\
	else \\8??0?
grp 08??-4m 2220reg p OK vi.h:181:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> int lbuf_undo\(struct lbuf \*lb, int \*row, int \*off\);
int lbuf_redo\(struct lbuf \*lb, int \*row, int \*off\);
void lbuf_saved\(struct lbuf \*lb, int clear\);.*(/\* regions \*/)
int lbuf_sectionbeg\(struct lbuf \*lb, int dir, int \*row, int \*off, int ch\);
int lbuf_wordbeg\(struct lbuf \*lb, int big, int dir, int \*row, int \*off\);9??0?
grp 09??-10m 2220reg p OK vi.h:181:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg vi.h:1812sc %? %@2132sc!0?
'\''1i 	sbuf *rehist;		/* alternate redo timelines */
??!219reg vi.h:139:m12sc %? %@2142sc!0?
'\''2i void lbuf_setleaf(struct lbuf *lb, int leaf);
char *lbuf_getleafs(struct lbuf *lb);
??!219reg vi.h:181:m22sc %? %@2142sc!vis 2b0wb1wb2wb3w2q' > "$P2VIF"
EXINIT='%ya 97:? %@97' $VI -e 'conf.c' 'ex.c' 'lbuf.c' 'vi.h' "$P2VIF"

if [ $# -gt 0 ]; then
    export P2VI_PATCH="$P2VI_PATCH ${0##*/}"
    next=$1
    shift
    case $next in /*|./*|../*) "$next" "$@" ;; *) "./$next" "$@" ;; esac
fi

exit 0
=== PATCH2VI PATCH ===
diff --git a/conf.c b/conf.c
index ad9395c9..5442c9e1 100644
--- a/conf.c
+++ b/conf.c
@@ -299,7 +299,7 @@ return|select|switch|type|var))\\>", A(GR1, BL1 | SYN_BD, YE1)},
 (?:'[0-9]+)|([.$]|[0-9 \t]*)?))(?:([-*-+/%])[ \t]*([0-9]+)[ \t]*)*(?:[ \t]*\\|(?:[^|\\\\]|\\\\.?)*\\|?)*[ \t]*)*)\
 ((pac|pr|ai|ish|err|fr|ic|grp|mpt|rr|shape|seq|ts|td|order|hl[lwpr]?|left|lim|led|vis)\
 |[@&!dmj]|=\\?{0,1}|\\?{1,2}[?!]?|b[psx]?|p[uh]?|ac|e[f!]?!?|f[-+><tdp]?|inc|i|sc!?|\
-(?:g!?|s)[ \t]?(.)?|q!?|reg?\\+?|rd?|w(?:q!|[q!])?|u[czbd]|x!?|ya[!+]?|cm!?|cd?)?",
+(?:g!?|s)[ \t]?(.)?|q!?|reg?\\+?|rd?|w(?:q!|[q!])?|u[czbdp]|x!?|ya[!+]?|cm!?|cd?)?",
 		A(BL1 | SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1)},
 	{ex_ft, "\\\\(.)", A(AY1 | SYN_BD, YE)},
 	{ex_ft, "!(?:[^!\\\\]|\\\\.?)*!?|%(?:#|[0-9]+|@([0-9]+))?", A(WH1 | SYN_BD, CY1)},
diff --git a/ex.c b/ex.c
index f8505153..2fbe14d5 100644
--- a/ex.c
+++ b/ex.c
@@ -1632,6 +1632,16 @@ static void *ec_krsset(char *loc, char *cmd, char *arg)
 	return xkwdrs ? NULL : xserr;
 }
 
+static void *ec_undoleafs(char *loc, char *cmd, char *arg)
+{
+	char *s = lbuf_getleafs(xb);
+	if (*arg)
+		lbuf_setleaf(xb, atoi(arg));
+	else
+		ex_print(s, msg_ft)
+	return NULL;
+}
+
 static int eo_val(char *arg)
 {
 	return uc_isdigit(*arg) || (*arg == '-' && uc_isdigit(arg[1])) ?
@@ -1729,6 +1739,7 @@ static struct excmd {
 	{"uc", ec_setenc},
 	{"uz", ec_setenc},
 	{"ub", ec_setenc},
+	{"up", ec_undoleafs},
 	{"ud", ec_undoredo},
 	EO(shape),
 	EO(seq),
diff --git a/lbuf.c b/lbuf.c
index f0e754e6..6c94d5b0 100644
--- a/lbuf.c
+++ b/lbuf.c
@@ -2,6 +2,7 @@ struct lbuf *lbuf_make(void)
 {
 	struct lbuf *lb = emalloc(sizeof(*lb));
 	memset(lb, 0, sizeof(*lb));
+	sbuf_make(lb->rehist, 128)
 	lb->mark_sb[0] = -1;
 	lb->mark_se[0] = -1;
 	return lb;
@@ -76,13 +77,39 @@ int lbuf_jump(struct lbuf *lb, int mk, int *pos, int *off)
 	return 0;
 }
 
+static void lbuf_freeleafs(struct lbuf *lb)
+{
+	char *ptr = lb->rehist->s;
+	struct lopt *hist;
+	int n, i, c;
+	sbuf *freedsb; sbuf_make(freedsb, 128)
+	for (i = 0; i < lb->hist_n; i++) {
+		sbuf_mem(freedsb, &lb->hist[i].mark, (int)sizeof(void*))
+		lopt_done(&lb->hist[i]);
+	}
+	while (lb->rehist->s_n > ptr - lb->rehist->s) {
+		n = *(int*)ptr;
+		hist = (struct lopt*)&ptr[sizeof(n)];
+		for (i = 0; i < n; i++) {
+			for (c = 0; c < freedsb->s_n; c+=sizeof(void*))
+				if (*(void**)((char*)freedsb->s + c) == hist[i].mark)
+					goto skip;
+			sbuf_mem(freedsb, &hist[i].mark, (int)sizeof(void*))
+			lopt_done(&hist[i]);
+			skip:;
+		}
+		ptr += n * sizeof(lb->hist[0]) + sizeof(n);
+	}
+	sbuf_free(lb->rehist)
+	sbuf_free(freedsb)
+}
+
 void lbuf_free(struct lbuf *lb)
 {
 	int i;
 	for (i = 0; i < lb->ln_n; i++)
 		free(lbuf_i(lb, i));
-	for (i = 0; i < lb->hist_n; i++)
-		lopt_done(&lb->hist[i]);
+	lbuf_freeleafs(lb);
 	free(lb->hist);
 	free(lb->mark);
 	free(lb->ln);
@@ -158,6 +185,63 @@ void lbuf_emark(struct lbuf *lb, struct lopt *lo, int end, int o2)
 		lopt_done(lo);
 }
 
+void lbuf_setleaf(struct lbuf *lb, int leaf)
+{
+	char *ptr1 = lb->rehist->s, *ptr2;
+	int n, i, off = -1;
+	for (i = 0; lb->rehist->s_n > ptr1 - lb->rehist->s; i++) {
+		n = *(int*)ptr1;
+		if (i == leaf) {
+			off = ptr1 - lb->rehist->s;
+			break;
+		}
+		ptr1 += n * sizeof(lb->hist[0]) + sizeof(lb->hist_n);
+	}
+	if (off < 0)
+		return;
+	while (!lbuf_undo(lb, &xrow, &xoff));
+	i = lb->hist_n - lb->hist_u;
+	if (i) {
+		sbuf_mem(lb->rehist, &lb->hist_n, (int)sizeof(lb->hist_n))
+		sbuf_mem(lb->rehist, lb->hist, (int)(lb->hist_n * sizeof(lb->hist[0])));
+		ptr1 = lb->rehist->s + off;
+		lb->hist_n = n;
+		lb->hist_u = 0;
+		if (lb->hist_n >= lb->hist_sz) {
+			free(lb->hist);
+			int sz = lb->hist_n * 2;
+			struct lopt *hist = emalloc(sz * sizeof(hist[0]));
+			lb->hist = hist;
+			lb->hist_sz = sz;
+		}
+		memcpy(lb->hist, &ptr1[sizeof(n)], n * sizeof(lb->hist[0]));
+		ptr2 = &ptr1[n * sizeof(lb->hist[0]) + sizeof(n)];
+		if (lb->rehist->s_n > ptr2 - lb->rehist->s)
+			memmove(ptr1, ptr2, lb->rehist->s_n - (ptr2 - lb->rehist->s));
+		lb->rehist->s_n -= ptr2 - ptr1;
+		while (!lbuf_redo(lb, &xrow, &xoff));
+	}
+}
+
+char *lbuf_getleafs(struct lbuf *lb)
+{
+	char *ptr = lb->rehist->s, *bptr;
+	int n, i;
+	char buf[100];
+	sbuf_smake(sb, 128)
+	for (i = 0; lb->rehist->s_n > ptr - lb->rehist->s; i++) {
+		n = *(int*)ptr;
+		bptr = itoa(i, buf);
+		*bptr++ = '=';
+		bptr = itoa(n, bptr);
+		*bptr++ = '|';
+		*bptr++ = '\0';
+		sbuf_str(sb, buf);
+		ptr += n * sizeof(lb->hist[0]) + sizeof(lb->hist_n);
+	}
+	sbufn_ret(sb, sb->s)
+}
+
 /* append undo/redo history */
 struct lopt *lbuf_opt(struct lbuf *lb, int beg, int o1, int n_del)
 {
@@ -166,8 +250,11 @@ struct lopt *lbuf_opt(struct lbuf *lb, int beg, int o1, int n_del)
 	if (xseq < 0)
 		lo = &slo;
 	else {
-		for (int i = lb->hist_u; i < lb->hist_n; i++)
-			lopt_done(&lb->hist[i]);
+		int i = lb->hist_n - lb->hist_u;
+		if (i) {
+			sbuf_mem(lb->rehist, &lb->hist_n, (int)sizeof(lb->hist_n))
+			sbuf_mem(lb->rehist, lb->hist, (int)(lb->hist_n * sizeof(lb->hist[0])));
+		}
 		lb->hist_n = lb->hist_u;
 		if (lb->hist_n == lb->hist_sz) {
 			int sz = lb->hist_sz + (lb->hist_sz ? lb->hist_sz : 128);
@@ -450,10 +537,10 @@ int lbuf_redo(struct lbuf *lb, int *row, int *off)
 void lbuf_saved(struct lbuf *lb, int clear)
 {
 	if (clear) {
-		for (int i = 0; i < lb->hist_n; i++)
-			lopt_done(&lb->hist[i]);
+		lbuf_freeleafs(lb);
 		lb->hist_n = 0;
 		lb->hist_u = 0;
+		sbuf_make(lb->rehist, 128)
 	}
 	lb->modified = 0;
 	lb->saved = lb->hist_u;
diff --git a/vi.h b/vi.h
index 0bb77c0b..4fa003bc 100644
--- a/vi.h
+++ b/vi.h
@@ -137,6 +137,7 @@ struct linfo {
 struct lbuf {
 	char **ln;			/* buffer lines */
 	struct lopt *hist;		/* buffer history */
+	sbuf *rehist;		/* alternate redo timelines */
 	int *mark;			/* mark id, row & off triplets */
 	int mark_n;			/* number of marks in mark[] */
 	int mark_sb[2];			/* [ mark row & off */
@@ -179,6 +180,8 @@ int lbuf_next(struct lbuf *lb, int dir, int *r, int *o);
 int lbuf_findchar(struct lbuf *lb, char *cs, int cmd, int n, int *r, int *o);
 int lbuf_search(struct lbuf *lb, rset *re, int dir, int beg, int end, int pskip,
 		int nskip, int *r, int *o);
+void lbuf_setleaf(struct lbuf *lb, int leaf);
+char *lbuf_getleafs(struct lbuf *lb);
 #define lbuf_dedup(lb, str, n) \
 { for (int i = 0; i < lbuf_len(lb);) { \
 	char *s = lbuf_get(lb, i); \
