#!/bin/sh -e
# Generated by patch2vi from unified diff
# Available separators: 0003-0010 0013-0014 0016-0037 0112 0120-0121 0132 0177-0377

VI=${VI:-vi}
if ! $VI -? 2>&1 | grep -q 'Nextvi'; then
    echo "Error: $VI is not nextvi" >&2
    echo "Set VI environment variable to point to nextvi binary" >&2
    exit 1
fi

# Env switches:
# Phase 1 (search/mark) reports nothing by default
#   DBG1=1 reports failures and which fallback anchor
#   resolved a group, QF1=1 also quits on failure
# Phase 2 (edits) reports and quits by default
#   DBG2=1 silences it, QF2=1 keeps going after an error
# INTR=1 enters vi at the failing code line in this
#   script, for state inspection mid execution

# Body too large for EXINIT/argv: stage it in a file
( : > /tmp/p2vi.$$.d ) 2>/dev/null && P2VIF=/tmp/p2vi.$$ || P2VIF=./p2vi.$$
trap 'rm -f "$P2VIF".*' EXIT

printf '%s%s%s\n' '|sc! |:vis 3ic 0217reg prFp FAIL %@219pr? %@212214reg ? %@217? %@211216reg ? %@220221reg vis 2q!1211reg ? %@221'\
"229reg  $P2VI_PATCH \
${DBG1:+213reg ? %@217? %@210215reg ? %@220}\
${DBG2:+ya!214ya!216}\
${QF1:+210reg vis 2q!1}\
${QF2:+ya!221}\
${INTR:+212reg |sc|vis 2:fr 0:e $0:83reg %@47:%f> 219reg %@219:&Q:b0:|sc! |:vis 3q1}"\
'230reg 0fr 2290?
f> [ /]lsp[.]sh 20??b320?? %ya 231230reg 1231??0?
fr 98211reg fr 230f> 1??!? %@221fr 98b01b110?
b2%ya 972sc %? %@972sc!b11211reg ? %@2210?
2sc %? %@2312sc!vis 2b0wb1w2q' > "$P2VIF".d
printf '%s\n' '2sc!fr 98b0%ya 98?0?
%f> 		A\(GR1 \| SYN_BD \| SYN_ATT, 1, GR1, AY1, YE, WH1, AY1, YE, WH1, AY1, YE, WH1, AY1, YE, WH1\), 2},

	\{bar_ft, "\^\(\\"\.\*\\"\)\.\*\(\\\\\[\[wrf]\\\\]\)\.\*\$", A\(AY1 \| SYN_BD, BL, RE\)},
	\{bar_ft, "\^<\(\.\+\)> \(\?:\[\^ ]\+ \)\*\(\[0-9]\+L\) \(\[0-9]\+W\) \(S\[0-9]\+\) \(O\[0-9]\+\) \(C\[0-9]\+\)\$",
		A\(AY1 \| SYN_BD, RE1, BL, YE, MA, CY1, YE1\)},
	\{bar_ft, "\^\(\\"\.\*\\"\)\.\* \(\[0-9]\{1,3}%\) \(L\[0-9]\+\) \(C\[0-9]\+\) \(B-\?\[0-9]\+\)\?\.\*\$",
		A\(AY1 \| SYN_BD, BL, RE1, BL, YE1, GR\)},1??0?
1??+3m 11q0?
%f> 	\{bar_ft, "\^<\(\.\+\)> \(\?:\[\^ ]\+ \)\*\(\[0-9]\+L\) \(\[0-9]\+W\) \(S\[0-9]\+\) \(O\[0-9]\+\) \(C\[0-9]\+\)\$",
		A\(AY1 \| SYN_BD, RE1, BL, YE, MA, CY1, YE1\)},
	\{bar_ft, "\^\(\\"\.\*\\"\)\.\* \(\[0-9]\{1,3}%\) \(L\[0-9]\+\) \(C\[0-9]\+\) \(B-\?\[0-9]\+\)\?\.\*\$",
		A\(AY1 \| SYN_BD, BL, RE1, BL, YE1, GR\)},2??0?
2??m 1220reg p OK conf.c:315:a22sc %? %@2152sc!1q0?
;0fr.,$f> ^	\{bar_ft, "\^<\(\.\+\)> \(\?:\[\^ ]\+ \)\*\(\[0-9]\+L\) \(\[0-9]\+W\) \(S\[0-9]\+\) \(O\[0-9]\+\) \(C\[0-9]\+\)\$",$3??0?
3??m 1220reg p OK conf.c:315:a32sc %? %@2152sc!fr 981qfr 980?
%f> 		A\(GR1 \| SYN_BD \| SYN_ATT, 1, GR1, AY1, YE, WH1, AY1, YE, WH1, AY1, YE, WH1, AY1, YE, WH1\), 2},

	\{bar_ft, "\^\(\\"\.\*\\"\)\.\*\(\\\\\[\[wrf]\\\\]\)\.\*\$", A\(AY1 \| SYN_BD, BL, RE\)},4??0?
4??+3m 1220reg p OK conf.c:315:a42sc %? %@2152sc!1q0?
%f> 		A\(AY1 \| SYN_BD, RE1, BL, YE, MA, CY1, YE1\)},
	\{bar_ft, "\^\(\\"\.\*\\"\)\.\* \(\[0-9]\{1,3}%\) \(L\[0-9]\+\) \(C\[0-9]\+\) \(B-\?\[0-9]\+\)\?\.\*\$",
		A\(AY1 \| SYN_BD, BL, RE1, BL, YE1, GR\)},5??0?
5??-1m 1220reg p OK conf.c:315:a52sc %? %@2152sc!1q0?
%f> .	........S....... .....T...1....., .Y...Y., W..,..... Y.,........1...E...... ..1,..E,..H.....}.

	......t.."......\\...\*.......f.\\.].........A.. \|.SYN_....B........
......f.. "\^...\+.> \(.:\[. ....\*.....]..\) \(\[.............9..\) \(....9......\[0......".
...\(A...\| ..N.BD..R.....L,.....MA,..Y., ......
	......t......"....\)\.........\{....%\).....-..........9... \(...\[0-.]........
...\(A.. ..S...........R...............\)..6??0?
6??+3m 1220reg p OK conf.c:315:a62sc %? %@2152sc!1q0?
grp 1%f> 		A\(GR1 \| SYN_BD \| SYN_ATT, 1, GR1, AY1, YE, WH1, AY1, YE, WH1, AY1, YE, WH1, AY1, YE, WH1\), 2},.*?
.*?
	\{bar_ft, "\^\(\\"\.\*\\"\)\.\*\(\\\\\[\[wrf]\\\\]\)\.\*\$", A\(AY1 \| SYN_BD, BL, RE\)},.*?
(	\{bar_ft, "\^<\(\.\+\)> \(\?:\[\^ ]\+ \)\*\(\[0-9]\+L\) \(\[0-9]\+W\) \(S\[0-9]\+\) \(O\[0-9]\+\) \(C\[0-9]\+\)\$",)7??0?
grp 07??m 1220reg p OK conf.c:315:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 		A\(SYN_BD, BL1, WH1, GR1, RE1, WH1, YE\)},
	\{vs_ft, "\(\\\\\\\\\)\(\.\)\(\?:\(-\)\(\?:\(\\\\\\\\\(\.\)\)\|\[\^\\\\\\\\\\\\]]\)\)\?\|\[\^\\\\\\\\\[\^]\(-\)\(\?:\(\\\\\\\\\(\.\)\)\|\.\)\|\\
\[\^\\\\\\\\\[\^]\\\\\^\(-\)\(\?:\(\\\\\\\\\(\.\)\)\|\[\^\\\\\\\\]\)\|\\\\\^\(-\)\[\^\\\\\\\\]",.*(	\{msg_ft, "\.\+", A\(AY1 \| SYN_BD\)},)
};
const int hlslen = LEN\(hls\);8??0?
grp 08??-9m 1220reg p OK conf.c:315:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 		A\(BL1 \| SYN_BD, RE, RE, RE, RE, WH1, MA1, RE, RE, WH1, RE, GR1, CY1, MA1\)},
	\{ex_ft, "\\\\\\\\\(\.\)", A\(AY1 \| SYN_BD, YE\)},
	\{ex_ft, "!\(\?:\[\^!\\\\\\\\]\|\\\\\\\\\.\?\)\*!\?\|%\(\?:#\|\[0-9]\+\|@\(\[0-9]\+\)\)\?", A\(WH1 \| SYN_BD, CY1\)},.*(/\* right-to-left characters \*/)
#define CR2L		"ء-يپچژکگی‌-‍؛،»«؟ً-ْٔ"
/\* neutral characters \*/9??0?
grp 09??-16m 1220reg p OK conf.c:315:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg conf.c:3152sc %? %@2132sc!0?
'\''1s/\)\$/).*$/??!219reg conf.c:315:m12sc %? %@2142sc!b1%ya 98?0?
%f> static int vi_status;			/\* permanent status bar \*/
static int vi_tsm;			/\* type of the status message \*/
static int vi_nlmode;			/\* new line mode for vi regions \*/

void \*emalloc\(size_t size\)
\{1??0?
1??+2m 11q0?
%f> static int vi_status;			/\* permanent status bar \*/
static int vi_tsm;			/\* type of the status message \*/
static int vi_nlmode;			/\* new line mode for vi regions \*/4??0?
4??+2m 1220reg p OK vi.c:46:a42sc %? %@2152sc!1q0?
grp 1%f> static int vi_status;			/\* permanent status bar \*/.*?
static int vi_tsm;			/\* type of the status message \*/.*?
(static int vi_nlmode;			/\* new line mode for vi regions \*/)7??0?
grp 07??m 1220reg p OK vi.c:46:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> static int vi_scrollud;			/\* scroll amount for \^u and \^d \*/
static int vi_scrolley;			/\* scroll amount for \^e and \^y \*/
static int vi_cndir = 1;		/\* \^n direction \*/.*(	void \*p;)
	if \(!\(p = malloc\(size\)\)\) \{
		fprintf\(stderr, "\\nmalloc: out of memory\\n"\);8??0?
grp 08??-4m 1220reg p OK vi.c:46:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> static int vi_charcmd;			/\* the character finding command \*/
static int vi_ybuf;			/\* current yank buffer, -1 if not given \*/
static int vi_col;			/\* the column requested by \| command \*/.*(void \*erealloc\(void \*p, size_t size\))
\{
	if \(!\(p = realloc\(p, size\)\)\) \{9??0?
grp 09??-12m 1220reg p OK vi.c:46:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg vi.c:462sc %? %@2132sc!0?
?0?
%f+ 	ret = func; \\
} } \\

static void vi_drawrow\(int row\)
\{
	int l1, i, i1, lnnum = vi_lnnum;1??0?
1??+2m 21q0?
%f+ 	ret = func; \\
} } \\

4??0?
4??+2m 2220reg p OK vi.c:127:a42sc %? %@2152sc!1q0?
m 01;0grp 1%f> 	i = i > 99 \? i % 100 : i; \\
	itoa\(i%10 \? i%10 : i, snum\); \\
	tmp\[l1] = \*snum; \\.*(	char \*c, \*s;)
	static char ch\[5] = "~";
	if \(xmpt == 1 && !vi_status && row == xtop \+ xrows - 1\)8??0?
grp 08??-4m 2220reg p OK vi.c:127:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 	l1 = ren_next\(c, ren_pos\(c, noff\), 1\)-1-xleft\+vi_lncol; \\
	if \(l1 > xcols \|\| l1 < 0 \|\| ret \|\| l1 >= rstate->cmax \+ vi_lncol\) \\
		break; \\.*(	if \(\*vi_word && xled\) \{)
		int noff, nrow, ret;
		c = lbuf_get\(xb, xrow\);9??0?
grp 09??-8m 2220reg p OK vi.c:127:a92sc %? %@2152sc!'\''00?
1;4;8;9??!219reg vi.c:1272sc %? %@2132sc!0?
?0?
%f+ 		vi_lncol = dir_context\(s\) < 0 \? 0 : l1;
		memset\(c, '\'' '\'', l1 - \(c - tmp\)\);
		c\[l1 - \(c - tmp\)] = '\''\\0'\'';
		led_crender\(s, row - xtop, l1, xleft, xleft \+ xcols - l1\)
		preserve\(int, syn_blockhl, syn_blockhl = -1;\)
		preserve\(int, ftidx,\)1??0?
1??+2m 31q0?
%f+ 		vi_lncol = dir_context\(s\) < 0 \? 0 : l1;
		memset\(c, '\'' '\'', l1 - \(c - tmp\)\);
		c\[l1 - \(c - tmp\)] = '\''\\0'\'';4??0?
4??+2m 3220reg p OK vi.c:195:a42sc %? %@2152sc!1q0?
grp 1%f+ 		vi_lncol = dir_context\(s\) < 0 \? 0 : l1;.*?
		memset\(c, '\'' '\'', l1 - \(c - tmp\)\);.*?
(		c\[l1 - \(c - tmp\)] = '\''\\0'\'';)7??0?
grp 07??m 3220reg p OK vi.c:195:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 		}
		\*c = '\''\\0'\'';
		l1 = \(c - tmp\) \+ \(i\+i1 - \(strlen\(tmp\) - !!i - !!i1\)\);.*(		syn_setft\(nn_ft\);)
		if \(\(lnnum == 1 \|\| lnnum & 4\) && !xleft && vi_lncol\) \{
			for \(i1 = 0; i1 < rstate->cmax &&8??0?
grp 08??-4m 3220reg p OK vi.c:195:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 			c = itoa\(abs\(xrow-row\+vi_rshift\), c\);
			\*c\+\+ = '\'' '\'';
			i1 = itoalen\(xrows\);.*(					memchr\(" \\t", \*rstate->chrs\[ren_off\(s, i1\)], 2\);\))
				i1 = ren_next\(s, i1, 1\);
			i1 -= \(itoa\(abs\(xrow-row\+vi_rshift\), tmp1\) - tmp1\)\+1;9??0?
grp 09??-7m 3220reg p OK vi.c:195:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg vi.c:1952sc %? %@2132sc!0?
?0?
%f+ 		restore\(ftidx\)
		return;
	}
	led_crender\(s, row - xtop, 0, xleft, xleft \+ xcols\)
	rstate = rstates;
}1??0?
1??+2m 41q0?
%f+ 		restore\(ftidx\)
		return;
	}4??0?
4??+2m 4220reg p OK vi.c:214:a42sc %? %@2152sc!1q0?
m 01;0grp 1%f> 		}
		RS\(2, led_prender\(tmp, row - xtop, 0, 0, l1\)\)
		restore\(syn_blockhl\).*(/\* redraw the screen \*/)
static void vi_drawagain\(int i\)
\{8??0?
grp 08??-5m 4220reg p OK vi.c:214:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 				memset\(p, '\'' '\'', strlen\(p\)\);
				RS\(2, led_prender\(tmp1, row - xtop, l1\+i1, 0, l1\)\)
			}.*(	for \(; i < xtop \+ xrows; i\+\+\))
		vi_drawrow\(i\);
}9??0?
grp 09??-9m 4220reg p OK vi.c:214:a92sc %? %@2152sc!'\''00?
1;4;8;9??!219reg vi.c:2142sc %? %@2132sc!0?
?0?
%f+ 	char cbuf\[8] = "", vi_msg\[512], \*c;
	col = vi_off2col\(xb, xrow, xoff\);
	col = ren_cursor\(lbuf_get\(xb, xrow\), col\) \+ 1;
	if \(type && lbuf_get\(xb, xrow\)\) \{
		c = rstate->chrs\[xoff];
		uc_code\(cp, c, l\)1??0?
1??+2m 51q0?
%f+ 	char cbuf\[8] = "", vi_msg\[512], \*c;
	col = vi_off2col\(xb, xrow, xoff\);
	col = ren_cursor\(lbuf_get\(xb, xrow\), col\) \+ 1;4??0?
4??+2m 5220reg p OK vi.c:497:a42sc %? %@2152sc!1q0?
grp 1%f+ 	char cbuf\[8] = "", vi_msg\[512], \*c;.*?
	col = vi_off2col\(xb, xrow, xoff\);.*?
(	col = ren_cursor\(lbuf_get\(xb, xrow\), col\) \+ 1;)7??0?
grp 07??m 5220reg p OK vi.c:497:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> \{
	int l, col;
	unsigned int cp;.*(static int vi_region\(int cmd, int \*row, int \*off\))
\{
	static sbuf \*savepath\[5];8??0?
grp 08??-19m 5220reg p OK vi.c:497:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> static char rep_cmd\[sizeof\(icmd\)];	/\* the last command \*/
static int rep_len;
#define rep_record\(\) memcpy\(rep_cmd, icmd, icmd_pos\); rep_len = icmd_pos;.*(	static rset \*bre;)
	static int srow\[5], soff\[5], lkwdcnt;
	static int cadir = 1;9??0?
grp 09??-22m 5220reg p OK vi.c:497:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg vi.c:4972sc %? %@2132sc!0?
?0?
%f+ 		c = rstate->chrs\[xoff];
		uc_code\(cp, c, l\)
		memcpy\(cbuf, c, l\);
		snprintf\(vi_msg, sizeof\(vi_msg\), "<%s> 0x%x 0%o %u %dL %dW S%td O%d C%d",
			cbuf, cp, cp, cp, l, rstate->wid\[xoff], c - lbuf_get\(xb, xrow\),1??0?
1??+3m 61q0?
%f+ 		snprintf\(vi_msg, sizeof\(vi_msg\), "<%s> 0x%x 0%o %u %dL %dW S%td O%d C%d",
			cbuf, cp, cp, cp, l, rstate->wid\[xoff], c - lbuf_get\(xb, xrow\),2??0?
2??m 6220reg p OK vi.c:502:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^		snprintf\(vi_msg, sizeof\(vi_msg\), "<%s> 0x%x 0%o %u %dL %dW S%td O%d C%d",$3??0?
3??m 6220reg p OK vi.c:502:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 		c = rstate->chrs\[xoff];
		uc_code\(cp, c, l\)
		memcpy\(cbuf, c, l\);4??0?
4??+3m 6220reg p OK vi.c:502:a42sc %? %@2152sc!1q0?
;0fr.,$f+ ^			cbuf, cp, cp, cp, l, rstate->wid\[xoff], c - lbuf_get\(xb, xrow\),$5??0?
5??-1m 6220reg p OK vi.c:502:a52sc %? %@2152sc!fr 981qfr 980?
%f+ ..c....s......c...\[......
.........\(c.,.c,.l.
.............,.c.....
......in...v...... .....f.....s... .<... 0..x..%.....%..........d..%...%...
.	.c...,...,.............st..e.>...\[....],.......u......... .....,6??0?
6??+3m 6220reg p OK vi.c:502:a62sc %? %@2152sc!1q0?
grp 1%f+ 		c = rstate->chrs\[xoff];.*?
		uc_code\(cp, c, l\).*?
		memcpy\(cbuf, c, l\);.*?
(		snprintf\(vi_msg, sizeof\(vi_msg\), "<%s> 0x%x 0%o %u %dL %dW S%td O%d C%d",)7??0?
grp 07??m 6220reg p OK vi.c:502:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> \{
	int l, col;
	unsigned int cp;.*(static int vi_region\(int cmd, int \*row, int \*off\))
\{
	static sbuf \*savepath\[5];8??0?
grp 08??-14m 6220reg p OK vi.c:502:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> static char rep_cmd\[sizeof\(icmd\)];	/\* the last command \*/
static int rep_len;
#define rep_record\(\) memcpy\(rep_cmd, icmd, icmd_pos\); rep_len = icmd_pos;.*(	static rset \*bre;)
	static int srow\[5], soff\[5], lkwdcnt;
	static int cadir = 1;9??0?
grp 09??-17m 6220reg p OK vi.c:502:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg vi.c:5022sc %? %@2132sc!0?
?0?
%f+ 			cbuf, cp, cp, cp, l, rstate->wid\[xoff], c - lbuf_get\(xb, xrow\),
			xoff, col\);
	} else \{
		snprintf\(vi_msg, sizeof\(vi_msg\),1??0?
1??+1m 71q0?
%f+ 			xoff, col\);
	} else \{
		snprintf\(vi_msg, sizeof\(vi_msg\),2??0?
2??m 7220reg p OK vi.c:504:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^			xoff, col\);$3??0?
3??m 7220reg p OK vi.c:504:a32sc %? %@2152sc!fr 981qfr 980?
;0fr.,$f+ ^			cbuf, cp, cp, cp, l, rstate->wid\[xoff], c - lbuf_get\(xb, xrow\),$4??0?
4??+1m 7220reg p OK vi.c:504:a42sc %? %@2152sc!fr 981qfr 980?
%f+ 	} else \{
		snprintf\(vi_msg, sizeof\(vi_msg\),5??0?
5??-1m 7220reg p OK vi.c:504:a52sc %? %@2152sc!1q0?
%f+ .....uf, cp. ....... l...s.....................l..f..et.x....r....
.	.x.... .....
...e.s. .
........tf..........i..........g\),6??0?
6??+1m 7220reg p OK vi.c:504:a62sc %? %@2152sc!1q0?
grp 1%f+ 			cbuf, cp, cp, cp, l, rstate->wid\[xoff], c - lbuf_get\(xb, xrow\),.*?
(			xoff, col\);)7??0?
grp 07??m 7220reg p OK vi.c:504:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> \{
	int l, col;
	unsigned int cp;.*(static int vi_region\(int cmd, int \*row, int \*off\))
\{
	static sbuf \*savepath\[5];8??0?
grp 08??-12m 7220reg p OK vi.c:504:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> static char rep_cmd\[sizeof\(icmd\)];	/\* the last command \*/
static int rep_len;
#define rep_record\(\) memcpy\(rep_cmd, icmd, icmd_pos\); rep_len = icmd_pos;.*(	static rset \*bre;)
	static int srow\[5], soff\[5], lkwdcnt;
	static int cadir = 1;9??0?
grp 09??-15m 7220reg p OK vi.c:504:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg vi.c:5042sc %? %@2132sc!0?
?0?
%f+ 	} else \{
		snprintf\(vi_msg, sizeof\(vi_msg\),
			"\\"%s\\"%s%dL %d%% L%d C%d B%td",
			xb_path\[0] \? xb_path : "unnamed",
			xb->modified \? "\* " : " ", lbuf_len\(xb\),
			xrow \* 100 / MAX\(1, lbuf_len\(xb\)-1\), xrow\+1, col,1??0?
1??+2m 81q0?
%f+ 			"\\"%s\\"%s%dL %d%% L%d C%d B%td",
			xb_path\[0] \? xb_path : "unnamed",
			xb->modified \? "\* " : " ", lbuf_len\(xb\),
			xrow \* 100 / MAX\(1, lbuf_len\(xb\)-1\), xrow\+1, col,2??0?
2??m 8220reg p OK vi.c:507:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^			"\\"%s\\"%s%dL %d%% L%d C%d B%td",$3??0?
3??m 8220reg p OK vi.c:507:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 	} else \{
		snprintf\(vi_msg, sizeof\(vi_msg\),4??0?
4??+2m 8220reg p OK vi.c:507:a42sc %? %@2152sc!1q0?
%f+ 			xb_path\[0] \? xb_path : "unnamed",
			xb->modified \? "\* " : " ", lbuf_len\(xb\),
			xrow \* 100 / MAX\(1, lbuf_len\(xb\)-1\), xrow\+1, col,5??0?
5??-1m 8220reg p OK vi.c:507:a52sc %? %@2152sc!1q0?
%f+ .}...s...
.........f\(...m........o...i..s...
.......s\\...... %....L%. ..d.B.td".
...x..p...\[0....x..p.t.....u.named..
..	x.-.....fi......\*.".....".....f.........
.	.x.o......../....... .b......\(............\+....o..6??0?
6??+2m 8220reg p OK vi.c:507:a62sc %? %@2152sc!1q0?
grp 1%f+ 	} else \{.*?
		snprintf\(vi_msg, sizeof\(vi_msg\),.*?
(			"\\"%s\\"%s%dL %d%% L%d C%d B%td",)7??0?
grp 07??m 8220reg p OK vi.c:507:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> \{
	int l, col;
	unsigned int cp;.*(static int vi_region\(int cmd, int \*row, int \*off\))
\{
	static sbuf \*savepath\[5];8??0?
grp 08??-9m 8220reg p OK vi.c:507:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> static char rep_cmd\[sizeof\(icmd\)];	/\* the last command \*/
static int rep_len;
#define rep_record\(\) memcpy\(rep_cmd, icmd, icmd_pos\); rep_len = icmd_pos;.*(	static rset \*bre;)
	static int srow\[5], soff\[5], lkwdcnt;
	static int cadir = 1;9??0?
grp 09??-12m 8220reg p OK vi.c:507:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg vi.c:5072sc %? %@2132sc!0?
?0?
%f+ 			xb_path\[0] \? xb_path : "unnamed",
			xb->modified \? "\* " : " ", lbuf_len\(xb\),
			xrow \* 100 / MAX\(1, lbuf_len\(xb\)-1\), xrow\+1, col,
			istempbuf\(ex_buf\) \? tempbufs - ex_buf - 1 : ex_buf - bufs\);
	}
	vi_drawmsg_mpt\(vi_msg\)
}1??0?
1??+3m 91q0?
%f+ 			istempbuf\(ex_buf\) \? tempbufs - ex_buf - 1 : ex_buf - bufs\);
	}
	vi_drawmsg_mpt\(vi_msg\)
}2??0?
2??m 9220reg p OK vi.c:511:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^			istempbuf\(ex_buf\) \? tempbufs - ex_buf - 1 : ex_buf - bufs\);$3??0?
3??m 9220reg p OK vi.c:511:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 			xb_path\[0] \? xb_path : "unnamed",
			xb->modified \? "\* " : " ", lbuf_len\(xb\),
			xrow \* 100 / MAX\(1, lbuf_len\(xb\)-1\), xrow\+1, col,4??0?
4??+3m 9220reg p OK vi.c:511:a42sc %? %@2152sc!1q0?
%f+ 	}
	vi_drawmsg_mpt\(vi_msg\)
}5??0?
5??-1m 9220reg p OK vi.c:511:a52sc %? %@2152sc!1q0?
%f+ 		..b_p..h\[.... .._..t... ..n.a...".
.......m........\?..... .."........_le...b..
.....ow.. .0. ....X....l..f.......\)..\). xr..\+...c.l,
.	.i...............\) ....m..u.........uf...1....x.... ..b....;
	.
	.....a.m.......v._.sg.
}6??0?
6??+3m 9220reg p OK vi.c:511:a62sc %? %@2152sc!1q0?
grp 1%f+ 			xb_path\[0] \? xb_path : "unnamed",.*?
			xb->modified \? "\* " : " ", lbuf_len\(xb\),.*?
			xrow \* 100 / MAX\(1, lbuf_len\(xb\)-1\), xrow\+1, col,.*?
(			istempbuf\(ex_buf\) \? tempbufs - ex_buf - 1 : ex_buf - bufs\);)7??0?
grp 07??m 9220reg p OK vi.c:511:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> \{
	int l, col;
	unsigned int cp;.*(static int vi_region\(int cmd, int \*row, int \*off\))
\{
	static sbuf \*savepath\[5];8??0?
grp 08??-5m 9220reg p OK vi.c:511:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> static char rep_cmd\[sizeof\(icmd\)];	/\* the last command \*/
static int rep_len;
#define rep_record\(\) memcpy\(rep_cmd, icmd, icmd_pos\); rep_len = icmd_pos;.*(	static rset \*bre;)
	static int srow\[5], soff\[5], lkwdcnt;
	static int cadir = 1;9??0?
grp 09??-8m 9220reg p OK vi.c:511:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg vi.c:5112sc %? %@2132sc!0?
?0?
%f+ 	free\(sb->s\);
}

static int vc_motion\(int cmd\)
\{
	int r1 = xrow, r2 = xrow;	/\* region rows \*/1??0?
1??+2m 101q0?
%f+ 	free\(sb->s\);
}

4??0?
4??+2m 10220reg p OK vi.c:948:a42sc %? %@2152sc!1q0?
m 01;0grp 1%f> 		sbuf_cut\(sb, 0\)
	}
	xoff = lbuf_indents\(xb, r1\);.*(	int o1 = xoff, o2;		/\* visual region columns \*/)
	int lnmode = 0;			/\* line-based region \*/
	int mv = vi_prefix\(\);8??0?
grp 08??-4m 10220reg p OK vi.c:948:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 		}
		sbufn_str\(sb, ln\)
		lbuf_edit\(xb, sb->s, i, i \+ 1, 0, 0\);.*(	if \(mv\))
		vi_arg = mv;
	o1 = ren_noeol\(lbuf_get\(xb, r1\), o1\);9??0?
grp 09??-8m 10220reg p OK vi.c:948:a92sc %? %@2152sc!'\''00?
1;4;8;9??!219reg vi.c:9482sc %? %@2132sc!0?
?0?
%f+ 				vi_mod \|= 1;
				break;
			case '\''u'\'':
				undo:
				if \(vi_arg >= 0 && !lbuf_undo\(xb, &xrow, &xoff\)\) \{
					vi_mod \|= 1;1??0?
1??+2m 111q0?
%f+ 				vi_mod \|= 1;
				break;
			case '\''u'\'':4??0?
4??+2m 11220reg p OK vi.c:1294:a42sc %? %@2152sc!1q0?
grp 1%f+ 				vi_mod \|= 1;.*?
				break;.*?
(			case '\''u'\'':)7??0?
grp 07??m 11220reg p OK vi.c:1294:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 					bufs_switchwft\(vi_arg < xbufcur \? vi_arg : 0\)
					vc_status\(0\);
				}.*(					goto undo;)
				} else if \(!vi_arg\)
					vi_drawmsg_mpt\("undo failed"\)8??0?
grp 08??-5m 11220reg p OK vi.c:1294:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 				vi_arg = vi_digit\(\);
				if \(vi_arg > -1 && vi_arg < xbufcur\) \{
					switchbuf:.*(			case TK_CTL\('\''r'\''\):)
				redo:
				if \(vi_arg >= 0 && !lbuf_redo\(xb, &xrow, &xoff\)\) \{9??0?
grp 09??-11m 11220reg p OK vi.c:1294:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg vi.c:12942sc %? %@2132sc!0?
?0?
%f+ 				vi_lncol = 0;
				vi_mod \|= 1;
				break;
			case '\''v'\'':
				vi_mod \|= 2;
				k = term_read\(0\);1??0?
1??+2m 121q0?
%f+ 				vi_lncol = 0;
				vi_mod \|= 1;
				break;4??0?
4??+2m 12220reg p OK vi.c:1344:a42sc %? %@2152sc!1q0?
grp 1%f+ 				vi_lncol = 0;.*?
				vi_mod \|= 1;.*?
(				break;)7??0?
grp 07??m 12220reg p OK vi.c:1344:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 					vi_lnnum = vi_lnnum & ~vi_arg;
				else
					vi_lnnum = vi_arg \? vi_lnnum \| vi_arg : !vi_lnnum;.*(					while \(vi_arg\) \{)
						term_push\("j", 1\);
						term_push\(rep_cmd, rep_len\);8??0?
grp 08??-6m 12220reg p OK vi.c:1344:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 				break;
			case '\''#'\'':
				if \(vi_lnnum & vi_arg\).*(						if \(strchr\("iIoOaAsScC", rep_cmd\[0]\)\) \{)
							term_push\("0", 1\);
							if \(noff\)9??0?
grp 09??-9m 12220reg p OK vi.c:1344:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg vi.c:13442sc %? %@2132sc!0?
?0?
%f+ 				vi_mod \|= 1;
				break;
			case '\'':'\'':
				ln = vi_enprompt\(":", NULL, &k, &n\);
				do_excmd:
				if \(k && ln\[n]\) \{1??0?
1??+2m 131q0?
%f+ 				vi_mod \|= 1;
				break;
			case '\'':'\'':4??0?
4??+2m 13220reg p OK vi.c:1448:a42sc %? %@2152sc!1q0?
grp 1%f+ 				vi_mod \|= 1;.*?
				break;.*?
(			case '\'':'\'':)7??0?
grp 07??m 13220reg p OK vi.c:1448:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 				} else
					vi_word = _vi_word \+ \(!\*vi_word \* vi_wsel\);
				vi_rshift = 0;.*(					ex_command\(ln \+ n\))
					if \(xrow != orow && \(xrow < xtop \|\|
							xrow >= xtop \+ xrows - !vi_status\)\)8??0?
grp 08??-4m 13220reg p OK vi.c:1448:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 				if \(vi_arg && vi_arg <= 5\) \{
					vi_wsel = vi_arg;
					vi_word = _vi_word \+ vi_arg;.*(						xtop = MAX\(0, xrow - xrows / 2\);)
				}
				vi_mod \|= 1;9??0?
grp 09??-7m 13220reg p OK vi.c:1448:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg vi.c:14482sc %? %@2132sc!0?
?0?
%f+ 					xmpt = 1;
				break;
			case '\''c'\'':
			case '\''d'\'':1??0?
1??+2m 141q0?
%f+ 					xmpt = 1;
				break;
			case '\''c'\'':4??0?
4??+2m 14220reg p OK vi.c:1467:a42sc %? %@2152sc!1q0?
grp 1%f+ 					xmpt = 1;.*?
				break;.*?
(			case '\''c'\'':)7??0?
grp 07??m 14220reg p OK vi.c:1467:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 					xmpt = xmpt \? xmpt : \(xgrec > 1\);
					continue;
				} else if \(!xmpt\).*(					char pairs\[2];)
					switch\(k\) \{
					case '\''\)'\'': case '\''\('\'': pairs\[0]='\''\('\''; pairs\[1]='\''\)'\''; break;8??0?
grp 08??-5m 14220reg p OK vi.c:1467:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 					vi_drawmsg\(ln\);
				free\(ln\);
				if \(xquit\) \{.*(					case '\'']'\'': case '\''\['\'': pairs\[0]='\''\['\''; pairs\[1]='\'']'\''; break;)
					case '\''}'\'': case '\''\{'\'': pairs\[0]='\''\{'\''; pairs\[1]='\''}'\''; break;
					case '\''>'\'': case '\''<'\'': pairs\[0]='\''<'\''; pairs\[1]='\''>'\''; break;9??0?
grp 09??-8m 14220reg p OK vi.c:1467:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg vi.c:14672sc %? %@2132sc!0?
?0?
%f+ 			case '\''d'\'':
				k = term_read\(0\);
				if \(k == '\''i'\''\) \{
					k = term_read\(0\);1??0?
1??m 151q0?
;0fr.,$f+ ^			case '\''d'\'':$4??0?
4??m 15220reg p OK vi.c:1468:a42sc %? %@2152sc!fr 981qfr 980?
m 01;0grp 1%f> 					xmpt = xmpt \? xmpt : \(xgrec > 1\);
					continue;
				} else if \(!xmpt\).*(					char pairs\[2];)
					switch\(k\) \{
					case '\''\)'\'': case '\''\('\'': pairs\[0]='\''\('\''; pairs\[1]='\''\)'\''; break;8??0?
grp 08??-4m 15220reg p OK vi.c:1468:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 					vi_drawmsg\(ln\);
				free\(ln\);
				if \(xquit\) \{.*(					case '\'']'\'': case '\''\['\'': pairs\[0]='\''\['\''; pairs\[1]='\'']'\''; break;)
					case '\''}'\'': case '\''\{'\'': pairs\[0]='\''\{'\''; pairs\[1]='\''}'\''; break;
					case '\''>'\'': case '\''<'\'': pairs\[0]='\''<'\''; pairs\[1]='\''>'\''; break;9??0?
grp 09??-7m 15220reg p OK vi.c:1468:a92sc %? %@2152sc!'\''00?
1;4;8;9??!219reg vi.c:14682sc %? %@2132sc!0?
?0?
%f+ 			case '\''>'\'':
			case '\''<'\'':
			case TK_CTL\('\''w'\''\):
				k = vc_motion\(c\);
				if \(c == '\''c'\''\)
					goto insert_done;1??0?
1??+2m 161q0?
%f+ 			case '\''>'\'':
			case '\''<'\'':
			case TK_CTL\('\''w'\''\):4??0?
4??+2m 16220reg p OK vi.c:1517:a42sc %? %@2152sc!1q0?
grp 1%f+ 			case '\''>'\'':.*?
			case '\''<'\'':.*?
(			case TK_CTL\('\''w'\''\):)7??0?
grp 07??m 16220reg p OK vi.c:1517:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 				term_dec\(\)
			case '\''y'\'':
			case '\''!'\'':.*(			case '\''I'\'':)
			case '\''i'\'':
			case '\''a'\'':8??0?
grp 08??-5m 16220reg p OK vi.c:1517:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 					out:
					break;
				}.*(			case '\''A'\'':)
			case '\''o'\'':
			case '\''O'\'':9??0?
grp 09??-8m 16220reg p OK vi.c:1517:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg vi.c:15172sc %? %@2132sc!0?
?0?
%f+ 			case '\''A'\'':
			case '\''o'\'':
			case '\''O'\'':
				insert:
				k = vc_insert\(c\);
				insert_done:1??0?
1??+2m 171q0?
%f+ 			case '\''A'\'':
			case '\''o'\'':
			case '\''O'\'':4??0?
4??+2m 17220reg p OK vi.c:1527:a42sc %? %@2152sc!1q0?
grp 1%f+ 			case '\''A'\'':.*?
			case '\''o'\'':.*?
(			case '\''O'\'':)7??0?
grp 07??m 17220reg p OK vi.c:1527:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 			case '\''I'\'':
			case '\''i'\'':
			case '\''a'\'':.*(				if \(k == 127 \|\| k == TK_CTL\('\''w'\''\)\) \{)
					if \(xrow && !\(xoff > 0 && lbuf_eol\(xb, xrow, 1\)\)\) \{
						xrow--;8??0?
grp 08??-4m 17220reg p OK vi.c:1527:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 				if \(c == '\''c'\''\)
					goto insert_done;
				break;.*(						if \(xtop > otop\))
							xtop = otop;
						topfix\(\)9??0?
grp 09??-7m 17220reg p OK vi.c:1527:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg vi.c:15272sc %? %@2132sc!0?
?0?
%f+ 					ex_command\(cmd\)
					restore\(xled\)
					vi_mod \|= 1;
				} else if \(k == '\''~'\'' \|\| k == '\''u'\'' \|\| k == '\''U'\''\)
					vc_motion\(k\);1??0?
1??+3m 181q0?
%f+ 				} else if \(k == '\''~'\'' \|\| k == '\''u'\'' \|\| k == '\''U'\''\)
					vc_motion\(k\);2??0?
2??m 18220reg p OK vi.c:1650:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^				} else if \(k == '\''~'\'' \|\| k == '\''u'\'' \|\| k == '\''U'\''\)$3??0?
3??m 18220reg p OK vi.c:1650:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 					ex_command\(cmd\)
					restore\(xled\)
					vi_mod \|= 1;4??0?
4??+3m 18220reg p OK vi.c:1650:a42sc %? %@2152sc!1q0?
;0fr.,$f+ ^					vc_motion\(k\);$5??0?
5??-1m 18220reg p OK vi.c:1650:a52sc %? %@2152sc!fr 981qfr 980?
%f+ ....	.x....m......d.
.....r.........e..
	.......... .....
..		....s..i...k.=....'\''..... ...... \|........U'\''\)
.	..	vc...t......;6??0?
6??+3m 18220reg p OK vi.c:1650:a62sc %? %@2152sc!1q0?
grp 1%f+ 					ex_command\(cmd\).*?
					restore\(xled\).*?
					vi_mod \|= 1;.*?
(				} else if \(k == '\''~'\'' \|\| k == '\''u'\'' \|\| k == '\''U'\''\))7??0?
grp 07??m 18220reg p OK vi.c:1650:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 					preserve\(int, xled, xled = 0;\)
					char cmd\[64] = "g/\./& ";
					memcpy\(itoa\(vi_arg, cmd\+5\), "gw", sizeof\("gw"\)\);.*(			case '\''X'\'':)
				term_push\("d", 2\);
				goto motion;8??0?
grp 08??-6m 18220reg p OK vi.c:1650:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 					restore\(xvis\)
					vi_mod \|= !texec;
				} else if \(k == '\''q'\''\) \{.*(			case '\''D'\'':)
				term_push\("d\$", 2\);
				goto motion;9??0?
grp 09??-9m 18220reg p OK vi.c:1650:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg vi.c:16502sc %? %@2132sc!0?
?0?
%f+ 					vc_motion\(k\);
				break;
			case '\''x'\'':
				term_push\("d ", 2\);1??0?
1??m 191q0?
;0fr.,$f+ ^					vc_motion\(k\);$4??0?
4??m 19220reg p OK vi.c:1651:a42sc %? %@2152sc!fr 981qfr 980?
m 01;0grp 1%f> 					preserve\(int, xled, xled = 0;\)
					char cmd\[64] = "g/\./& ";
					memcpy\(itoa\(vi_arg, cmd\+5\), "gw", sizeof\("gw"\)\);.*(			case '\''X'\'':)
				term_push\("d", 2\);
				goto motion;8??0?
grp 08??-5m 19220reg p OK vi.c:1651:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 					restore\(xvis\)
					vi_mod \|= !texec;
				} else if \(k == '\''q'\''\) \{.*(			case '\''D'\'':)
				term_push\("d\$", 2\);
				goto motion;9??0?
grp 09??-8m 19220reg p OK vi.c:1651:a92sc %? %@2152sc!'\''00?
1;4;8;9??!219reg vi.c:16512sc %? %@2132sc!0?
?0?
%f+ 				term_push\("yy", 2\);
				goto motion;
			case '\''~'\'':
				term_push\("g~ ", 3\);
				goto motion;
			case '\''C'\'':1??0?
1??+2m 201q0?
%f+ 				term_push\("yy", 2\);
				goto motion;
			case '\''~'\'':4??0?
4??+2m 20220reg p OK vi.c:1665:a42sc %? %@2152sc!1q0?
grp 1%f+ 				term_push\("yy", 2\);.*?
				goto motion;.*?
(			case '\''~'\'':)7??0?
grp 07??m 20220reg p OK vi.c:1665:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 				term_push\("d\$", 2\);
				goto motion;
			case '\''Y'\'':.*(			case '\''r'\'':)
				vi_mod \|= vc_replace\(\);
				break;8??0?
grp 08??-14m 20220reg p OK vi.c:1665:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 				term_push\("d", 2\);
				goto motion;
			case '\''D'\'':.*(			case '\''R'\'':)
				ex_exec\("left0:reg"\);
				break;9??0?
grp 09??-17m 20220reg p OK vi.c:1665:a92sc %? %@2152sc!'\''00?
1;4;7;8;9??!219reg vi.c:16652sc %? %@2132sc!0?
?0?
%f+ 				term_push\("g~ ", 3\);
				goto motion;
			case '\''C'\'':
				term_push\("c\$", 2\);
				goto motion;
			case '\''s'\'':1??0?
1??+3m 211q0?
%f+ 				term_push\("c\$", 2\);
				goto motion;
			case '\''s'\'':2??0?
2??m 21220reg p OK vi.c:1669:a22sc %? %@2152sc!1q0?
%f+ 				term_push\("c\$", 2\);
				goto motion;3??0?
3??m 21220reg p OK vi.c:1669:a32sc %? %@2152sc!1q0?
%f+ 				term_push\("g~ ", 3\);
				goto motion;
			case '\''C'\'':4??0?
4??+3m 21220reg p OK vi.c:1669:a42sc %? %@2152sc!1q0?
;0fr.,$f+ ^			case '\''s'\'':$5??0?
5??-2m 21220reg p OK vi.c:1669:a52sc %? %@2152sc!fr 981qfr 980?
%f+ ..	....._..s.."...".....
	.	.............
......e...'\'':
.			ter..p..h..c... ...
.....o.o........
	.	ca.......6??0?
6??+3m 21220reg p OK vi.c:1669:a62sc %? %@2152sc!1q0?
grp 1%f+ 				term_push\("g~ ", 3\);.*?
				goto motion;.*?
			case '\''C'\'':.*?
(				term_push\("c\$", 2\);)7??0?
grp 07??m 21220reg p OK vi.c:1669:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 				term_push\("d\$", 2\);
				goto motion;
			case '\''Y'\'':.*(			case '\''r'\'':)
				vi_mod \|= vc_replace\(\);
				break;8??0?
grp 08??-10m 21220reg p OK vi.c:1669:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 				term_push\("d", 2\);
				goto motion;
			case '\''D'\'':.*(			case '\''R'\'':)
				ex_exec\("left0:reg"\);
				break;9??0?
grp 09??-13m 21220reg p OK vi.c:1669:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg vi.c:16692sc %? %@2132sc!0?
?0?
%f+ 			case '\''s'\'':
				term_push\("c ", 2\);
				goto motion;
			case '\''S'\'':1??0?
1??+1m 221q0?
%f+ 				term_push\("c ", 2\);
				goto motion;
			case '\''S'\'':2??0?
2??m 22220reg p OK vi.c:1672:a22sc %? %@2152sc!1q0?
%f+ 				term_push\("c ", 2\);
				goto motion;3??0?
3??m 22220reg p OK vi.c:1672:a32sc %? %@2152sc!1q0?
;0fr.,$f+ ^			case '\''s'\'':$4??0?
4??+1m 22220reg p OK vi.c:1672:a42sc %? %@2152sc!fr 981qfr 980?
;0fr.,$f+ ^			case '\''S'\'':$5??0?
5??-2m 22220reg p OK vi.c:1672:a52sc %? %@2152sc!fr 981qfr 980?
%f+ 	.	.a.. '\''s.:
...	.e.m_p.s.\("c.", .\).
..		.o.o .o.ion.
....a.e.'\''.'\''.6??0?
6??+1m 22220reg p OK vi.c:1672:a62sc %? %@2152sc!1q0?
grp 1%f+ 			case '\''s'\'':.*?
(				term_push\("c ", 2\);)7??0?
grp 07??m 22220reg p OK vi.c:1672:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 				term_push\("d\$", 2\);
				goto motion;
			case '\''Y'\'':.*(			case '\''r'\'':)
				vi_mod \|= vc_replace\(\);
				break;8??0?
grp 08??-7m 22220reg p OK vi.c:1672:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 				term_push\("d", 2\);
				goto motion;
			case '\''D'\'':.*(			case '\''R'\'':)
				ex_exec\("left0:reg"\);
				break;9??0?
grp 09??-10m 22220reg p OK vi.c:1672:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg vi.c:16722sc %? %@2132sc!0?
?0?
%f+ 			case '\''S'\'':
				term_push\("cc", 2\);
				motion:
				icmd_pos--;
				goto re_motion;1??0?
1??+1m 231q0?
%f+ 				term_push\("cc", 2\);
				motion:
				icmd_pos--;
				goto re_motion;2??0?
2??m 23220reg p OK vi.c:1675:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^				term_push\("cc", 2\);$3??0?
3??m 23220reg p OK vi.c:1675:a32sc %? %@2152sc!fr 981qfr 980?
;0fr.,$f+ ^			case '\''S'\'':$4??0?
4??+1m 23220reg p OK vi.c:1675:a42sc %? %@2152sc!fr 981qfr 980?
%f+ 				motion:
				icmd_pos--;
				goto re_motion;5??0?
5??-1m 23220reg p OK vi.c:1675:a52sc %? %@2152sc!1q0?
%f+ 	...........
..	.t.r......."..".....
....m.....:
	.........os-..
.		....o..e_....o.;6??0?
6??+1m 23220reg p OK vi.c:1675:a62sc %? %@2152sc!1q0?
grp 1%f+ 			case '\''S'\'':.*?
(				term_push\("cc", 2\);)7??0?
grp 07??m 23220reg p OK vi.c:1675:a72sc %? %@2152sc!1q0?
m 01;0grp 1%f> 				term_push\("d\$", 2\);
				goto motion;
			case '\''Y'\'':.*(			case '\''r'\'':)
				vi_mod \|= vc_replace\(\);
				break;8??0?
grp 08??-4m 23220reg p OK vi.c:1675:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 				term_push\("d", 2\);
				goto motion;
			case '\''D'\'':.*(			case '\''R'\'':)
				ex_exec\("left0:reg"\);
				break;9??0?
grp 09??-7m 23220reg p OK vi.c:1675:a92sc %? %@2152sc!'\''00?
1;2;3;4;5;6;7;8;9??!219reg vi.c:16752sc %? %@2132sc!0?
?0?
%f+ 				vc_status\(0\);
				vi_mod \|= 1;
				break;
			default:
				continue;
			}1??0?
1??+2m 241q0?
%f+ 				vc_status\(0\);
				vi_mod \|= 1;
				break;4??0?
4??+2m 24220reg p OK vi.c:1740:a42sc %? %@2152sc!1q0?
m 01;0grp 1%f> 					ex_exec\("b-2:%d:fd:b-2"\);
				else
					ex_exec\("%d:fd"\);.*(		topfix\(\))
		ln = lbuf_get\(xb, xrow\);
		xoff = ren_noeol\(ln, xoff\);8??0?
grp 08??-5m 24220reg p OK vi.c:1740:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 				if \(!vi_arg\)
					ex_exec\("b-2"\);
				else if \(xb != tempbufs\[1]\.lb\).*(		if \(ln && !rstate->wid\[xoff]\) \{)
			for \(n = xoff, k = n; k < rstate->n && !rstate->wid\[k];\) \{
				if \(!k\)9??0?
grp 09??-8m 24220reg p OK vi.c:1740:a92sc %? %@2152sc!'\''00?
1;4;8;9??!219reg vi.c:17402sc %? %@2132sc!0?
?0?
%f+ 				}
			}
		}
		term_record = 1;
		if \(vi_mod & 1 \|\| xleft != oleft
				\|\| \(vi_lnnum && orow != xrow && !\(vi_lnnum == 2\)\)1??0?
1??+2m 251q0?
%f+ 				}
			}
		}4??0?
4??+2m 25220reg p OK vi.c:1800:a42sc %? %@2152sc!1q0?
m 01;0grp 1%f> 					la\.off = off1;
					sbuf_mem\(led_attsb, &la, sizeof\(la\)\)
					vi_mod \|= row1 == row && orow == xrow \? 2 : 1;.*(				\|\| \(\*vi_word && orow != xrow\)\))
			vi_drawagain\(xtop\);
		else if \(\*vi_word && \(ooff != xoff \|\| vi_mod & 2\)8??0?
grp 08??-4m 25220reg p OK vi.c:1800:a82sc %? %@2152sc!'\''08??1q0?
m 01;0grp 1%f> 					la\.att = hls\[k]\.att\[0];
					sbuf_mem\(led_attsb, &la, sizeof\(la\)\)
					la\.s = lbuf_get\(xb, row1\);.*(				&& xrow\+1 < xtop \+ xrows\))
			vi_drawrow\(xrow\+1\);
		else if \(xtop != otop\)9??0?
grp 09??-7m 25220reg p OK vi.c:1800:a92sc %? %@2152sc!'\''00?
1;4;8;9??!219reg vi.c:18002sc %? %@2132sc!0?
'\''1i static int vi_visual;			/* visual mode: 0=off, '\''v'\''=char, '\''V'\''=line '\''b'\''=block */
static int vi_vrow;			/* selection anchor row */
static int vi_voff;			/* selection anchor column */
??!219reg vi.c:46:m12sc %? %@2142sc!0?
'\''2i static void vi_visual_attrib(char *s, int row)
{
	if (!vi_visual || !s)
		return;
	int ar = vi_vrow, ao = vi_voff;
	int cr = xrow,   co = xoff;
	if (ar > cr || (ar == cr && ao > co)) {
		swap(&ar, &cr);
		swap(&ao, &co);
	}
	if (row < ar || row > cr)
		return;
	if (!led_attsb)
		sbuf_make(led_attsb, sizeof(led_att) * 16)
	led_att la;
	la.att = SYN_RV;
	la.s = s;
	ren_state *r = ren_position(s);
	int rn1 = r->n - 1;
	int o_beg, o_end;
	if (vi_visual == '\''V'\'') {
		o_beg = 0;
		o_end = rn1;
	} else if (vi_visual == '\''b'\'') {
		o_beg = MIN(vi_voff, xoff);
		o_end = MAX(vi_voff, xoff);
	} else if (ar == cr) {
		o_beg = ao; o_end = co;
	} else if (row == ar) {
		o_beg = ao; o_end = lbuf_eol(xb, row, 1);
	} else if (row == cr) {
		o_beg = 0;
		o_end = co;
	} else {
		o_beg = 0;
		o_end = lbuf_eol(xb, row, 1);
	}
	o_beg = MAX(0, MIN(o_beg, rn1));
	o_end = MAX(0, MIN(o_end, rn1));
	for (int o = o_beg; o <= o_end; o++) {
		if (row == xrow && o == xoff)
			continue;
		la.off = o;
		sbuf_mem(led_attsb, &la, (int)sizeof(la))
	}
}

??!219reg vi.c:127:m22sc %? %@2142sc!0?
'\''3i 		vi_visual_attrib(s, row);
??!219reg vi.c:195:m32sc %? %@2142sc!0?
'\''4i 	vi_visual_attrib(s, row);
??!219reg vi.c:214:m42sc %? %@2142sc!0?
'\''5i 	char *vs = vi_visual == '\''V'\'' ? "-- VISUAL LINE -- " :
		   vi_visual == '\''b'\'' ? "-- VISUAL BLOCK -- " :
		   vi_visual ? "-- VISUAL -- " : "";
??!219reg vi.c:497:m52sc %? %@2142sc!0?
'\''6s/d"/d %s"/??!219reg vi.c:502:m62sc %? %@2142sc!0?
'\''7s/l\)/l, vs)/??!219reg vi.c:504:m72sc %? %@2142sc!0?
'\''8s/d"/d %s"/??!219reg vi.c:507:m82sc %? %@2142sc!0?
'\''9s/s\)/s, vs)/??!219reg vi.c:511:m92sc %? %@2142sc!0?
'\''10i static int vc_insert(int cmd);

static int vc_block_insert(int vcmd, int r1, int r2, int ci)
{
	int eol = lbuf_eol(xb, r1, 1);
	xrow = r1;
	xoff = MIN(ci, eol);
	char *old_ln = lbuf_get(xb, r1);
	int old_nbytes = old_ln ? lbuf_s(old_ln)->len : 0;
	int off = MIN(ci, eol);
	if (off > 0) {
		char *cp = rstate->chrs[off];
		if (*cp == '\''\n'\'')
			off--;
	}
	if (vcmd == '\''A'\'' && off < rstate->n)
		off++;
	int ins_byte = rstate->chrs[off] - rstate->chrs[0];
	int key = vc_insert(vcmd == '\''A'\'' ? '\''a'\'' : '\''i'\'');
	char *new_ln = lbuf_get(xb, r1);
	int new_nbytes = new_ln ? lbuf_s(new_ln)->len : 0;
	int added = new_nbytes - old_nbytes;
	if (added <= 0)
		return key;
	char *ins_text = new_ln + ins_byte;
	int added_chars = 0;
	for (char *t = ins_text; t < ins_text + added; t += uc_len(t))
		added_chars++;
	for (int r = r1 + 1; r <= r2; r++) {
		char *ln = lbuf_get(xb, r);
		if (!ln)
			continue;
		int n = uc_slen(ln) - 1;	/* index of '\''\n'\'' = number of content chars */
		int pos;
		if (vcmd == '\''I'\'') {
			if (ci > n)		/* line too short: skip */
				continue;
			pos = ci;
		} else {			/* '\''A'\'': insert after right edge */
			pos = MIN(ci + 1, n);
		}
		char *p = uc_chr(ln, pos);
		char *nl_p = ln + lbuf_s(ln)->len;	/* pointer to '\''\n'\'' byte */
		int pre_bytes = p - ln;
		int post_bytes = nl_p - p + 1;		/* bytes from p through '\''\n'\'' */
		char *new_ln2 = emalloc(pre_bytes + added + post_bytes + 1);
		memcpy(new_ln2, ln, pre_bytes);
		memcpy(new_ln2 + pre_bytes, ins_text, added);
		memcpy(new_ln2 + pre_bytes + added, p, post_bytes);
		new_ln2[pre_bytes + added + post_bytes] = '\''\0'\'';
		lbuf_edit(xb, new_ln2, r, r + 1, pos, pos + added_chars);
		free(new_ln2);
	}
	vi_mod |= r1 != r2 ? 1 : 2;
	return key;
}

#define VCB_BOUNDS \
	char *ln = lbuf_get(xb, r); \
	if (!ln) continue; \
	n = uc_slen(ln) - 1; \
	left = MIN(c_left, n); \
	right = MIN(c_right, n - 1); \
	bp = uc_chr(ln, left); \
	ep = right >= left ? uc_chr(bp, right - left + 1) : bp; \
	nlp = ln + lbuf_s(ln)->len; \
	if (ep > nlp) ep = nlp

static int vc_block_op(int cmd, int r1, int r2, int c_left, int c_right)
{
	int r, n, left, right;
	char *bp, *ep, *nlp;
	if (cmd == '\''y'\'' || cmd == '\''d'\'' || cmd == '\''c'\'') {
		sbuf_smake(yb, 256)
		for (r = r1; r <= r2; r++) {
			VCB_BOUNDS;
			if (ep > bp)
				sbuf_mem(yb, bp, (int)(ep - bp))
			if ((cmd == '\''d'\'' || cmd == '\''c'\'') && left <= right && n) {
				int beg_bytes = (int)(bp - ln);
				int rest_bytes = (int)(nlp - ep + 1);
				char *new_ln = emalloc(beg_bytes + rest_bytes + 1);
				memcpy(new_ln, ln, beg_bytes);
				memcpy(new_ln + beg_bytes, ep, rest_bytes);
				new_ln[beg_bytes + rest_bytes] = '\''\0'\'';
				lbuf_edit(xb, new_ln, r, r + 1, 0, 0);
				free(new_ln);
			}
			sbuf_chr(yb, '\''\n'\'')
		}
		sbuf_nul(yb)
		vi_regput(vi_ybuf < 0 ? xdefreg : vi_ybuf, yb->s, 0);
		free(yb->s);
		if (cmd == '\''d'\'' || cmd == '\''c'\'') {
			xrow = r1;
			xoff = c_left;
		}
		if (cmd == '\''c'\'')
			return vc_block_insert('\''I'\'', r1, r2, c_left);
	} else if (cmd == '\''~'\'' || cmd == '\''u'\'' || cmd == '\''U'\'') {
		for (r = r1; r <= r2; r++) {
			VCB_BOUNDS;
			if (left > right || !n)
				continue;
			int total = lbuf_s(ln)->len + 2;
			char *new_ln = emalloc(total);
			memcpy(new_ln, ln, total - 1);
			new_ln[total - 1] = '\''\0'\'';
			char *p = new_ln + (bp - ln);
			char *pe = new_ln + (ep - ln);
			while (p < pe) {
				int ch = (unsigned char)*p;
				if (ch <= 0x7f) {
					if (cmd == '\''u'\'')
						*p = (char)tolower(ch);
					else if (cmd == '\''U'\'')
						*p = (char)toupper(ch);
					else
						*p = (char)(islower(ch) ? toupper(ch) : tolower(ch));
				}
				p += uc_len(p);
			}
			lbuf_edit(xb, new_ln, r, r + 1, 0, 0);
			free(new_ln);
		}
	} else if (cmd == '\''>'\'' || cmd == '\''<'\'')
		vi_shift(r1, r2, cmd == '\''>'\'' ? +1 : -1, 1);
	vi_mod |= r1 != r2 ? 1 : 2;
	return 0;
}

static int vc_visual_op(int cmd)
{
	int r1 = vi_vrow, o1 = vi_voff;
	int r2 = xrow, o2 = xoff;
	if (r1 > r2 || (r1 == r2 && o1 > o2)) {
		swap(&r1, &r2);
		swap(&o1, &o2);
	}
	int visual = vi_visual;
	int lnmode = visual == '\''V'\'';
	vi_visual = 0;
	if (visual == '\''b'\'')
		return vc_block_op(cmd, r1, r2, MIN(o1, o2), MAX(o1, o2));
	if (!lnmode) {
		if (o2 < lbuf_eol(xb, r2, 2))
			o2++;		/* include char under cursor, like vc_motion */
		ren_state *r = (ren_state*)lbuf_get(xb, r1);
		r = r ? ren_position((char*)r) : NULL;
		o1 = r ? MAX(0, MIN(o1, r->n)) : 0;
	} else {
		o1 = 0;
		o2 = lbuf_eol(xb, r2, r1 >= r2);
	}
	int key = 0;
	int prevlen = lbuf_len(xb);
	if (cmd == '\''y'\'')
		vi_yank(r1, o1, r2, o2, lnmode);
	else if (cmd == '\''d'\'')
		vi_delete(r1, o1, r2, o2, lnmode);
	else if (cmd == '\''c'\'')
		key = vi_change(r1, o1, r2, o2, lnmode);
	else if (cmd == '\''~'\'' || cmd == '\''u'\'' || cmd == '\''U'\'')
		vi_case(r1, o1, r2, o2, lnmode, cmd);
	else if (cmd == '\''!'\'')
		vi_pipe(r1, r2);
	else if (cmd == '\''>'\'' || cmd == '\''<'\'')
		vi_shift(r1, r2, cmd == '\''>'\'' ? +1 : -1, 1);
	vi_mod |= r1 != r2 || prevlen != lbuf_len(xb) ? 1 : 2;
	return key;
}

??!219reg vi.c:948:m102sc %? %@2142sc!0?
'\''11i 				if (vi_visual) {
					vc_visual_op('\''u'\'');
					break;
				}
??!219reg vi.c:1294:m112sc %? %@2142sc!0?
'\''12i 			case '\''U'\'':
				if (vi_visual)
					vc_visual_op('\''U'\'');
				break;
??!219reg vi.c:1344:m122sc %? %@2142sc!0?
'\''13i 				if (vi_visual == '\''v'\'' || vi_visual == '\''V'\'') {
					char range[128];
					int vr1 = MIN(vi_vrow, xrow), vr2 = MAX(vi_vrow, xrow);
					char *p = itoa(vr1+1, range);
					*p++ = '\'','\'';
					p = itoa(vr2+1, p);
					if (vi_visual == '\''v'\'') {
						*p++ = '\'';'\'';
						p = itoa(vi_voff, p);
						*p++ = '\'';'\'';
						p = itoa(xoff+1, p);
					}
					*p = '\''\0'\'';
					ln = vi_enprompt(":", range, &k, &n);
					goto do_excmd;
				}
??!219reg vi.c:1448:m132sc %? %@2142sc!0?
'\''14i 				if (vi_visual) {
					k = vc_visual_op('\''c'\'');
					goto insert_done;
				}
??!219reg vi.c:1467:m142sc %? %@2142sc!0?
'\''15i 				if (vi_visual) {
					vc_visual_op('\''d'\'');
					break;
				}
??!219reg vi.c:1468:m152sc %? %@2142sc!0?
'\''16i 				if (vi_visual && c != TK_CTL('\''w'\'')) {
					vc_visual_op(c);
					break;
				}
??!219reg vi.c:1517:m162sc %? %@2142sc!0?
'\''17i 				if (vi_visual == '\''b'\'' && (c == '\''I'\'' || c == '\''A'\'')) {
					int r1b = MIN(vi_vrow, xrow), r2b = MAX(vi_vrow, xrow);
					int c_left = MIN(vi_voff, xoff), c_right = MAX(vi_voff, xoff);
					vi_visual = 0;
					k = vc_block_insert(c, r1b, r2b, c == '\''I'\'' ? c_left : c_right);
					goto insert_done;
				}
??!219reg vi.c:1527:m172sc %? %@2142sc!0?
'\''18s/\)/) {/??!219reg vi.c:1650:m182sc %? %@2142sc!0?
'\''19i 				} else if (k == '\''v'\'' || k == '\''V'\'' || k == '\''b'\'') {
					if (!vi_visual) {		/* fresh selection */
						vi_vrow = xrow;
						vi_voff = xoff;
					}
					vi_visual = vi_visual == k ? 0 : k;
					vi_mod |= 1;
				}
??!219reg vi.c:1651:m192sc %? %@2142sc!0?
'\''20i 				if (vi_visual) {
					vc_visual_op('\''~'\'');
					break;
				}
??!219reg vi.c:1665:m202sc %? %@2142sc!0?
'\''21,#+1d??!219reg vi.c:1669:m212sc %? %@2142sc!0?
'\''22,#+1d??!219reg vi.c:1672:m222sc %? %@2142sc!0?
'\''23c 				if (vi_visual) {
					k = vc_visual_op('\''c'\'');
					goto insert_done;
				}
				if (c == '\''C'\'')
					term_push("c$", 2);
				else if (c == '\''s'\'')
					term_push("c ", 2);
				else
					term_push("cc", 2);
??!219reg vi.c:1675:m232sc %? %@2142sc!0?
'\''24i 			case TK_ESC:
				if (vi_visual) {
					vi_visual = 0;
					vi_mod |= 1;
					break;
				}
				continue;
??!219reg vi.c:1740:m242sc %? %@2142sc!0?
'\''25i 		if (vi_visual)
			vi_mod |= 1;
??!219reg vi.c:1800:m252sc %? %@2142sc!' > "$P2VIF".0
# Compat 231 src=lsp.sh
printf '%s\n' '2sc!fr 98b1%ya 98?0?
%f> 					ex_command\(cmd\)
					restore\(xled\)
					vi_mod \|= 1;
				} else if \(k == '\''~'\'' \|\| k == '\''u'\'' \|\| k == '\''U'\''\) \{ \{
					vc_motion\(k\);
				} else if \(k == '\''v'\'' \|\| k == '\''V'\'' \|\| k == '\''b'\''\) \{
					if \(!vi_visual\) \{		/\* fresh selection \*/1??0?
1??+3m 11q0?
%f> 				} else if \(k == '\''~'\'' \|\| k == '\''u'\'' \|\| k == '\''U'\''\) \{ \{
					vc_motion\(k\);
				} else if \(k == '\''v'\'' \|\| k == '\''V'\'' \|\| k == '\''b'\''\) \{
					if \(!vi_visual\) \{		/\* fresh selection \*/2??0?
2??m 1220reg p OK vi.c:1957:a22sc %? %@2152sc!1q0?
;0fr.,$f> ^				} else if \(k == '\''~'\'' \|\| k == '\''u'\'' \|\| k == '\''U'\''\) \{ \{$3??0?
3??m 1220reg p OK vi.c:1957:a32sc %? %@2152sc!fr 981qfr 980?
%f> 					ex_command\(cmd\)
					restore\(xled\)
					vi_mod \|= 1;4??0?
4??+3m 1220reg p OK vi.c:1957:a42sc %? %@2152sc!1q0?
%f> 					vc_motion\(k\);
				} else if \(k == '\''v'\'' \|\| k == '\''V'\'' \|\| k == '\''b'\''\) \{
					if \(!vi_visual\) \{		/\* fresh selection \*/5??0?
5??-1m 1220reg p OK vi.c:1957:a52sc %? %@2152sc!0?
1;2;3;4;5??!219reg vi.c:19572sc %? %@2132sc!0?
?0?
%f+ 					}
					vi_visual = vi_visual == k \? 0 : k;
					vi_mod \|= 1;
				}
				} else if \(k == '\''K'\''\) \{
					if \(xb_path && xb_path\[0]\)
						lsp_hover\(xb_path, xrow, xoff\);1??0?
1??+3m 21q0?
%f+ 				}
				} else if \(k == '\''K'\''\) \{
					if \(xb_path && xb_path\[0]\)
						lsp_hover\(xb_path, xrow, xoff\);2??0?
2??m 2220reg p OK vi.c:1966:a22sc %? %@2152sc!1q0?
;0fr.,$f+ ^				}$3??0?
3??m 2220reg p OK vi.c:1966:a32sc %? %@2152sc!fr 981qfr 980?
%f+ 					}
					vi_visual = vi_visual == k \? 0 : k;
					vi_mod \|= 1;4??0?
4??+3m 2220reg p OK vi.c:1966:a42sc %? %@2152sc!1q0?
%f+ 				} else if \(k == '\''K'\''\) \{
					if \(xb_path && xb_path\[0]\)
						lsp_hover\(xb_path, xrow, xoff\);5??0?
5??-1m 2220reg p OK vi.c:1966:a52sc %? %@2152sc!0?
1;2;3;4;5??!219reg vi.c:19662sc %? %@2132sc!0?
'\''1s/\{ \{/{/??!219reg vi.c:1957:m12sc %? %@2142sc!0?
'\''2d??!219reg vi.c:1966:m22sc %? %@2142sc!p compat 231 applied: src=lsp.sh' > "$P2VIF".231
EXINIT='%ya 97:? %@97' $VI -e 'conf.c' 'vi.c' "$P2VIF".0 "$P2VIF".231 "$P2VIF".d

if [ $# -gt 0 ]; then
    export P2VI_PATCH="$P2VI_PATCH ${0##*/}"
    next=$1
    shift
    case $next in /*|./*|../*) "$next" "$@" ;; *) "./$next" "$@" ;; esac
fi

exit 0
=== PATCH2VI COMPAT 231 src=lsp.sh ===
=== COMPAT PATCH ===
--- a/vi.c
+++ b/vi.c
@@ -1954,7 +1954,7 @@
 					ex_command(cmd)
 					restore(xled)
 					vi_mod |= 1;
-				} else if (k == '~' || k == 'u' || k == 'U') { {
+				} else if (k == '~' || k == 'u' || k == 'U') {
 					vc_motion(k);
 				} else if (k == 'v' || k == 'V' || k == 'b') {
 					if (!vi_visual) {		/* fresh selection */
@@ -1963,7 +1963,6 @@
 					}
 					vi_visual = vi_visual == k ? 0 : k;
 					vi_mod |= 1;
-				}
 				} else if (k == 'K') {
 					if (xb_path && xb_path[0])
 						lsp_hover(xb_path, xrow, xoff);
=== END ===
=== END COMPAT ===
=== PATCH2VI PATCH ===
diff --git a/conf.c b/conf.c
index ad9395c9..e367f283 100644
--- a/conf.c
+++ b/conf.c
@@ -312,7 +312,7 @@ return|select|switch|type|var))\\>", A(GR1, BL1 | SYN_BD, YE1)},
 		A(GR1 | SYN_BD | SYN_ATT, 1, GR1, AY1, YE, WH1, AY1, YE, WH1, AY1, YE, WH1, AY1, YE, WH1), 2},
 
 	{bar_ft, "^(\".*\").*(\\[[wrf]\\]).*$", A(AY1 | SYN_BD, BL, RE)},
-	{bar_ft, "^<(.+)> (?:[^ ]+ )*([0-9]+L) ([0-9]+W) (S[0-9]+) (O[0-9]+) (C[0-9]+)$",
+	{bar_ft, "^<(.+)> (?:[^ ]+ )*([0-9]+L) ([0-9]+W) (S[0-9]+) (O[0-9]+) (C[0-9]+).*$",
 		A(AY1 | SYN_BD, RE1, BL, YE, MA, CY1, YE1)},
 	{bar_ft, "^(\".*\").* ([0-9]{1,3}%) (L[0-9]+) (C[0-9]+) (B-?[0-9]+)?.*$",
 		A(AY1 | SYN_BD, BL, RE1, BL, YE1, GR)},
diff --git a/vi.c b/vi.c
index 2f4ccc2b..776e0f41 100644
--- a/vi.c
+++ b/vi.c
@@ -44,6 +44,9 @@ static int vi_cndir = 1;		/* ^n direction */
 static int vi_status;			/* permanent status bar */
 static int vi_tsm;			/* type of the status message */
 static int vi_nlmode;			/* new line mode for vi regions */
+static int vi_visual;			/* visual mode: 0=off, 'v'=char, 'V'=line 'b'=block */
+static int vi_vrow;			/* selection anchor row */
+static int vi_voff;			/* selection anchor column */
 
 void *emalloc(size_t size)
 {
@@ -125,6 +128,53 @@ for (i = 0, ret = 0;; i++) { \
 	ret = func; \
 } } \
 
+static void vi_visual_attrib(char *s, int row)
+{
+	if (!vi_visual || !s)
+		return;
+	int ar = vi_vrow, ao = vi_voff;
+	int cr = xrow,   co = xoff;
+	if (ar > cr || (ar == cr && ao > co)) {
+		swap(&ar, &cr);
+		swap(&ao, &co);
+	}
+	if (row < ar || row > cr)
+		return;
+	if (!led_attsb)
+		sbuf_make(led_attsb, sizeof(led_att) * 16)
+	led_att la;
+	la.att = SYN_RV;
+	la.s = s;
+	ren_state *r = ren_position(s);
+	int rn1 = r->n - 1;
+	int o_beg, o_end;
+	if (vi_visual == 'V') {
+		o_beg = 0;
+		o_end = rn1;
+	} else if (vi_visual == 'b') {
+		o_beg = MIN(vi_voff, xoff);
+		o_end = MAX(vi_voff, xoff);
+	} else if (ar == cr) {
+		o_beg = ao; o_end = co;
+	} else if (row == ar) {
+		o_beg = ao; o_end = lbuf_eol(xb, row, 1);
+	} else if (row == cr) {
+		o_beg = 0;
+		o_end = co;
+	} else {
+		o_beg = 0;
+		o_end = lbuf_eol(xb, row, 1);
+	}
+	o_beg = MAX(0, MIN(o_beg, rn1));
+	o_end = MAX(0, MIN(o_end, rn1));
+	for (int o = o_beg; o <= o_end; o++) {
+		if (row == xrow && o == xoff)
+			continue;
+		la.off = o;
+		sbuf_mem(led_attsb, &la, (int)sizeof(la))
+	}
+}
+
 static void vi_drawrow(int row)
 {
 	int l1, i, i1, lnnum = vi_lnnum;
@@ -193,6 +243,7 @@ static void vi_drawrow(int row)
 		vi_lncol = dir_context(s) < 0 ? 0 : l1;
 		memset(c, ' ', l1 - (c - tmp));
 		c[l1 - (c - tmp)] = '\0';
+		vi_visual_attrib(s, row);
 		led_crender(s, row - xtop, l1, xleft, xleft + xcols - l1)
 		preserve(int, syn_blockhl, syn_blockhl = -1;)
 		preserve(int, ftidx,)
@@ -212,6 +263,7 @@ static void vi_drawrow(int row)
 		restore(ftidx)
 		return;
 	}
+	vi_visual_attrib(s, row);
 	led_crender(s, row - xtop, 0, xleft, xleft + xcols)
 	rstate = rstates;
 }
@@ -495,20 +547,23 @@ static void vc_status(int type)
 	char cbuf[8] = "", vi_msg[512], *c;
 	col = vi_off2col(xb, xrow, xoff);
 	col = ren_cursor(lbuf_get(xb, xrow), col) + 1;
+	char *vs = vi_visual == 'V' ? "-- VISUAL LINE -- " :
+		   vi_visual == 'b' ? "-- VISUAL BLOCK -- " :
+		   vi_visual ? "-- VISUAL -- " : "";
 	if (type && lbuf_get(xb, xrow)) {
 		c = rstate->chrs[xoff];
 		uc_code(cp, c, l)
 		memcpy(cbuf, c, l);
-		snprintf(vi_msg, sizeof(vi_msg), "<%s> 0x%x 0%o %u %dL %dW S%td O%d C%d",
+		snprintf(vi_msg, sizeof(vi_msg), "<%s> 0x%x 0%o %u %dL %dW S%td O%d C%d %s",
 			cbuf, cp, cp, cp, l, rstate->wid[xoff], c - lbuf_get(xb, xrow),
-			xoff, col);
+			xoff, col, vs);
 	} else {
 		snprintf(vi_msg, sizeof(vi_msg),
-			"\"%s\"%s%dL %d%% L%d C%d B%td",
+			"\"%s\"%s%dL %d%% L%d C%d B%td %s",
 			xb_path[0] ? xb_path : "unnamed",
 			xb->modified ? "* " : " ", lbuf_len(xb),
 			xrow * 100 / MAX(1, lbuf_len(xb)-1), xrow+1, col,
-			istempbuf(ex_buf) ? tempbufs - ex_buf - 1 : ex_buf - bufs);
+			istempbuf(ex_buf) ? tempbufs - ex_buf - 1 : ex_buf - bufs, vs);
 	}
 	vi_drawmsg_mpt(vi_msg)
 }
@@ -946,6 +1001,178 @@ static void vi_shift(int r1, int r2, int dir, int count)
 	free(sb->s);
 }
 
+static int vc_insert(int cmd);
+
+static int vc_block_insert(int vcmd, int r1, int r2, int ci)
+{
+	int eol = lbuf_eol(xb, r1, 1);
+	xrow = r1;
+	xoff = MIN(ci, eol);
+	char *old_ln = lbuf_get(xb, r1);
+	int old_nbytes = old_ln ? lbuf_s(old_ln)->len : 0;
+	int off = MIN(ci, eol);
+	if (off > 0) {
+		char *cp = rstate->chrs[off];
+		if (*cp == '\n')
+			off--;
+	}
+	if (vcmd == 'A' && off < rstate->n)
+		off++;
+	int ins_byte = rstate->chrs[off] - rstate->chrs[0];
+	int key = vc_insert(vcmd == 'A' ? 'a' : 'i');
+	char *new_ln = lbuf_get(xb, r1);
+	int new_nbytes = new_ln ? lbuf_s(new_ln)->len : 0;
+	int added = new_nbytes - old_nbytes;
+	if (added <= 0)
+		return key;
+	char *ins_text = new_ln + ins_byte;
+	int added_chars = 0;
+	for (char *t = ins_text; t < ins_text + added; t += uc_len(t))
+		added_chars++;
+	for (int r = r1 + 1; r <= r2; r++) {
+		char *ln = lbuf_get(xb, r);
+		if (!ln)
+			continue;
+		int n = uc_slen(ln) - 1;	/* index of '\n' = number of content chars */
+		int pos;
+		if (vcmd == 'I') {
+			if (ci > n)		/* line too short: skip */
+				continue;
+			pos = ci;
+		} else {			/* 'A': insert after right edge */
+			pos = MIN(ci + 1, n);
+		}
+		char *p = uc_chr(ln, pos);
+		char *nl_p = ln + lbuf_s(ln)->len;	/* pointer to '\n' byte */
+		int pre_bytes = p - ln;
+		int post_bytes = nl_p - p + 1;		/* bytes from p through '\n' */
+		char *new_ln2 = emalloc(pre_bytes + added + post_bytes + 1);
+		memcpy(new_ln2, ln, pre_bytes);
+		memcpy(new_ln2 + pre_bytes, ins_text, added);
+		memcpy(new_ln2 + pre_bytes + added, p, post_bytes);
+		new_ln2[pre_bytes + added + post_bytes] = '\0';
+		lbuf_edit(xb, new_ln2, r, r + 1, pos, pos + added_chars);
+		free(new_ln2);
+	}
+	vi_mod |= r1 != r2 ? 1 : 2;
+	return key;
+}
+
+#define VCB_BOUNDS \
+	char *ln = lbuf_get(xb, r); \
+	if (!ln) continue; \
+	n = uc_slen(ln) - 1; \
+	left = MIN(c_left, n); \
+	right = MIN(c_right, n - 1); \
+	bp = uc_chr(ln, left); \
+	ep = right >= left ? uc_chr(bp, right - left + 1) : bp; \
+	nlp = ln + lbuf_s(ln)->len; \
+	if (ep > nlp) ep = nlp
+
+static int vc_block_op(int cmd, int r1, int r2, int c_left, int c_right)
+{
+	int r, n, left, right;
+	char *bp, *ep, *nlp;
+	if (cmd == 'y' || cmd == 'd' || cmd == 'c') {
+		sbuf_smake(yb, 256)
+		for (r = r1; r <= r2; r++) {
+			VCB_BOUNDS;
+			if (ep > bp)
+				sbuf_mem(yb, bp, (int)(ep - bp))
+			if ((cmd == 'd' || cmd == 'c') && left <= right && n) {
+				int beg_bytes = (int)(bp - ln);
+				int rest_bytes = (int)(nlp - ep + 1);
+				char *new_ln = emalloc(beg_bytes + rest_bytes + 1);
+				memcpy(new_ln, ln, beg_bytes);
+				memcpy(new_ln + beg_bytes, ep, rest_bytes);
+				new_ln[beg_bytes + rest_bytes] = '\0';
+				lbuf_edit(xb, new_ln, r, r + 1, 0, 0);
+				free(new_ln);
+			}
+			sbuf_chr(yb, '\n')
+		}
+		sbuf_nul(yb)
+		vi_regput(vi_ybuf < 0 ? xdefreg : vi_ybuf, yb->s, 0);
+		free(yb->s);
+		if (cmd == 'd' || cmd == 'c') {
+			xrow = r1;
+			xoff = c_left;
+		}
+		if (cmd == 'c')
+			return vc_block_insert('I', r1, r2, c_left);
+	} else if (cmd == '~' || cmd == 'u' || cmd == 'U') {
+		for (r = r1; r <= r2; r++) {
+			VCB_BOUNDS;
+			if (left > right || !n)
+				continue;
+			int total = lbuf_s(ln)->len + 2;
+			char *new_ln = emalloc(total);
+			memcpy(new_ln, ln, total - 1);
+			new_ln[total - 1] = '\0';
+			char *p = new_ln + (bp - ln);
+			char *pe = new_ln + (ep - ln);
+			while (p < pe) {
+				int ch = (unsigned char)*p;
+				if (ch <= 0x7f) {
+					if (cmd == 'u')
+						*p = (char)tolower(ch);
+					else if (cmd == 'U')
+						*p = (char)toupper(ch);
+					else
+						*p = (char)(islower(ch) ? toupper(ch) : tolower(ch));
+				}
+				p += uc_len(p);
+			}
+			lbuf_edit(xb, new_ln, r, r + 1, 0, 0);
+			free(new_ln);
+		}
+	} else if (cmd == '>' || cmd == '<')
+		vi_shift(r1, r2, cmd == '>' ? +1 : -1, 1);
+	vi_mod |= r1 != r2 ? 1 : 2;
+	return 0;
+}
+
+static int vc_visual_op(int cmd)
+{
+	int r1 = vi_vrow, o1 = vi_voff;
+	int r2 = xrow, o2 = xoff;
+	if (r1 > r2 || (r1 == r2 && o1 > o2)) {
+		swap(&r1, &r2);
+		swap(&o1, &o2);
+	}
+	int visual = vi_visual;
+	int lnmode = visual == 'V';
+	vi_visual = 0;
+	if (visual == 'b')
+		return vc_block_op(cmd, r1, r2, MIN(o1, o2), MAX(o1, o2));
+	if (!lnmode) {
+		if (o2 < lbuf_eol(xb, r2, 2))
+			o2++;		/* include char under cursor, like vc_motion */
+		ren_state *r = (ren_state*)lbuf_get(xb, r1);
+		r = r ? ren_position((char*)r) : NULL;
+		o1 = r ? MAX(0, MIN(o1, r->n)) : 0;
+	} else {
+		o1 = 0;
+		o2 = lbuf_eol(xb, r2, r1 >= r2);
+	}
+	int key = 0;
+	int prevlen = lbuf_len(xb);
+	if (cmd == 'y')
+		vi_yank(r1, o1, r2, o2, lnmode);
+	else if (cmd == 'd')
+		vi_delete(r1, o1, r2, o2, lnmode);
+	else if (cmd == 'c')
+		key = vi_change(r1, o1, r2, o2, lnmode);
+	else if (cmd == '~' || cmd == 'u' || cmd == 'U')
+		vi_case(r1, o1, r2, o2, lnmode, cmd);
+	else if (cmd == '!')
+		vi_pipe(r1, r2);
+	else if (cmd == '>' || cmd == '<')
+		vi_shift(r1, r2, cmd == '>' ? +1 : -1, 1);
+	vi_mod |= r1 != r2 || prevlen != lbuf_len(xb) ? 1 : 2;
+	return key;
+}
+
 static int vc_motion(int cmd)
 {
 	int r1 = xrow, r2 = xrow;	/* region rows */
@@ -1292,6 +1519,10 @@ void vi(int init)
 				vi_mod |= 1;
 				break;
 			case 'u':
+				if (vi_visual) {
+					vc_visual_op('u');
+					break;
+				}
 				undo:
 				if (vi_arg >= 0 && !lbuf_undo(xb, &xrow, &xoff)) {
 					vi_mod |= 1;
@@ -1342,6 +1573,10 @@ void vi(int init)
 				vi_lncol = 0;
 				vi_mod |= 1;
 				break;
+			case 'U':
+				if (vi_visual)
+					vc_visual_op('U');
+				break;
 			case 'v':
 				vi_mod |= 2;
 				k = term_read(0);
@@ -1446,6 +1681,22 @@ void vi(int init)
 				vi_mod |= 1;
 				break;
 			case ':':
+				if (vi_visual == 'v' || vi_visual == 'V') {
+					char range[128];
+					int vr1 = MIN(vi_vrow, xrow), vr2 = MAX(vi_vrow, xrow);
+					char *p = itoa(vr1+1, range);
+					*p++ = ',';
+					p = itoa(vr2+1, p);
+					if (vi_visual == 'v') {
+						*p++ = ';';
+						p = itoa(vi_voff, p);
+						*p++ = ';';
+						p = itoa(xoff+1, p);
+					}
+					*p = '\0';
+					ln = vi_enprompt(":", range, &k, &n);
+					goto do_excmd;
+				}
 				ln = vi_enprompt(":", NULL, &k, &n);
 				do_excmd:
 				if (k && ln[n]) {
@@ -1465,7 +1716,15 @@ void vi(int init)
 					xmpt = 1;
 				break;
 			case 'c':
+				if (vi_visual) {
+					k = vc_visual_op('c');
+					goto insert_done;
+				}
 			case 'd':
+				if (vi_visual) {
+					vc_visual_op('d');
+					break;
+				}
 				k = term_read(0);
 				if (k == 'i') {
 					k = term_read(0);
@@ -1515,6 +1774,10 @@ void vi(int init)
 			case '>':
 			case '<':
 			case TK_CTL('w'):
+				if (vi_visual && c != TK_CTL('w')) {
+					vc_visual_op(c);
+					break;
+				}
 				k = vc_motion(c);
 				if (c == 'c')
 					goto insert_done;
@@ -1525,6 +1788,13 @@ void vi(int init)
 			case 'A':
 			case 'o':
 			case 'O':
+				if (vi_visual == 'b' && (c == 'I' || c == 'A')) {
+					int r1b = MIN(vi_vrow, xrow), r2b = MAX(vi_vrow, xrow);
+					int c_left = MIN(vi_voff, xoff), c_right = MAX(vi_voff, xoff);
+					vi_visual = 0;
+					k = vc_block_insert(c, r1b, r2b, c == 'I' ? c_left : c_right);
+					goto insert_done;
+				}
 				insert:
 				k = vc_insert(c);
 				insert_done:
@@ -1647,8 +1917,16 @@ void vi(int init)
 					ex_command(cmd)
 					restore(xled)
 					vi_mod |= 1;
-				} else if (k == '~' || k == 'u' || k == 'U')
+				} else if (k == '~' || k == 'u' || k == 'U') {
 					vc_motion(k);
+				} else if (k == 'v' || k == 'V' || k == 'b') {
+					if (!vi_visual) {		/* fresh selection */
+						vi_vrow = xrow;
+						vi_voff = xoff;
+					}
+					vi_visual = vi_visual == k ? 0 : k;
+					vi_mod |= 1;
+				}
 				break;
 			case 'x':
 				term_push("d ", 2);
@@ -1663,16 +1941,25 @@ void vi(int init)
 				term_push("yy", 2);
 				goto motion;
 			case '~':
+				if (vi_visual) {
+					vc_visual_op('~');
+					break;
+				}
 				term_push("g~ ", 3);
 				goto motion;
 			case 'C':
-				term_push("c$", 2);
-				goto motion;
 			case 's':
-				term_push("c ", 2);
-				goto motion;
 			case 'S':
-				term_push("cc", 2);
+				if (vi_visual) {
+					k = vc_visual_op('c');
+					goto insert_done;
+				}
+				if (c == 'C')
+					term_push("c$", 2);
+				else if (c == 's')
+					term_push("c ", 2);
+				else
+					term_push("cc", 2);
 				motion:
 				icmd_pos--;
 				goto re_motion;
@@ -1738,6 +2025,13 @@ void vi(int init)
 				vc_status(0);
 				vi_mod |= 1;
 				break;
+			case TK_ESC:
+				if (vi_visual) {
+					vi_visual = 0;
+					vi_mod |= 1;
+					break;
+				}
+				continue;
 			default:
 				continue;
 			}
@@ -1798,6 +2092,8 @@ void vi(int init)
 				}
 			}
 		}
+		if (vi_visual)
+			vi_mod |= 1;
 		term_record = 1;
 		if (vi_mod & 1 || xleft != oleft
 				|| (vi_lnnum && orow != xrow && !(vi_lnnum == 2))
