language: c
sudo: false
addons:
  apt:
    packages:
      - libsqlite3-dev
before_script:
  - ./configure --with-ext="oo tree binary sqlite3" --enable-utf8 --ipv6 --disable-docs
script:
  - make test
