#!/bin/bash

# Abort on any errors
set -e

# Process options
while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        --generate-jimsh0)
            GENERATE_JIMSH0=true
        ;;
        --use-tclsh)
            USE_TCLSH=true
        ;;
        --prefix)
            PREFIX="--prefix=$2"
            shift
        ;;
        *)
            echo "Unknown option $1"
            echo "options: --generate-jimsh0 : compile jimsh0 and use it for configuration"
            echo "         --use-tclsh       : use tclsh for configuration (overridden by --generate-jimsh0)"
            echo "         --prefix xxx      : configure prefix setting"
            exit -1
        ;;
    esac
    shift
done

# Print commands and abort on any errors
set -ex

# Get path to source location
SCRIPT=$(readlink -f "$0")
SRC_DIR=$(dirname "$SCRIPT")/../..


if [ "$GENERATE_JIMSH0" == "true" ]; then
    # Force jimsh0 to be generated by providing a 
    # path with bogus copies of jimsh & tclsh
    PATH_EXTRA="$SRC_DIR/tools/ci-test:"
elif [ "$USE_TCLSH" == "true" ]; then
    # Ensure that tclsh is used
    PATH_EXTRA=
    type tclsh >/dev/null 2>&1 || { echo >&2 "tclsh is required for the --use-tclsh option - please ensure it is installed.  Aborting."; exit 1; }
fi

# Build MetaKit if needed
$SRC_DIR/tools/ci-test/buildmk.sh

# Configure with all extensions, maintainer mode,
# code coverage arcs, all warnings enabled as errors

PATH=$PATH_EXTRA$PATH \
    $SRC_DIR/configure \
                   --full \
                   --ssl \
                   --maintainer \
                   --with-ext="sqlite3 zlib readline mk nshelper rlprompt sdl" \
                   --random-hash \
                   $PREFIX \
                   CFLAGS="--coverage \
                           -g \
                           -O0 \
                           -Werror \
                           -Wall \
                           -I$SRC_DIR/mk/include \
                           -L$SRC_DIR/mk/lib" \
                   LDFLAGS="--coverage \
                            -Wl,-rpath,$SRC_DIR/mk/lib \
                           -L$SRC_DIR/mk/lib"

