Document: jimtcl
Title: Debian jimtcl Manual
Author: <insert document author here>
Abstract: This manual describes what jimtcl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/jimtcl/jimtcl.sgml.gz

Format: postscript
Files: /usr/share/doc/jimtcl/jimtcl.ps.gz

Format: text
Files: /usr/share/doc/jimtcl/jimtcl.text.gz

Format: HTML
Index: /usr/share/doc/jimtcl/html/index.html
Files: /usr/share/doc/jimtcl/html/*.html
